<?php
return array(
    'type_category_map' => array(
        0 => array(
            'types' => array(
                0 => 'E_CIGARETTE',
                1 => 'E_PIPE',
            ),
            'path' => [
                'E-ZIGARETTEN',
            ],
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' =>       'E-Zigaretten günstig online kaufen',
                    'description' => 'E-Zigaretten ##topic## günstig kaufen ✓ E-Zigaretten für Einsteiger und Profis ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' =>       '##supplier## E-Zigaretten günstig online kaufen',
                    'description' => 'E-Zigaretten von ##supplier## günstig kaufen ✓ Für Einsteiger und Profis ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'E-Zigarette,günstig,kaufen,##supplier##',
                ]
            ]
        ),
        1 => array(
            'types' => array(
                0 => 'BOX_MOD',
                1 => 'BOX_MOD_CELL',
                2 => 'SQUONKER_BOX',
            ),
            'path' => [
                'AKKUTRÄGER',
            ],
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' => 'Akkuträger und Box Mods für E-Zigaretten günstig online kaufen',
                    'description' => 'Akkuträger und Box Mods günstig kaufen ✓ Für Einsteiger und Profis ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Akkuträger,Box,Box Mod,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' => '##supplier## Akkuträger und Box Mods günstig online kaufen',
                    'description' => 'Akkuträger von ##supplier## günstig kaufen ✓ Für Einsteiger und Profis ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Akkuträger,Box,Box Mod,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ]
        ),
        2 => array(
            'types' => array(
                0 => 'CLEAROMIZER',
            ),
            'path' => [
                'VERDAMPFER',
            ],
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' => 'Verdampfer und Clearomizer für E-Zigaretten günstig online kaufen',
                    'description' => 'Verdampfer für E-Zigaretten günstig kaufen ✓ Für Einsteiger und Profis ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Verdampfer,Clearomizer,Atomizer,Vaporizer,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' => '##supplier## Verdampfer für E-Zigaretten günstig kaufen',
                    'description' => 'Verdampfer von ##supplier## günstig kaufen ✓ Für Einsteiger und Profis ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Verdampfer,Clearomizer,Atomizer,Vaporizer,E-Zigarette,günstig,kaufen,##supplier##',
                ]
            ]
        ),
        3 => array(
            'types' => array(
                0 => 'CLEAROMIZER_RTA',
                1 => 'CLEAROMIZER_RDA',
                2 => 'CLEAROMIZER_RDTA',
                3 => 'CLEAROMIZER_RDSA',
            ),
            'path' => [
                'VERDAMPFER',
                'Selbstwickler',
            ],
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' => 'Selbstwickel-Verdampfer für die E-Zigaratte günstig online kaufen',
                    'description' => 'Selbstwickel-Verdampfer günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Selbstwickler,Verdampfer,Selbstwickel-Verdampfer,Clearomizer,Atomizer,Vaporizer,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' => '##supplier## Selbstwickel-Verdampfer günstig kaufen',
                    'description' => 'Selbstwickel-Verdampfer von ##supplier## günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Selbstwickler,Verdampfer,Selbstwickel-Verdampfer,Clearomizer,Atomizer,Vaporizer,E-Zigarette,günstig,kaufen,##supplier##',
                ]
            ]
        ),
        4 => array(
            'types' => array(
                0 => 'LIQUID',
                1 => 'LIQUID_BOX',
            ),
            'path' => [
                'LIQUID',
            ],
            'append_subcategory' => 'brand',
            'seo' => [
                'base' => [
                    'title' =>       'Liquids für E-Zigaretten günstig online kaufen',
                    'description' => 'Liquids für E-Zigaretten günstig kaufen ✓ Viele Geschmacksrichtungen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Liquid,E-Liquid,günstig,kaufen,E-Zigarette',
                ],
                'brand' => [
                    'title' => '##supplier## Liquids für E-Zigaretten günstig kaufen',
                    'description' => 'Liquids von ##supplier## günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Liquid,E-Liquid,günstig,kaufen,E-Zigarette,##supplier##',
                ]
            ]
        ),
        5 => array(
            'types' => array(
                0 => 'EASY3_CAP',
            ),
            'path' => [
                'LIQUID',
                'Easy 3 Caps'
            ],
            'seo' => [
                'base' => [
                    'title' =>       'Caps für die SC Easy 3 E-Zigarette günstig online kaufen',
                    'description' => 'Caps für die SC Easy 3 E-Zigarette günstig kaufen ✓ Viele Geschmacksrichtungen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Cap,Caps,Cap-System,SC,SC Easy 3,E-Zigarette,günstig,kaufen',
                ]
            ]

        ),
        6 => array(
            'types' => array(
                0 => 'AROMA',
            ),
            'path' => [
                'AROMEN',
            ],
            'append_subcategory' => 'brand',
            'seo' => [
                'base' => [
                    'title' => 'Aromen für E-Zigaretten günstig online kaufen',
                    'description' => 'Aromen und Longfills günstig kaufen ✓ Viele Geschmacksrichtungen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Aroma,Longfill,E-Zigarette,günstig,kaufen',
                ],
                'brand' => [
                    'title' => '##supplier## Aromen für E-Zigaretten günstig kaufen',
                    'description' => 'Aromen von ##supplier## günstig kaufen ✓ Viele Geschmacksrichtungen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Aroma,Longfill,E-Zigarette,günstig,kaufen,##supplier##',
                ]
            ]
        ),
        7 => array(
            'types' => array(
                0 => 'SHAKE_VAPE',
            ),
            'path' => [
                'SHAKE & VAPE',
            ],
            'append_subcategory' => 'brand',
            'seo' => [
                'base' => [
                    'title' =>       'Shake & Vape Liquids für E-Zigaretten günstig online kaufen',
                    'description' => 'Shake & Vape Liquids - Shortfills - günstig kaufen ✓ Viele Geschmacksrichtungen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Shake & Vape,Longfill,E-Liquid,Liquid,E-Zigarette,günstig,kaufen',
                ],
                'brand' => [
                    'title' =>       '##supplier## Shake & Vape Liquids günstig kaufen',
                    'description' => 'Shake & Vape Liquids von ##supplier## günstig kaufen ✓ Viele Geschmacksrichtungen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Shake & Vape,Longfill,E-Liquid,Liquid,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ]
        ),
        8 => array(
            'types' => array(
                0 => 'HEAD',
            ),
            'base_category' => 'ZUBEHÖR > Verdampferköpfe',
            'path' => [
                'ZUBEHÖR',
                'Verdampferköpfe',
            ],
            'seo' => [
                'base' => [
                    'title' =>       'Verdampferköpfe für E-Zigaretten günstig online kaufen',
                    'description' => 'Verdampferköpfe für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Verdampfer, Verdampferkopf,Coil,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' =>       '##supplier## Verdampferköpfe für E-Zigaretten günstig kaufen',
                    'description' => 'Verdampferköpfe von ##supplier## günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Verdampfer, Verdampferkopf,Coil,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ]
        ),
        9 => array(
            'types' => array(
                0 => 'TANK',
                1 => 'TANK_PROTECTION',
            ),
            'base_category' => 'ZUBEHÖR > Glastanks & Schutz',
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' =>       'Glastanks für E-Zigaretten günstig online kaufen',
                    'description' => 'Glastanks für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Glastank,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' =>       '##supplier## Glastanks für E-Zigaretten günstig kaufen',
                    'description' => 'Glastanks für E-Zigaretten von ##supplier## günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Glastank,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ]
        ),
        10 => array(
            'types' => array(
                0 => 'DRIP_TIP',
                1 => 'DRIP_TIP_CAP',
            ),
            'base_category' => 'ZUBEHÖR > Mundstücke & Schutz',
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' =>       'Mundstücke für E-Zigaretten günstig online kaufen',
                    'description' => 'Mundstücke für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Mundstück,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' =>       '##supplier## Mundstücke für E-Zigaretten günstig kaufen',
                    'description' => 'Mundstücke für E-Zigaretten von ##supplier## günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Mundstück,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ]
        ),
        11 => array(
            'types' => array(
                0 => 'SEAL',
            ),
            'base_category' => 'ZUBEHÖR > Dichtungen',
            'append_subcategory' => 'supplier',
            'seo' => [
                'base' => [
                    'title' =>       'Ersatz-Dichtungen für E-Zigaretten günstig online kaufen',
                    'description' => 'Ersatz-Dichtungen für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Dichtung,Ersatzdichtung,Ersatz-Dichtung,E-Zigarette,günstig,kaufen',
                ],
                'supplier' => [
                    'title' =>       '##supplier## Ersatzdichtungen für E-Zigaretten günstig kaufen',
                    'description' => 'Glastanks für E-Zigaretten von ##supplier## günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Dichtung,Ersatzdichtung,Ersatz-Dichtung,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ],
        ),
        12 => array(
            'types' => array(
                0 => 'POD',
                1 => 'CARTRIDGE',
            ),
            'base_category' => 'ZUBEHÖR > Pods & Cartridges',
            'append_subcategory' => 'common_name',
            'seo' => [
                'base' => [
                    'title' =>       'Pods für E-Zigaretten günstig online kaufen',
                    'description' => 'Pods für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Pod,Cartridge,E-Zigarette,günstig,kaufen',
                ],
                'common_name' => [
                    'title' =>       '##supplier## Pods für die ##common_name## E-Zigarette günstig kaufen',
                    'description' => 'Pods für die ##supplier## ##common_name## E-Zigarette günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Pod,Cartridge,E-Zigarette,günstig,kaufen,##supplier##',
                ],
            ],
        ),
        13 => array(
            'types' => array(
                0 => 'CELL',
                1 => 'CELL_BOX',
            ),
            'base_category' => 'ZUBEHÖR > Akkuzellen & -boxen',
            'seo' => [
                'base' => [
                    'title' =>       'Akkus für E-Zigaretten günstig online kaufen',
                    'description' => 'Akkus für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Akku,Akkuzelle,Batterie,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        14 => array(
            'types' => array(
                0 => 'BASE',
                1 => 'SHOT',
            ),
            'base_category' => 'ZUBEHÖR > Basen & Shots',
            'seo' => [
                'base' => [
                    'title' =>       'Basis und Nikotin-Shots für die E-Liquid günstig online kaufen',
                    'description' => 'Basis und Nikotin-Shots für E-Liquid günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Base,Basis,Nikotinshot,Nikotin-Shot,Liquid,E-Liquid,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        15 => array(
            'types' => array(
                0 => 'CHARGER',
                1 => 'CABLE',
            ),
            'base_category' => 'ZUBEHÖR > Ladegeräte & -kabel',
            'seo' => [
                'base' => [
                    'title' =>       'Ladegeräte und -kabel für E-Zigaretten günstig online kaufen',
                    'description' => 'Ladegeräte und -kabel für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Ladegerät,Ladekabel,Kabel,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        16 => array(
            'types' => array(
                0 => 'SQUONKER_BOTTLE',
            ),
            'base_category' => 'ZUBEHÖR > Squonker-Flaschen',
            'seo' => [
                'base' => [
                    'title' =>       'Squonker-Flaschen für E-Zigaretten günstig online kaufen',
                    'description' => 'Squonker-Flaschen für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Squonker-Bottle,Squonkerflasche,Squonker-Flasche,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        17 => array(
            'types' => array(
                0 => 'BAG',
            ),
            'base_category' => 'ZUBEHÖR > Taschen & Etuis',
            'seo' => [
                'base' => [
                    'title' =>       'Taschen & Etuis für E-Zigaretten günstig online kaufen',
                    'description' => 'Taschen & Etuis für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Tasche,Etui,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        18 => array(
            'types' => array(
                0 => 'TOOL',
                1 => 'TOOL_HEATING_PLATE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Werkzeug',
            'seo' => [
                'base' => [
                    'title' =>       'Werkzeug für E-Zigaretten günstig online kaufen',
                    'description' => 'Werkzeug für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Werkzeug,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        19 => array(
            'types' => array(
                0 => 'WADDING',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Watte',
            'seo' => [
                'base' => [
                    'title' =>       'E-Zigarette | Watte und -pads für Selbstwickler günstig online kaufen',
                    'description' => 'Watte für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Watte,Selbstwickler,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        20 => array(
            'types' => array(
                0 => 'WIRE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Wickeldraht',
            'seo' => [
                'base' => [
                    'title' =>       'E-Zigarette | Wickeldraht für Selbstwickler günstig online kaufen',
                    'description' => 'Wickeldraht für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Wickeldraht,Draht,Selbstwickler,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        21 => array(
            'types' => array(
                0 => 'DECK',
                1 => 'RDA_BASE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Decks',
            'seo' => [
                'base' => [
                    'title' =>       'E-Zigarette | Base & Deck für Selbstwickler günstig online kaufen',
                    'description' => 'Bases & Decks für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Base,Deck,Selbstwickler,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        23 => array(
            'types' => array(
                0 => 'COIL',
                1 => 'HEATING_PLATE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Coils',
            'seo' => [
                'base' => [
                    'title' =>       'Coils und Wicklungen für E-Zigaretten günstig online kaufen',
                    'description' => 'Coils und Wicklungen für E-Zigaretten günstig kaufen ✓ Große Auswahl ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Coil,Wicklung,Spule,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        24 => array(
            'types' => array(
                0 => 'EXTENSION_KIT',
                1 => 'CONVERSION_KIT',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Umbau- & Eweiterungskits',
            'seo' => [
                'base' => [
                    'title' =>       'Steam Crave | Erweitungs- und Umbaukits für den Aromamizer günstig kaufen',
                    'description' => 'Erweitungs- und Umbaukit den Steam Crave Aromamizer günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Steam Crave,Aromamizer,Erweiterung,Umbau,Erweiterungskit,Umbaukit,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        25 => array(
            'types' => array(
                0 => 'EMPTY_BOTTLE',
            ),
            'base_category' => 'ZUBEHÖR > Leerflaschen',
            'seo' => [
                'base' => [
                    'title' =>       'Leerflaschen für E-Liquid günstig online kaufen',
                    'description' => 'Leerflaschen für E-Liquid günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Leerflasche,Flasche,Liquid,E-Liquid,günstig,kaufen',
                ],
            ],
        ),
        26 => array(
            'types' => array(
                0 => 'CLEANING_SUPPLY',
            ),
            'base_category' => 'ZUBEHÖR > Reinigung',
            'seo' => [
                'base' => [
                    'title' =>       'Renigungszubehör für E-Zigaretten günstig kaufen',
                    'description' => 'Reinigungszubehör für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Reinigung,Zubehör,Reinigungszubehör,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        27 => array(
            'types' => array(
                0 => 'ACCESSORY',
            ),
            'base_category' => 'ZUBEHÖR > Accessoires',
            'seo' => [
                'base' => [
                    'title' =>       'Accessoires für E-Zigaretten günstig onliine kaufen',
                    'description' => 'Accessoires für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Accessoire,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        32 => array(
            'types' => array(
                0 => 'COVER',
            ),
            'base_category' => 'ZUBEHÖR > Abdeckungen',
            'seo' => [
                'base' => [
                    'title' =>       'Abdeckungen für E-Zigaretten günstig online kaufen',
                    'description' => 'Abdeckungen für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Abdeckung,Cover,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        28 => array(
            'types' => array(
                0 => 'E_HOOKAH',
                1 => 'VAPORIZER',
            ),
            'base_category' => 'E-ZIGARETTEN > E-Hookah & Vaporizer',
            'seo' => [
                'base' => [
                    'title' =>       'E-Hookah und Vaporizer günstig online kaufen',
                    'description' => 'E-Hookah und Vaporizer günstig online kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'E-Shisha,E-Hookah,Vaporizer,günstig,kaufen',
                ],
            ],
        ),
        29 => array(
            'types' => array(
                0 => 'BATTERY_CAP',
                1 => 'BATTERY_SLEEVE',
            ),
            'base_category' => 'ZUBEHÖR > Batteriekappen & -hülsen',
            'seo' => [
                'base' => [
                    'title' =>       'Batteriekappen für E-Zigaretten günstig online kaufen',
                    'description' => 'Batteriekappen für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Batteriekappe,Kappe,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        30 => array(
            'types' => array(
                0 => 'MAGNET',
                1 => 'MAGNET_ADAPTOR',
            ),
            'base_category' => 'ZUBEHÖR > Magnet & Magnetadapter',
            'seo' => [
                'base' => [
                    'title' =>       'Magnete und -adapter für E-Zigaretten günstig online kaufen',
                    'description' => 'Magnete und -adapter für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Magnet,Magnetadapter,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
        31 => array(
            'types' => array(
                0 => 'STORAGE',
            ),
            'base_category' => 'ZUBEHÖR > Aufbewahrung',
            'seo' => [
                'base' => [
                    'title' =>       'Vitrinen für E-Zigaretten günstig online kaufen',
                    'description' => 'Vitrinen für E-Zigaretten günstig kaufen ✓ Faire Preise ✓ Rascher Versand ► Besuchen Sie vapee.de!',
                    'keywords' => 'Aufbewahrung,Vitrine,E-Zigarette,günstig,kaufen',
                ],
            ],
        ),
    ),
    'category_tree' => array(
        'E-ZIGARETTEN' => array(
            'asMODus' => 2,
            'Aspire' => 15,
            'CoilArt' => 2,
            'Desire Design' => 1,
            'eLeaf' => 18,
            'FreeMax' => 1,
            'GeekVape' => 3,
            'Innokin' => 1,
            'Joyetech' => 14,
            'JustFog' => 6,
            'Lost Vape' => 2,
            'OBS' => 3,
            'Revenant Vape' => 1,
            'SC' => 1,
            'Sigelei' => 3,
            'Smoant' => 1,
            'Smoktech' => 10,
            'Uwell' => 7,
            'VapeOnly' => 3,
            'Vaporesso' => 9,
            'Vzone' => 3,
            'Wismec' => 9,
            'Yihi' => 1,
            'ZQ' => 1,
            'E-Hookah & Vaporizer' => 1,
        ),
        'LIQUIDS' => array(
            'Beeren' => 70,
            'Bonbons & Kaugummi' => 12,
            'Cerealien' => 1,
            'Cremiges' => 7,
            'exotische Früchte' => 20,
            'Frisches & Eiscreme' => 63,
            'Früchte' => 48,
            'Gebäck' => 12,
            'Getränke' => 12,
            'Gewürze' => 31,
            'Melonen' => 13,
            'Milch & Co.' => 5,
            'Nüsse' => 5,
            'Pflanzen' => 4,
            'Süßigkeiten' => 10,
            'Tabak' => 46,
            'Tee & Kaffee' => 5,
            'Trauben' => 2,
            'Zitrusfrüchte' => 12,
            'Cheap Thrills' => 3,
            'Dr. Frost' => 6,
            'Erste Sahne' => 39,
            'Happy Liquid' => 21,
            'InnoCigs' => 42,
            'Miami Drippers' => 3,
            'SC' => 47,
            'Simple Essentials' => 14,
            'SOLT' => 6,
            'Spever' => 7,
            'Vampire Vape' => 55,
            'Easy 3 Caps' => 10,
        ),
        'SHAKE & VAPE' => array(
            'Beeren' => 111,
            'Bonbons & Kaugummi' => 22,
            'Cerealien' => 2,
            'Cremiges' => 22,
            'exotische Früchte' => 58,
            'Frisches & Eiscreme' => 90,
            'Früchte' => 73,
            'Gebäck' => 43,
            'Getränke' => 35,
            'Gewürze' => 45,
            'Melonen' => 23,
            'Milch & Co.' => 29,
            'Nüsse' => 11,
            'Pflanzen' => 13,
            'Süßigkeiten' => 28,
            'Tabak' => 14,
            'Tee & Kaffee' => 10,
            'Trauben' => 16,
            'Zitrusfrüchte' => 54,
            '5 Stars Peine' => 13,
            'Bang Bang Juice' => 4,
            'Brateflavour' => 8,
            'Chicken Shop' => 4,
            'Dexter’s Juice Lab' => 4,
            'Disco Juice' => 3,
            'Dr. Frost' => 16,
            'Dr. Vapes' => 6,
            'Elements' => 4,
            'Erste Sahne' => 12,
            'The Fog Clown' => 12,
            'German Liquids' => 19,
            'Illusions' => 8,
            'InnoCigs' => 30,
            'I VG' => 13,
            'Juice Bomb' => 5,
            'Operation Baked' => 3,
            'Pink Spot' => 27,
            'red\'s Apple Juice' => 7,
            'SC' => 8,
            'Skull Plus' => 7,
            'Smoking Bull' => 14,
            'Team 120' => 2,
            'Treibstoff' => 4,
            'Twelve Monkeys' => 24,
            'TWIST' => 5,
            'Twisted' => 20,
            'Vampire Vape' => 25,
            'Vaporist' => 6,
            'Vapors Line' => 16,
            'Wonutz' => 5,
        ),
        'AROMEN' => array(
            'Beeren' => 104,
            'Bonbons & Kaugummi' => 24,
            'Cerealien' => 3,
            'Cremiges' => 35,
            'exotische Früchte' => 52,
            'Frisches & Eiscreme' => 102,
            'Früchte' => 92,
            'Gebäck' => 49,
            'Getränke' => 48,
            'Gewürze' => 68,
            'Melonen' => 30,
            'Milch & Co.' => 45,
            'Nüsse' => 24,
            'Pflanzen' => 18,
            'Süßigkeiten' => 47,
            'Tabak' => 21,
            'Tee & Kaffee' => 22,
            'Trauben' => 10,
            'Zitrusfrüchte' => 69,
            '5 Stars Peine' => 13,
            '7 Todsünden' => 8,
            'Arschkalt' => 4,
            'Bozz Liquids' => 21,
            'Captain Dolly' => 8,
            'Demons' => 7,
            'Dutty Juice' => 6,
            'Elli\'s Aromen' => 30,
            'Flavorist' => 4,
            'Flavour Trade' => 5,
            'Foozy Juice' => 2,
            'Frankonia' => 15,
            'I VG' => 2,
            'Kaori' => 3,
            'Military' => 7,
            'Mr. Nik\'s' => 6,
            'Mùa' => 4,
            'Mule Fuel' => 5,
            'Roofy\'s' => 3,
            'SC' => 20,
            'Shark Attack' => 9,
            'Smoking Bull' => 29,
            'TNYVPS' => 4,
            'Tobacco Time' => 2,
            'Twisted' => 65,
            'Vampire Vape' => 77,
            'VapeHansa' => 20,
            'Vape Rebelz' => 10,
            'Vapors Line' => 15,
            'WSY' => 4,
            'Yankee Juice Co.' => 6,
        ),
        'BOXEN' => array(
            'asMODus' => 8,
            'Aspire' => 8,
            'CoilArt' => 1,
            'Desire Design' => 2,
            'Digiflavor' => 2,
            'eLeaf' => 14,
            'GeekVape' => 4,
            'iPV' => 1,
            'Joyetech' => 8,
            'JustFog' => 3,
            'Nikola' => 1,
            'OBS' => 1,
            'Revenant Vape' => 1,
            'Smoktech' => 5,
            'Steam Crave' => 1,
            'Uwell' => 7,
            'Vapanion' => 1,
            'VapeOnly' => 1,
            'Vaporesso' => 4,
            'Vapor Storm' => 4,
            'VooPoo' => 5,
            'Vsticking' => 1,
            'Vzone' => 1,
            'Wismec' => 10,
            'Yihi' => 2,
        ),
        'VERDAMPFER' => array(
            'Advken' => 1,
            'Aspire' => 15,
            'CoilArt' => 1,
            'Desire Design' => 1,
            'eLeaf' => 11,
            'FreeMax' => 2,
            'GeekVape' => 3,
            'HellVape' => 1,
            'iPV' => 1,
            'Joyetech' => 14,
            'JustFog' => 3,
            'Nikola' => 1,
            'OBS' => 1,
            'Smoktech' => 3,
            'Uwell' => 6,
            'Vapanion' => 2,
            'VapeOnly' => 1,
            'Vaporesso' => 6,
            'Vzone' => 2,
            'Wismec' => 4,
            'Selbstwickler' => array(
                'Advken' => 2,
                'asMODus' => 6,
                'Augvape' => 2,
                'CoilArt' => 1,
                'Cthulhu' => 5,
                'Digiflavor' => 3,
                'Ehpro' => 1,
                'GeekVape' => 12,
                'HellVape' => 8,
                'OBS' => 3,
                'Smoant' => 1,
                'Steam Crave' => 5,
                'Uwell' => 1,
                'Wismec' => 1,
                'Wotofo' => 1,
            ),
            'AsMODus' => 1,
        ),
        'ZUBEHÖR' => array(
            'Basen & Shots' => 8,
            'Verdampferköpfe' => array(
                'Advken' => 1,
                'asMODus' => 1,
                'Aspire' => 28,
                'CoilArt' => 2,
                'Desire Design' => 1,
                'eLeaf' => 22,
                'FreeMax' => 11,
                'GeekVape' => 6,
                'HellVape' => 1,
                'Innokin' => 1,
                'iPV' => 2,
                'Joyetech' => 15,
                'JustFog' => 2,
                'Nikola' => 1,
                'OBS' => 3,
                'Sigelei' => 4,
                'Smoktech' => 45,
                'Uwell' => 15,
                'Vapanion' => 1,
                'VapeOnly' => 1,
                'Vaporesso' => 14,
                'Wismec' => 9,
                'AsMODus' => 1,
                'Lost Vape' => 1,
            ),
            'Pods & Cartridges' => array(
                'Atopack Magic' => 1,
                'Aurora Play' => 1,
                'AVP' => 1,
                'Breeze 2' => 1,
                'C601' => 1,
                'Cobble AIO' => 1,
                'Elven' => 1,
                'Exceed Edge' => 1,
                'Exceed Grip' => 2,
                'iWu' => 1,
                'Minifit' => 1,
                'Mino' => 1,
                'Motiv 2' => 1,
                'Nautilus AIO' => 1,
                'Nord' => 1,
                'Original Q' => 1,
                'RunAbout' => 1,
                'Scado' => 1,
                'Spryte AIO' => 1,
                'SX Mini Mi Class' => 1,
                'Teros' => 1,
                'Zero' => 1,
                'Caliburn' => 1,
                'Lyra' => 1,
            ),
            'Akkuzellen & -boxen' => 18,
            'Ladegeräte & -kabel' => 14,
            'Glastanks & Schutz' => array(
                'Advken' => 1,
                'asMODus' => 1,
                'Aspire' => 12,
                'eLeaf' => 7,
                'FreeMax' => 3,
                'GeekVape' => 2,
                'HellVape' => 3,
                'iPV' => 1,
                'Joyetech' => 6,
                'JustFog' => 3,
                'Nikola' => 1,
                'OBS' => 2,
                'Sigelei' => 2,
                'Smoktech' => 8,
                'Steam Crave' => 6,
                'Uwell' => 5,
                'Vapanion' => 2,
                'Vaporesso' => 7,
                'Wismec' => 5,
                'Yihi' => 1,
            ),
            'Mundstücke & Schutz' => array(
                'Aspire' => 5,
                'Chubby Gorilla' => 1,
                'Cthulhu' => 1,
                'eLeaf' => 2,
                'GeekVape' => 2,
                'HellVape' => 2,
                'InnoCigs' => 3,
                'Joyetech' => 5,
                'JustFog' => 2,
                'Smoktech' => 2,
                'Steam Crave' => 1,
                'Uwell' => 3,
                'VapeOnly' => 2,
                'Wismec' => 3,
                'SC' => 1,
            ),
            'Dichtungen' => array(
                'Aspire' => 5,
                'eLeaf' => 2,
                'Joyetech' => 2,
                'Smoktech' => 1,
                'Uwell' => 3,
            ),
            'Selbstwickler' => array(
                'Coils' => 36,
                'Decks' => 5,
                'Umbau- & Eweiterungskits' => 3,
                'Watte' => 7,
                'Werkzeug' => 16,
                'Wickeldraht' => 24,
            ),
            'Taschen & Etuis' => 12,
            'Leerflaschen' => 14,
            'Squonker-Flaschen' => 4,
            'Batteriekappen & -hülsen' => 3,
            'Reinigung' => 2,
            'Aufbewahrung' => 2,
            'Accessoires' => 1,
            'Abdeckungen' => 3,
        ),
        '' => 1,
    ),
    'category_positions' => array(
        'E-ZIGARETTEN' => 2,
        'E-ZIGARETTEN > asMODus' => 2,
        'E-ZIGARETTEN > Aspire' => 3,
        'E-ZIGARETTEN > CoilArt' => 4,
        'E-ZIGARETTEN > Desire Design' => 5,
        'E-ZIGARETTEN > eLeaf' => 6,
        'E-ZIGARETTEN > FreeMax' => 7,
        'E-ZIGARETTEN > GeekVape' => 8,
        'E-ZIGARETTEN > Innokin' => 9,
        'E-ZIGARETTEN > Joyetech' => 10,
        'E-ZIGARETTEN > JustFog' => 11,
        'E-ZIGARETTEN > Lost Vape' => 12,
        'E-ZIGARETTEN > OBS' => 13,
        'E-ZIGARETTEN > Revenant Vape' => 14,
        'E-ZIGARETTEN > SC' => 15,
        'E-ZIGARETTEN > Sigelei' => 16,
        'E-ZIGARETTEN > Smoant' => 17,
        'E-ZIGARETTEN > Smoktech' => 18,
        'E-ZIGARETTEN > Uwell' => 19,
        'E-ZIGARETTEN > VapeOnly' => 20,
        'E-ZIGARETTEN > Vaporesso' => 21,
        'E-ZIGARETTEN > Vzone' => 22,
        'E-ZIGARETTEN > Wismec' => 23,
        'E-ZIGARETTEN > Yihi' => 24,
        'E-ZIGARETTEN > ZQ' => 25,
        'E-ZIGARETTEN > E-Hookah & Vaporizer' => 26,
        'LIQUIDS' => 3,
        'LIQUIDS > Beeren' => 2,
        'LIQUIDS > Bonbons & Kaugummi' => 3,
        'LIQUIDS > Cerealien' => 4,
        'LIQUIDS > Cremiges' => 5,
        'LIQUIDS > exotische Früchte' => 6,
        'LIQUIDS > Frisches & Eiscreme' => 7,
        'LIQUIDS > Früchte' => 8,
        'LIQUIDS > Gebäck' => 9,
        'LIQUIDS > Getränke' => 10,
        'LIQUIDS > Gewürze' => 11,
        'LIQUIDS > Melonen' => 12,
        'LIQUIDS > Milch & Co.' => 13,
        'LIQUIDS > Nüsse' => 14,
        'LIQUIDS > Pflanzen' => 15,
        'LIQUIDS > Süßigkeiten' => 16,
        'LIQUIDS > Tabak' => 17,
        'LIQUIDS > Tee & Kaffee' => 18,
        'LIQUIDS > Trauben' => 19,
        'LIQUIDS > Zitrusfrüchte' => 20,
        'LIQUIDS > Cheap Thrills' => 21,
        'LIQUIDS > Dr. Frost' => 22,
        'LIQUIDS > Erste Sahne' => 23,
        'LIQUIDS > Happy Liquid' => 24,
        'LIQUIDS > InnoCigs' => 25,
        'LIQUIDS > Miami Drippers' => 26,
        'LIQUIDS > SC' => 27,
        'LIQUIDS > Simple Essentials' => 28,
        'LIQUIDS > SOLT' => 29,
        'LIQUIDS > Spever' => 30,
        'LIQUIDS > Vampire Vape' => 31,
        'LIQUIDS > Easy 3 Caps' => 32,
        'SHAKE & VAPE' => 4,
        'SHAKE & VAPE > Beeren' => 2,
        'SHAKE & VAPE > Bonbons & Kaugummi' => 3,
        'SHAKE & VAPE > Cerealien' => 4,
        'SHAKE & VAPE > Cremiges' => 5,
        'SHAKE & VAPE > exotische Früchte' => 6,
        'SHAKE & VAPE > Frisches & Eiscreme' => 7,
        'SHAKE & VAPE > Früchte' => 8,
        'SHAKE & VAPE > Gebäck' => 9,
        'SHAKE & VAPE > Getränke' => 10,
        'SHAKE & VAPE > Gewürze' => 11,
        'SHAKE & VAPE > Melonen' => 12,
        'SHAKE & VAPE > Milch & Co.' => 13,
        'SHAKE & VAPE > Nüsse' => 14,
        'SHAKE & VAPE > Pflanzen' => 15,
        'SHAKE & VAPE > Süßigkeiten' => 16,
        'SHAKE & VAPE > Tabak' => 17,
        'SHAKE & VAPE > Tee & Kaffee' => 18,
        'SHAKE & VAPE > Trauben' => 19,
        'SHAKE & VAPE > Zitrusfrüchte' => 20,
        'SHAKE & VAPE > 5 Stars Peine' => 21,
        'SHAKE & VAPE > Bang Bang Juice' => 22,
        'SHAKE & VAPE > Brateflavour' => 23,
        'SHAKE & VAPE > Chicken Shop' => 24,
        'SHAKE & VAPE > Dexter’s Juice Lab' => 25,
        'SHAKE & VAPE > Disco Juice' => 26,
        'SHAKE & VAPE > Dr. Frost' => 27,
        'SHAKE & VAPE > Dr. Vapes' => 28,
        'SHAKE & VAPE > Elements' => 29,
        'SHAKE & VAPE > Erste Sahne' => 30,
        'SHAKE & VAPE > The Fog Clown' => 31,
        'SHAKE & VAPE > German Liquids' => 32,
        'SHAKE & VAPE > Illusions' => 33,
        'SHAKE & VAPE > InnoCigs' => 34,
        'SHAKE & VAPE > I VG' => 35,
        'SHAKE & VAPE > Juice Bomb' => 36,
        'SHAKE & VAPE > Operation Baked' => 37,
        'SHAKE & VAPE > Pink Spot' => 38,
        'SHAKE & VAPE > red\'s Apple Juice' => 39,
        'SHAKE & VAPE > SC' => 40,
        'SHAKE & VAPE > Skull Plus' => 41,
        'SHAKE & VAPE > Smoking Bull' => 42,
        'SHAKE & VAPE > Team 120' => 43,
        'SHAKE & VAPE > Treibstoff' => 44,
        'SHAKE & VAPE > Twelve Monkeys' => 45,
        'SHAKE & VAPE > TWIST' => 46,
        'SHAKE & VAPE > Twisted' => 47,
        'SHAKE & VAPE > Vampire Vape' => 48,
        'SHAKE & VAPE > Vaporist' => 49,
        'SHAKE & VAPE > Vapors Line' => 50,
        'SHAKE & VAPE > Wonutz' => 51,
        'AROMEN' => 5,
        'AROMEN > Beeren' => 2,
        'AROMEN > Bonbons & Kaugummi' => 3,
        'AROMEN > Cerealien' => 4,
        'AROMEN > Cremiges' => 5,
        'AROMEN > exotische Früchte' => 6,
        'AROMEN > Frisches & Eiscreme' => 7,
        'AROMEN > Früchte' => 8,
        'AROMEN > Gebäck' => 9,
        'AROMEN > Getränke' => 10,
        'AROMEN > Gewürze' => 11,
        'AROMEN > Melonen' => 12,
        'AROMEN > Milch & Co.' => 13,
        'AROMEN > Nüsse' => 14,
        'AROMEN > Pflanzen' => 15,
        'AROMEN > Süßigkeiten' => 16,
        'AROMEN > Tabak' => 17,
        'AROMEN > Tee & Kaffee' => 18,
        'AROMEN > Trauben' => 19,
        'AROMEN > Zitrusfrüchte' => 20,
        'AROMEN > 5 Stars Peine' => 21,
        'AROMEN > 7 Todsünden' => 22,
        'AROMEN > Arschkalt' => 23,
        'AROMEN > Bozz Liquids' => 24,
        'AROMEN > Captain Dolly' => 25,
        'AROMEN > Demons' => 26,
        'AROMEN > Dutty Juice' => 27,
        'AROMEN > Elli\'s Aromen' => 28,
        'AROMEN > Flavorist' => 29,
        'AROMEN > Flavour Trade' => 30,
        'AROMEN > Foozy Juice' => 31,
        'AROMEN > Frankonia' => 32,
        'AROMEN > I VG' => 33,
        'AROMEN > Kaori' => 34,
        'AROMEN > Military' => 35,
        'AROMEN > Mr. Nik\'s' => 36,
        'AROMEN > Mùa' => 37,
        'AROMEN > Mule Fuel' => 38,
        'AROMEN > Roofy\'s' => 39,
        'AROMEN > SC' => 40,
        'AROMEN > Shark Attack' => 41,
        'AROMEN > Smoking Bull' => 42,
        'AROMEN > TNYVPS' => 43,
        'AROMEN > Tobacco Time' => 44,
        'AROMEN > Twisted' => 45,
        'AROMEN > Vampire Vape' => 46,
        'AROMEN > VapeHansa' => 47,
        'AROMEN > Vape Rebelz' => 48,
        'AROMEN > Vapors Line' => 49,
        'AROMEN > WSY' => 50,
        'AROMEN > Yankee Juice Co.' => 51,
        'BOXEN' => 6,
        'BOXEN > asMODus' => 2,
        'BOXEN > Aspire' => 3,
        'BOXEN > CoilArt' => 4,
        'BOXEN > Desire Design' => 5,
        'BOXEN > Digiflavor' => 6,
        'BOXEN > eLeaf' => 7,
        'BOXEN > GeekVape' => 8,
        'BOXEN > iPV' => 9,
        'BOXEN > Joyetech' => 10,
        'BOXEN > JustFog' => 11,
        'BOXEN > Nikola' => 12,
        'BOXEN > OBS' => 13,
        'BOXEN > Revenant Vape' => 14,
        'BOXEN > Smoktech' => 15,
        'BOXEN > Steam Crave' => 16,
        'BOXEN > Uwell' => 17,
        'BOXEN > Vapanion' => 18,
        'BOXEN > VapeOnly' => 19,
        'BOXEN > Vaporesso' => 20,
        'BOXEN > Vapor Storm' => 21,
        'BOXEN > VooPoo' => 22,
        'BOXEN > Vsticking' => 23,
        'BOXEN > Vzone' => 24,
        'BOXEN > Wismec' => 25,
        'BOXEN > Yihi' => 26,
        'VERDAMPFER' => 7,
        'VERDAMPFER > Advken' => 2,
        'VERDAMPFER > Aspire' => 3,
        'VERDAMPFER > CoilArt' => 4,
        'VERDAMPFER > Desire Design' => 5,
        'VERDAMPFER > eLeaf' => 6,
        'VERDAMPFER > FreeMax' => 7,
        'VERDAMPFER > GeekVape' => 8,
        'VERDAMPFER > HellVape' => 9,
        'VERDAMPFER > iPV' => 10,
        'VERDAMPFER > Joyetech' => 11,
        'VERDAMPFER > JustFog' => 12,
        'VERDAMPFER > Nikola' => 13,
        'VERDAMPFER > OBS' => 14,
        'VERDAMPFER > Smoktech' => 15,
        'VERDAMPFER > Uwell' => 16,
        'VERDAMPFER > Vapanion' => 17,
        'VERDAMPFER > VapeOnly' => 18,
        'VERDAMPFER > Vaporesso' => 19,
        'VERDAMPFER > Vzone' => 20,
        'VERDAMPFER > Wismec' => 21,
        'VERDAMPFER > Selbstwickler' => 22,
        'VERDAMPFER > Selbstwickler > Advken' => 2,
        'VERDAMPFER > Selbstwickler > asMODus' => 3,
        'VERDAMPFER > Selbstwickler > Augvape' => 4,
        'VERDAMPFER > Selbstwickler > CoilArt' => 5,
        'VERDAMPFER > Selbstwickler > Cthulhu' => 6,
        'VERDAMPFER > Selbstwickler > Digiflavor' => 7,
        'VERDAMPFER > Selbstwickler > Ehpro' => 8,
        'VERDAMPFER > Selbstwickler > GeekVape' => 9,
        'VERDAMPFER > Selbstwickler > HellVape' => 10,
        'VERDAMPFER > Selbstwickler > OBS' => 11,
        'VERDAMPFER > Selbstwickler > Smoant' => 12,
        'VERDAMPFER > Selbstwickler > Steam Crave' => 13,
        'VERDAMPFER > Selbstwickler > Uwell' => 14,
        'VERDAMPFER > Selbstwickler > Wismec' => 15,
        'VERDAMPFER > Selbstwickler > Wotofo' => 16,
        'VERDAMPFER > AsMODus' => 23,
        'ZUBEHÖR' => 8,
        'ZUBEHÖR > Basen & Shots' => 2,
        'ZUBEHÖR > Verdampferköpfe' => 3,
        'ZUBEHÖR > Verdampferköpfe > Advken' => 2,
        'ZUBEHÖR > Verdampferköpfe > asMODus' => 3,
        'ZUBEHÖR > Verdampferköpfe > Aspire' => 4,
        'ZUBEHÖR > Verdampferköpfe > CoilArt' => 5,
        'ZUBEHÖR > Verdampferköpfe > Desire Design' => 6,
        'ZUBEHÖR > Verdampferköpfe > eLeaf' => 7,
        'ZUBEHÖR > Verdampferköpfe > FreeMax' => 8,
        'ZUBEHÖR > Verdampferköpfe > GeekVape' => 9,
        'ZUBEHÖR > Verdampferköpfe > HellVape' => 10,
        'ZUBEHÖR > Verdampferköpfe > Innokin' => 11,
        'ZUBEHÖR > Verdampferköpfe > iPV' => 12,
        'ZUBEHÖR > Verdampferköpfe > Joyetech' => 13,
        'ZUBEHÖR > Verdampferköpfe > JustFog' => 14,
        'ZUBEHÖR > Verdampferköpfe > Nikola' => 15,
        'ZUBEHÖR > Verdampferköpfe > OBS' => 16,
        'ZUBEHÖR > Verdampferköpfe > Sigelei' => 17,
        'ZUBEHÖR > Verdampferköpfe > Smoktech' => 18,
        'ZUBEHÖR > Verdampferköpfe > Uwell' => 19,
        'ZUBEHÖR > Verdampferköpfe > Vapanion' => 20,
        'ZUBEHÖR > Verdampferköpfe > VapeOnly' => 21,
        'ZUBEHÖR > Verdampferköpfe > Vaporesso' => 22,
        'ZUBEHÖR > Verdampferköpfe > Wismec' => 23,
        'ZUBEHÖR > Verdampferköpfe > AsMODus' => 24,
        'ZUBEHÖR > Verdampferköpfe > Lost Vape' => 25,
        'ZUBEHÖR > Pods & Cartridges' => 4,
        'ZUBEHÖR > Pods & Cartridges > Atopack Magic' => 2,
        'ZUBEHÖR > Pods & Cartridges > Aurora Play' => 3,
        'ZUBEHÖR > Pods & Cartridges > AVP' => 4,
        'ZUBEHÖR > Pods & Cartridges > Breeze 2' => 5,
        'ZUBEHÖR > Pods & Cartridges > C601' => 6,
        'ZUBEHÖR > Pods & Cartridges > Cobble AIO' => 7,
        'ZUBEHÖR > Pods & Cartridges > Elven' => 8,
        'ZUBEHÖR > Pods & Cartridges > Exceed Edge' => 9,
        'ZUBEHÖR > Pods & Cartridges > Exceed Grip' => 10,
        'ZUBEHÖR > Pods & Cartridges > iWu' => 11,
        'ZUBEHÖR > Pods & Cartridges > Minifit' => 12,
        'ZUBEHÖR > Pods & Cartridges > Mino' => 13,
        'ZUBEHÖR > Pods & Cartridges > Motiv 2' => 14,
        'ZUBEHÖR > Pods & Cartridges > Nautilus AIO' => 15,
        'ZUBEHÖR > Pods & Cartridges > Nord' => 16,
        'ZUBEHÖR > Pods & Cartridges > Original Q' => 17,
        'ZUBEHÖR > Pods & Cartridges > RunAbout' => 18,
        'ZUBEHÖR > Pods & Cartridges > Scado' => 19,
        'ZUBEHÖR > Pods & Cartridges > Spryte AIO' => 20,
        'ZUBEHÖR > Pods & Cartridges > SX Mini Mi Class' => 21,
        'ZUBEHÖR > Pods & Cartridges > Teros' => 22,
        'ZUBEHÖR > Pods & Cartridges > Zero' => 23,
        'ZUBEHÖR > Pods & Cartridges > Caliburn' => 24,
        'ZUBEHÖR > Pods & Cartridges > Lyra' => 25,
        'ZUBEHÖR > Akkuzellen & -boxen' => 5,
        'ZUBEHÖR > Ladegeräte & -kabel' => 6,
        'ZUBEHÖR > Glastanks & Schutz' => 7,
        'ZUBEHÖR > Glastanks & Schutz > Advken' => 2,
        'ZUBEHÖR > Glastanks & Schutz > asMODus' => 3,
        'ZUBEHÖR > Glastanks & Schutz > Aspire' => 4,
        'ZUBEHÖR > Glastanks & Schutz > eLeaf' => 5,
        'ZUBEHÖR > Glastanks & Schutz > FreeMax' => 6,
        'ZUBEHÖR > Glastanks & Schutz > GeekVape' => 7,
        'ZUBEHÖR > Glastanks & Schutz > HellVape' => 8,
        'ZUBEHÖR > Glastanks & Schutz > iPV' => 9,
        'ZUBEHÖR > Glastanks & Schutz > Joyetech' => 10,
        'ZUBEHÖR > Glastanks & Schutz > JustFog' => 11,
        'ZUBEHÖR > Glastanks & Schutz > Nikola' => 12,
        'ZUBEHÖR > Glastanks & Schutz > OBS' => 13,
        'ZUBEHÖR > Glastanks & Schutz > Sigelei' => 14,
        'ZUBEHÖR > Glastanks & Schutz > Smoktech' => 15,
        'ZUBEHÖR > Glastanks & Schutz > Steam Crave' => 16,
        'ZUBEHÖR > Glastanks & Schutz > Uwell' => 17,
        'ZUBEHÖR > Glastanks & Schutz > Vapanion' => 18,
        'ZUBEHÖR > Glastanks & Schutz > Vaporesso' => 19,
        'ZUBEHÖR > Glastanks & Schutz > Wismec' => 20,
        'ZUBEHÖR > Glastanks & Schutz > Yihi' => 21,
        'ZUBEHÖR > Mundstücke & Schutz' => 8,
        'ZUBEHÖR > Mundstücke & Schutz > Aspire' => 2,
        'ZUBEHÖR > Mundstücke & Schutz > Chubby Gorilla' => 3,
        'ZUBEHÖR > Mundstücke & Schutz > Cthulhu' => 4,
        'ZUBEHÖR > Mundstücke & Schutz > eLeaf' => 5,
        'ZUBEHÖR > Mundstücke & Schutz > GeekVape' => 6,
        'ZUBEHÖR > Mundstücke & Schutz > HellVape' => 7,
        'ZUBEHÖR > Mundstücke & Schutz > InnoCigs' => 8,
        'ZUBEHÖR > Mundstücke & Schutz > Joyetech' => 9,
        'ZUBEHÖR > Mundstücke & Schutz > JustFog' => 10,
        'ZUBEHÖR > Mundstücke & Schutz > Smoktech' => 11,
        'ZUBEHÖR > Mundstücke & Schutz > Steam Crave' => 12,
        'ZUBEHÖR > Mundstücke & Schutz > Uwell' => 13,
        'ZUBEHÖR > Mundstücke & Schutz > VapeOnly' => 14,
        'ZUBEHÖR > Mundstücke & Schutz > Wismec' => 15,
        'ZUBEHÖR > Mundstücke & Schutz > SC' => 16,
        'ZUBEHÖR > Dichtungen' => 9,
        'ZUBEHÖR > Dichtungen > Aspire' => 2,
        'ZUBEHÖR > Dichtungen > eLeaf' => 3,
        'ZUBEHÖR > Dichtungen > Joyetech' => 4,
        'ZUBEHÖR > Dichtungen > Smoktech' => 5,
        'ZUBEHÖR > Dichtungen > Uwell' => 6,
        'ZUBEHÖR > Selbstwickler' => 10,
        'ZUBEHÖR > Selbstwickler > Coils' => 2,
        'ZUBEHÖR > Selbstwickler > Decks' => 3,
        'ZUBEHÖR > Selbstwickler > Umbau- & Eweiterungskits' => 4,
        'ZUBEHÖR > Selbstwickler > Watte' => 5,
        'ZUBEHÖR > Selbstwickler > Werkzeug' => 6,
        'ZUBEHÖR > Selbstwickler > Wickeldraht' => 7,
        'ZUBEHÖR > Taschen & Etuis' => 11,
        'ZUBEHÖR > Leerflaschen' => 12,
        'ZUBEHÖR > Squonker-Flaschen' => 13,
        'ZUBEHÖR > Batteriekappen & -hülsen' => 14,
        'ZUBEHÖR > Reinigung' => 15,
        'ZUBEHÖR > Aufbewahrung' => 16,
        'ZUBEHÖR > Accessoires' => 17,
        'ZUBEHÖR > Abdeckungen' => 18,
        '' => 9,
    ),


);
