<?php
return array(
    'type_category_map' => array(
        0 => array(
            'types' => array(
                0 => 'E_CIGARETTE',
                1 => 'E_PIPE',
            ),
            'base_category' => 'E-ZIGARETTEN',
            'append_subcategory' => 'supplier',
        ),
        1 => array(
            'types' => array(
                0 => 'BOX_MOD',
                1 => 'BOX_MOD_CELL',
                2 => 'SQUONKER_BOX',
            ),
            'base_category' => 'BOXEN',
            'append_subcategory' => 'supplier',
        ),
        2 => array(
            'types' => array(
                0 => 'CLEAROMIZER',
            ),
            'base_category' => 'VERDAMPFER',
            'append_subcategory' => 'supplier',
        ),
        3 => array(
            'types' => array(
                0 => 'CLEAROMIZER_RTA',
                1 => 'CLEAROMIZER_RDA',
                2 => 'CLEAROMIZER_RDTA',
                3 => 'CLEAROMIZER_RDSA',
            ),
            'base_category' => 'VERDAMPFER > Selbstwickler',
            'append_subcategory' => 'supplier',
        ),
        4 => array(
            'types' => array(
                0 => 'LIQUID',
            ),
            'base_category' => 'LIQUIDS',
            'append_subcategory' => 'brand',
        ),
        5 => array(
            'types' => array(
                0 => 'EASY3_CAP',
            ),
            'base_category' => 'LIQUIDS > Easy 3 Caps',
        ),
        6 => array(
            'types' => array(
                0 => 'AROMA',
            ),
            'base_category' => 'AROMEN',
            'append_subcategory' => 'brand',
        ),
        7 => array(
            'types' => array(
                0 => 'SHAKE_VAPE',
            ),
            'base_category' => 'SHAKE & VAPE',
            'append_subcategory' => 'brand',
        ),
        8 => array(
            'types' => array(
                0 => 'HEAD',
            ),
            'base_category' => 'ZUBEHÖR > Verdampferköpfe',
            'append_subcategory' => 'supplier',
        ),
        9 => array(
            'types' => array(
                0 => 'TANK',
                1 => 'TANK_PROTECTION',
            ),
            'base_category' => 'ZUBEHÖR > Glastanks & Schutz',
            'append_subcategory' => 'supplier',
        ),
        10 => array(
            'types' => array(
                0 => 'DRIP_TIP',
                1 => 'DRIP_TIP_CAP',
            ),
            'base_category' => 'ZUBEHÖR > Mundstücke & Schutz',
            'append_subcategory' => 'supplier',
        ),
        11 => array(
            'types' => array(
                0 => 'SEAL',
            ),
            'base_category' => 'ZUBEHÖR > Dichtungen',
            'append_subcategory' => 'supplier',
        ),
        12 => array(
            'types' => array(
                0 => 'POD',
                1 => 'CARTRIDGE',
            ),
            'base_category' => 'ZUBEHÖR > Pods & Cartridges',
            'append_subcategory' => 'common_name',
        ),
        13 => array(
            'types' => array(
                0 => 'CELL',
                1 => 'CELL_BOX',
            ),
            'base_category' => 'ZUBEHÖR > Akkuzellen & -boxen',
        ),
        14 => array(
            'types' => array(
                0 => 'BASE',
                1 => 'SHOT',
            ),
            'base_category' => 'ZUBEHÖR > Basen & Shots',
        ),
        15 => array(
            'types' => array(
                0 => 'CHARGER',
                1 => 'CABLE',
            ),
            'base_category' => 'ZUBEHÖR > Ladegeräte & -kabel',
        ),
        16 => array(
            'types' => array(
                0 => 'SQUONKER_BOTTLE',
            ),
            'base_category' => 'ZUBEHÖR > Squonker-Flaschen',
        ),
        17 => array(
            'types' => array(
                0 => 'BAG',
            ),
            'base_category' => 'ZUBEHÖR > Taschen & Etuis',
        ),
        18 => array(
            'types' => array(
                0 => 'TOOL',
                1 => 'TOOL_HEATING_PLATE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Werkzeug',
        ),
        19 => array(
            'types' => array(
                0 => 'TOOL',
                1 => 'TOOL_HEATING_PLATE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Werkzeug',
        ),
        20 => array(
            'types' => array(
                0 => 'WADDING',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Watte',
        ),
        21 => array(
            'types' => array(
                0 => 'WIRE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Wickeldraht',
        ),
        22 => array(
            'types' => array(
                0 => 'DECK',
                1 => 'RDA_BASE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Decks',
        ),
        23 => array(
            'types' => array(
                0 => 'COIL',
                1 => 'HEATING_PLATE',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Coils',
        ),
        24 => array(
            'types' => array(
                0 => 'EXTENSION_KIT',
                1 => 'CONVERSION_KIT',
            ),
            'base_category' => 'ZUBEHÖR > Selbstwickler > Umbau- & Eweiterungskits',
        ),
        25 => array(
            'types' => array(
                0 => 'EMPTY_BOTTLE',
            ),
            'base_category' => 'ZUBEHÖR > Leerflaschen',
        ),
        26 => array(
            'types' => array(
                0 => 'CLEANING_SUPPLY',
            ),
            'base_category' => 'ZUBEHÖR > Reinigung',
        ),
        27 => array(
            'types' => array(
                0 => 'ACCESSORY',
            ),
            'base_category' => 'ZUBEHÖR > Accessoires',
        ),
        28 => array(
            'types' => array(
                0 => 'E_HOOKAH',
                1 => 'VAPORIZER',
            ),
            'base_category' => 'E-ZIGARETTEN > E-Hookah & Vaporizer',
        ),
        29 => array(
            'types' => array(
                0 => 'BATTERY_CAP',
                1 => 'BATTERY_SLEEVE',
            ),
            'base_category' => 'ZUBEHÖR > Batteriekappen & -hülsen',
        ),
        30 => array(
            'types' => array(
                0 => 'MAGNET',
                1 => 'MAGNET_ADAPTOR',
            ),
            'base_category' => 'ZUBEHÖR > Magnet & Magnetadapter',
        ),
        31 => array(
            'types' => array(
                0 => 'STORAGE',
            ),
            'base_category' => 'ZUBEHÖR > Vitrinen',
        ),
    ),
    'category_tree' => array(
        'E-ZIGARETTEN' => array(
            'asMODus' => 2,
            'Aspire' => 15,
            'eLeaf' => 20,
            'GeekVape' => 3,
            'InnoCigs' => 1,
            'Joyetech' => 15,
            'JustFog' => 5,
            'OBS' => 1,
            'Revenant Vape' => 1,
            'Sigelei' => 2,
            'Smoktech' => 8,
            'Uwell' => 6,
            'VapeOnly' => 3,
            'Vaporesso' => 12,
            'Vzone' => 1,
            'Wismec' => 9,
            'Yihi' => 1,
            'ZQ' => 1,
            'E-Hookah & Vaporizer' => 2,
        ),
        'LIQUIDS' => array(
            'Beeren' => 63,
            'Bonbons & Kaugummi' => 9,
            'Cerealien' => 2,
            'Cremiges' => 5,
            'exotische Früchte' => 14,
            'Frisches' => 44,
            'Früchte' => 40,
            'Gebäck' => 9,
            'Getränke' => 9,
            'Gewürze' => 23,
            'Melonen' => 9,
            'Milch & Co.' => 5,
            'Nüsse' => 4,
            'Pflanzen' => 4,
            'Süßigkeiten' => 6,
            'Tabak' => 35,
            'Tee & Kaffee' => 4,
            'Trauben' => 1,
            'Zitrusfrüchte' => 8,
            'Cheap Thrills' => 3,
            'Erste Sahne' => 38,
            'Happy Liquid' => 21,
            'InnoCigs' => 42,
            'Miami Drippers' => 3,
            'SC' => 41,
            'Simple Essentials' => 14,
            'SOLT' => 6,
            'Spever' => 7,
            'Vampire Vape' => 45,
            'Easy 3 Caps' => array(
                'Tabak' => 3,
                'Gewürze' => 2,
                'Frisches' => 1,
                'Früchte' => 3,
                'Beeren' => 2,
                'Milch & Co.' => 1,
            ),
        ),
        'SHAKE & VAPE' => array(
            'Beeren' => 108,
            'Bonbons & Kaugummi' => 26,
            'Cerealien' => 5,
            'Cremiges' => 18,
            'exotische Früchte' => 49,
            'Frisches' => 84,
            'Früchte' => 70,
            'Gebäck' => 45,
            'Getränke' => 41,
            'Gewürze' => 43,
            'Melonen' => 27,
            'Milch & Co.' => 32,
            'Nüsse' => 9,
            'Pflanzen' => 13,
            'Süßigkeiten' => 24,
            'Tabak' => 14,
            'Tee & Kaffee' => 6,
            'Trauben' => 14,
            'Zitrusfrüchte' => 50,
            '5 Stars Peine' => 13,
            'Bang Bang Juice' => 4,
            'Chicken Shop' => 4,
            'Dexter’s Juice Lab' => 4,
            'Disco Juice' => 3,
            'Dr. Frost' => 15,
            'Erste Sahne' => 11,
            'The Fog Clown' => 9,
            'German Liquids' => 19,
            'Hustler Juice' => 1,
            'Illusions' => 5,
            'InnoCigs' => 30,
            'I VG' => 38,
            'Operation Baked' => 4,
            'Pink Spot' => 27,
            'Pretty Big Bottle' => 1,
            'red\'s Apple Juice' => 10,
            'SC' => 8,
            'Skull Plus' => 7,
            'Smoking Bull' => 14,
            'Team 120' => 6,
            'Treibstoff' => 4,
            'Twelve Monkeys' => 25,
            'TWIST' => 11,
            'Twisted' => 20,
            'Vampire Vape' => 25,
            'Vaporist' => 3,
            'Vapors Line' => 16,
            'Wonutz' => 5,
            'Yogi' => 3,
        ),
        'AROMEN' => array(
            'Beeren' => 87,
            'Bonbons & Kaugummi' => 19,
            'Cerealien' => 2,
            'Cremiges' => 26,
            'exotische Früchte' => 37,
            'Frisches' => 78,
            'Früchte' => 69,
            'Gebäck' => 38,
            'Getränke' => 24,
            'Gewürze' => 55,
            'Melonen' => 19,
            'Milch & Co.' => 34,
            'Nüsse' => 19,
            'Pflanzen' => 14,
            'Süßigkeiten' => 31,
            'Tabak' => 16,
            'Tee & Kaffee' => 14,
            'Trauben' => 6,
            'Zitrusfrüchte' => 51,
            '5 Stars Peine' => 10,
            '7 Todsünden' => 8,
            'Bozz Liquids' => 21,
            'Flavorist' => 2,
            'Foozy Juice' => 2,
            'I VG' => 12,
            'Military' => 2,
            'Mr. Nik\'s' => 6,
            'Mule Fuel' => 19,
            'SC' => 20,
            'Smoking Bull' => 29,
            'Tobacco Time' => 2,
            'Twenty Eight Monkeys' => 1,
            'Twisted' => 67,
            'Vampire Vape' => 77,
            'VapeHansa' => 33,
            'Vape Rebelz' => 10,
            'Vapors Line' => 15,
        ),
        'BOXEN' => array(
            'asMODus' => 9,
            'Aspire' => 7,
            'Digiflavor' => 1,
            'eLeaf' => 16,
            'GeekVape' => 3,
            'iPV' => 1,
            'Joyetech' => 10,
            'JustFog' => 2,
            'OBS' => 1,
            'Revenant Vape' => 1,
            'Smoktech' => 6,
            'Steam Crave' => 1,
            'Uwell' => 5,
            'Vapanion' => 1,
            'VapeOnly' => 1,
            'Vaporesso' => 5,
            'Vapor Storm' => 2,
            'VooPoo' => 2,
            'Vsticking' => 1,
            'Wismec' => 11,
            'Yihi' => 1,
        ),
        'VERDAMPFER' => array(
            'Advken' => 1,
            'Aspire' => 15,
            'eLeaf' => 13,
            'GeekVape' => 2,
            'HellVape' => 1,
            'iPV' => 1,
            'Joyetech' => 14,
            'JustFog' => 2,
            'Smoktech' => 7,
            'Uwell' => 5,
            'Vapanion' => 2,
            'VapeOnly' => 1,
            'Vaporesso' => 7,
            'Wismec' => 6,
            'Selbstwickler' => array(
                'Advken' => 1,
                'asMODus' => 6,
                'CoilArt' => 1,
                'Digiflavor' => 3,
                'Ehpro' => 1,
                'GeekVape' => 9,
                'HellVape' => 7,
                'OBS' => 2,
                'Steam Crave' => 5,
                'Uwell' => 1,
                'Wismec' => 1,
                'Wotofo' => 1,
                'Cthulhu' => 4,
                'Augvape' => 2,
            ),
        ),
        'ZUBEHÖR' => array(
            'Basen & Shots' => 7,
            'Verdampferköpfe' => array(
                'Advken' => 1,
                'asMODus' => 1,
                'Aspire' => 28,
                'eLeaf' => 24,
                'GeekVape' => 3,
                'iPV' => 2,
                'Joyetech' => 14,
                'JustFog' => 2,
                'OBS' => 1,
                'Sigelei' => 4,
                'Smoktech' => 46,
                'Uwell' => 8,
                'Vapanion' => 1,
                'VapeOnly' => 1,
                'Vaporesso' => 15,
                'Wismec' => 9,
            ),
            'Pods & Cartridges' => array(
                'Atopack Magic' => 1,
                'Aurora Play' => 1,
                'Breeze 2' => 1,
                'C601' => 1,
                'Caliburn Pod' => 1,
                'Cobble AIO' => 1,
                'Elven' => 1,
                'Exceed Edge' => 1,
                'iWu' => 1,
                'Minifit' => 1,
                'Motiv 2' => 1,
                'Nautilus AIO' => 1,
                'Nord' => 1,
                'RunAbout' => 1,
                'Scado' => 1,
                'Spryte AIO' => 1,
                'SX Mini Mi Class' => 1,
                'Teros' => 1,
                'Zero' => 1,
            ),
            'Akkuzellen & -boxen' => 16,
            'Ladegeräte & -kabel' => 13,
            'Glastanks & Schutz' => array(
                'asMODus' => 1,
                'Aspire' => 12,
                'eLeaf' => 8,
                'GeekVape' => 2,
                'HellVape' => 3,
                'iPV' => 1,
                'Joyetech' => 6,
                'JustFog' => 2,
                'Smoktech' => 7,
                'Sigelei' => 2,
                'Steam Crave' => 7,
                'Uwell' => 7,
                'Vapanion' => 2,
                'Vaporesso' => 5,
                'Wismec' => 6,
            ),
            'Mundstücke & Schutz' => array(
                'Aspire' => 5,
                'Chubby Gorilla' => 1,
                'eLeaf' => 4,
                'GeekVape' => 2,
                'HellVape' => 2,
                'InnoCigs' => 5,
                'Joyetech' => 5,
                'JustFog' => 2,
                'Smoktech' => 4,
                'Steam Crave' => 1,
                'Uwell' => 3,
                'VapeOnly' => 2,
                'Wismec' => 4,
            ),
            'Dichtungen' => array(
                'Aspire' => 5,
                'eLeaf' => 2,
                'Joyetech' => 2,
                'Smoktech' => 1,
                'Uwell' => 3,
                'Vapanion' => 1,
                'Vaporesso' => 1,
            ),
            'Selbstwickler' => array(
                'Coils' => 32,
                'Decks' => 5,
                'Umbau- & Eweiterungskits' => 3,
                'Watte' => 7,
                'Werkzeug' => 15,
                'Wickeldraht' => 23,
            ),
            'Taschen & Etuis' => 11,
            'Leerflaschen' => 13,
            'Squonker-Flaschen' => 3,
            'Batteriekappen & -hülsen' => 3,
            'Magnet & Magnetadapter' => 2,
            'Reinigung' => 2,
            'Accessoires' => 4,
            'Vitrinen' => 1,
        ),
    ),
    'category_positions' => array(
        'E-ZIGARETTEN' => 1,
        'E-ZIGARETTEN > asMODus' => 1,
        'E-ZIGARETTEN > Aspire' => 2,
        'E-ZIGARETTEN > eLeaf' => 3,
        'E-ZIGARETTEN > GeekVape' => 4,
        'E-ZIGARETTEN > InnoCigs' => 5,
        'E-ZIGARETTEN > Joyetech' => 6,
        'E-ZIGARETTEN > JustFog' => 7,
        'E-ZIGARETTEN > OBS' => 8,
        'E-ZIGARETTEN > Revenant Vape' => 9,
        'E-ZIGARETTEN > Sigelei' => 10,
        'E-ZIGARETTEN > Smoktech' => 11,
        'E-ZIGARETTEN > Uwell' => 12,
        'E-ZIGARETTEN > VapeOnly' => 13,
        'E-ZIGARETTEN > Vaporesso' => 14,
        'E-ZIGARETTEN > Vzone' => 15,
        'E-ZIGARETTEN > Wismec' => 16,
        'E-ZIGARETTEN > Yihi' => 17,
        'E-ZIGARETTEN > ZQ' => 18,
        'E-ZIGARETTEN > E-Hookah & Vaporizer' => 19,
        'LIQUIDS' => 2,
        'LIQUIDS > Beeren' => 1,
        'LIQUIDS > Bonbons & Kaugummi' => 2,
        'LIQUIDS > Cerealien' => 3,
        'LIQUIDS > Cremiges' => 4,
        'LIQUIDS > exotische Früchte' => 5,
        'LIQUIDS > Frisches' => 6,
        'LIQUIDS > Früchte' => 7,
        'LIQUIDS > Gebäck' => 8,
        'LIQUIDS > Getränke' => 9,
        'LIQUIDS > Gewürze' => 10,
        'LIQUIDS > Melonen' => 11,
        'LIQUIDS > Milch & Co.' => 12,
        'LIQUIDS > Nüsse' => 13,
        'LIQUIDS > Pflanzen' => 14,
        'LIQUIDS > Süßigkeiten' => 15,
        'LIQUIDS > Tabak' => 16,
        'LIQUIDS > Tee & Kaffee' => 17,
        'LIQUIDS > Trauben' => 18,
        'LIQUIDS > Zitrusfrüchte' => 19,
        'LIQUIDS > Cheap Thrills' => 20,
        'LIQUIDS > Erste Sahne' => 21,
        'LIQUIDS > Happy Liquid' => 22,
        'LIQUIDS > InnoCigs' => 23,
        'LIQUIDS > Miami Drippers' => 24,
        'LIQUIDS > SC' => 25,
        'LIQUIDS > Simple Essentials' => 26,
        'LIQUIDS > SOLT' => 27,
        'LIQUIDS > Spever' => 28,
        'LIQUIDS > Vampire Vape' => 29,
        'LIQUIDS > Easy 3 Caps' => 30,
        'LIQUIDS > Easy 3 Caps > Tabak' => 1,
        'LIQUIDS > Easy 3 Caps > Gewürze' => 2,
        'LIQUIDS > Easy 3 Caps > Frisches' => 3,
        'LIQUIDS > Easy 3 Caps > Früchte' => 4,
        'LIQUIDS > Easy 3 Caps > Beeren' => 5,
        'LIQUIDS > Easy 3 Caps > Milch & Co.' => 6,
        'SHAKE & VAPE' => 3,
        'SHAKE & VAPE > Beeren' => 1,
        'SHAKE & VAPE > Bonbons & Kaugummi' => 2,
        'SHAKE & VAPE > Cerealien' => 3,
        'SHAKE & VAPE > Cremiges' => 4,
        'SHAKE & VAPE > exotische Früchte' => 5,
        'SHAKE & VAPE > Frisches' => 6,
        'SHAKE & VAPE > Früchte' => 7,
        'SHAKE & VAPE > Gebäck' => 8,
        'SHAKE & VAPE > Getränke' => 9,
        'SHAKE & VAPE > Gewürze' => 10,
        'SHAKE & VAPE > Melonen' => 11,
        'SHAKE & VAPE > Milch & Co.' => 12,
        'SHAKE & VAPE > Nüsse' => 13,
        'SHAKE & VAPE > Pflanzen' => 14,
        'SHAKE & VAPE > Süßigkeiten' => 15,
        'SHAKE & VAPE > Tabak' => 16,
        'SHAKE & VAPE > Tee & Kaffee' => 17,
        'SHAKE & VAPE > Trauben' => 18,
        'SHAKE & VAPE > Zitrusfrüchte' => 19,
        'SHAKE & VAPE > 5 Stars Peine' => 20,
        'SHAKE & VAPE > Bang Bang Juice' => 21,
        'SHAKE & VAPE > Chicken Shop' => 22,
        'SHAKE & VAPE > Dexter’s Juice Lab' => 23,
        'SHAKE & VAPE > Disco Juice' => 24,
        'SHAKE & VAPE > Dr. Frost' => 25,
        'SHAKE & VAPE > Erste Sahne' => 26,
        'SHAKE & VAPE > The Fog Clown' => 27,
        'SHAKE & VAPE > German Liquids' => 28,
        'SHAKE & VAPE > Hustler Juice' => 29,
        'SHAKE & VAPE > Illusions' => 30,
        'SHAKE & VAPE > InnoCigs' => 31,
        'SHAKE & VAPE > I VG' => 32,
        'SHAKE & VAPE > Operation Baked' => 33,
        'SHAKE & VAPE > Pink Spot' => 34,
        'SHAKE & VAPE > Pretty Big Bottle' => 35,
        'SHAKE & VAPE > red\'s Apple Juice' => 36,
        'SHAKE & VAPE > SC' => 37,
        'SHAKE & VAPE > Skull Plus' => 38,
        'SHAKE & VAPE > Smoking Bull' => 39,
        'SHAKE & VAPE > Team 120' => 40,
        'SHAKE & VAPE > Treibstoff' => 41,
        'SHAKE & VAPE > Twelve Monkeys' => 42,
        'SHAKE & VAPE > TWIST' => 43,
        'SHAKE & VAPE > Twisted' => 44,
        'SHAKE & VAPE > Vampire Vape' => 45,
        'SHAKE & VAPE > Vaporist' => 46,
        'SHAKE & VAPE > Vapors Line' => 47,
        'SHAKE & VAPE > Wonutz' => 48,
        'SHAKE & VAPE > Yogi' => 49,
        'AROMEN' => 4,
        'AROMEN > Beeren' => 1,
        'AROMEN > Bonbons & Kaugummi' => 2,
        'AROMEN > Cerealien' => 3,
        'AROMEN > Cremiges' => 4,
        'AROMEN > exotische Früchte' => 5,
        'AROMEN > Frisches' => 6,
        'AROMEN > Früchte' => 7,
        'AROMEN > Gebäck' => 8,
        'AROMEN > Getränke' => 9,
        'AROMEN > Gewürze' => 10,
        'AROMEN > Melonen' => 11,
        'AROMEN > Milch & Co.' => 12,
        'AROMEN > Nüsse' => 13,
        'AROMEN > Pflanzen' => 14,
        'AROMEN > Süßigkeiten' => 15,
        'AROMEN > Tabak' => 16,
        'AROMEN > Tee & Kaffee' => 17,
        'AROMEN > Trauben' => 18,
        'AROMEN > Zitrusfrüchte' => 19,
        'AROMEN > 5 Stars Peine' => 20,
        'AROMEN > Bozz Liquids' => 21,
        'AROMEN > Flavorist' => 22,
        'AROMEN > Foozy Juice' => 23,
        'AROMEN > I VG' => 24,
        'AROMEN > Military' => 25,
        'AROMEN > Mr. Nik\'s' => 26,
        'AROMEN > Mule Fuel' => 27,
        'AROMEN > SC' => 28,
        'AROMEN > Smoking Bull' => 29,
        'AROMEN > Tobacco Time' => 30,
        'AROMEN > Twenty Eight Monkeys' => 31,
        'AROMEN > Twisted' => 32,
        'AROMEN > Vampire Vape' => 33,
        'AROMEN > VapeHansa' => 34,
        'AROMEN > Vape Rebelz' => 35,
        'AROMEN > Vapors Line' => 36,
        'AROMEN > 7 Todsünden' => 37,
        'BOXEN' => 5,
        'BOXEN > asMODus' => 1,
        'BOXEN > Aspire' => 2,
        'BOXEN > eLeaf' => 3,
        'BOXEN > GeekVape' => 4,
        'BOXEN > Joyetech' => 5,
        'BOXEN > JustFog' => 6,
        'BOXEN > OBS' => 7,
        'BOXEN > Revenant Vape' => 8,
        'BOXEN > Smoktech' => 9,
        'BOXEN > Steam Crave' => 10,
        'BOXEN > Uwell' => 11,
        'BOXEN > Vapanion' => 12,
        'BOXEN > VapeOnly' => 13,
        'BOXEN > Vaporesso' => 14,
        'BOXEN > Vapor Storm' => 15,
        'BOXEN > Wismec' => 16,
        'BOXEN > Yihi' => 17,
        'BOXEN > Chubby Gorilla' => 18,
        'BOXEN > Digiflavor' => 19,
        'BOXEN > Vsticking' => 20,
        'BOXEN > VooPoo' => 21,
        'BOXEN > iPV' => 22,
        'VERDAMPFER' => 6,
        'VERDAMPFER > Aspire' => 1,
        'VERDAMPFER > eLeaf' => 2,
        'VERDAMPFER > GeekVape' => 3,
        'VERDAMPFER > HellVape' => 4,
        'VERDAMPFER > Joyetech' => 5,
        'VERDAMPFER > JustFog' => 6,
        'VERDAMPFER > Smoktech' => 7,
        'VERDAMPFER > Uwell' => 8,
        'VERDAMPFER > Vapanion' => 9,
        'VERDAMPFER > VapeOnly' => 10,
        'VERDAMPFER > Vaporesso' => 11,
        'VERDAMPFER > Wismec' => 12,
        'VERDAMPFER > Selbstwickler' => 13,
        'VERDAMPFER > Selbstwickler > Advken' => 1,
        'VERDAMPFER > Selbstwickler > asMODus' => 2,
        'VERDAMPFER > Selbstwickler > CoilArt' => 3,
        'VERDAMPFER > Selbstwickler > Digiflavor' => 4,
        'VERDAMPFER > Selbstwickler > Ehpro' => 5,
        'VERDAMPFER > Selbstwickler > GeekVape' => 6,
        'VERDAMPFER > Selbstwickler > HellVape' => 7,
        'VERDAMPFER > Selbstwickler > OBS' => 8,
        'VERDAMPFER > Selbstwickler > Steam Crave' => 9,
        'VERDAMPFER > Selbstwickler > Uwell' => 10,
        'VERDAMPFER > Selbstwickler > Wismec' => 11,
        'VERDAMPFER > Selbstwickler > Wotofo' => 12,
        'VERDAMPFER > Selbstwickler > Cthulhu' => 13,
        'VERDAMPFER > Selbstwickler > Augvape' => 14,
        'VERDAMPFER > Advken' => 14,
        'VERDAMPFER > iPV' => 15,
        'ZUBEHÖR' => 7,
        'ZUBEHÖR > Basen & Shots' => 1,
        'ZUBEHÖR > Verdampferköpfe' => 2,
        'ZUBEHÖR > Verdampferköpfe > Advken' => 1,
        'ZUBEHÖR > Verdampferköpfe > asMODus' => 2,
        'ZUBEHÖR > Verdampferköpfe > Aspire' => 3,
        'ZUBEHÖR > Verdampferköpfe > eLeaf' => 4,
        'ZUBEHÖR > Verdampferköpfe > GeekVape' => 5,
        'ZUBEHÖR > Verdampferköpfe > iPV' => 6,
        'ZUBEHÖR > Verdampferköpfe > Joyetech' => 7,
        'ZUBEHÖR > Verdampferköpfe > JustFog' => 8,
        'ZUBEHÖR > Verdampferköpfe > OBS' => 9,
        'ZUBEHÖR > Verdampferköpfe > Sigelei' => 10,
        'ZUBEHÖR > Verdampferköpfe > Smoktech' => 11,
        'ZUBEHÖR > Verdampferköpfe > Uwell' => 12,
        'ZUBEHÖR > Verdampferköpfe > Vapanion' => 13,
        'ZUBEHÖR > Verdampferköpfe > VapeOnly' => 14,
        'ZUBEHÖR > Verdampferköpfe > Vaporesso' => 15,
        'ZUBEHÖR > Verdampferköpfe > Wismec' => 16,
        'ZUBEHÖR > Pods & Cartridges' => 3,
        'ZUBEHÖR > Pods & Cartridges > Atopack Magic' => 1,
        'ZUBEHÖR > Pods & Cartridges > Aurora Play' => 2,
        'ZUBEHÖR > Pods & Cartridges > Breeze 2' => 3,
        'ZUBEHÖR > Pods & Cartridges > C601' => 4,
        'ZUBEHÖR > Pods & Cartridges > Caliburn Pod' => 5,
        'ZUBEHÖR > Pods & Cartridges > Cobble AIO' => 6,
        'ZUBEHÖR > Pods & Cartridges > Elven' => 7,
        'ZUBEHÖR > Pods & Cartridges > Exceed Edge' => 8,
        'ZUBEHÖR > Pods & Cartridges > iWu' => 9,
        'ZUBEHÖR > Pods & Cartridges > Minifit' => 10,
        'ZUBEHÖR > Pods & Cartridges > Motiv 2' => 11,
        'ZUBEHÖR > Pods & Cartridges > Nautilus AIO' => 12,
        'ZUBEHÖR > Pods & Cartridges > Nord Pod Set' => 13,
        'ZUBEHÖR > Pods & Cartridges > RunAbout' => 14,
        'ZUBEHÖR > Pods & Cartridges > Scado Pod' => 15,
        'ZUBEHÖR > Pods & Cartridges > Spryte AIO' => 16,
        'ZUBEHÖR > Pods & Cartridges > SX Mini Mi Class Pod' => 17,
        'ZUBEHÖR > Pods & Cartridges > Teros' => 18,
        'ZUBEHÖR > Pods & Cartridges > Zero' => 19,
        'ZUBEHÖR > Akkuzellen & -boxen' => 4,
        'ZUBEHÖR > Ladegeräte & -kabel' => 5,
        'ZUBEHÖR > Glastanks & Schutz' => 6,
        'ZUBEHÖR > Glastanks & Schutz > asMODus' => 1,
        'ZUBEHÖR > Glastanks & Schutz > Aspire' => 2,
        'ZUBEHÖR > Glastanks & Schutz > eLeaf' => 3,
        'ZUBEHÖR > Glastanks & Schutz > GeekVape' => 4,
        'ZUBEHÖR > Glastanks & Schutz > HellVape' => 5,
        'ZUBEHÖR > Glastanks & Schutz > iPV' => 6,
        'ZUBEHÖR > Glastanks & Schutz > Joyetech' => 7,
        'ZUBEHÖR > Glastanks & Schutz > JustFog' => 8,
        'ZUBEHÖR > Glastanks & Schutz > Smoktech' => 9,
        'ZUBEHÖR > Glastanks & Schutz > Sigelei' => 10,
        'ZUBEHÖR > Glastanks & Schutz > Steam Crave' => 11,
        'ZUBEHÖR > Glastanks & Schutz > Uwell' => 12,
        'ZUBEHÖR > Glastanks & Schutz > Vapanion' => 13,
        'ZUBEHÖR > Glastanks & Schutz > Vaporesso' => 14,
        'ZUBEHÖR > Glastanks & Schutz > Wismec' => 15,
        'ZUBEHÖR > Mundstücke & Schutz' => 7,
        'ZUBEHÖR > Mundstücke & Schutz > Aspire' => 1,
        'ZUBEHÖR > Mundstücke & Schutz > Chubby Gorilla' => 2,
        'ZUBEHÖR > Mundstücke & Schutz > eLeaf' => 3,
        'ZUBEHÖR > Mundstücke & Schutz > GeekVape' => 4,
        'ZUBEHÖR > Mundstücke & Schutz > HellVape' => 5,
        'ZUBEHÖR > Mundstücke & Schutz > InnoCigs' => 6,
        'ZUBEHÖR > Mundstücke & Schutz > Joyetech' => 7,
        'ZUBEHÖR > Mundstücke & Schutz > JustFog' => 8,
        'ZUBEHÖR > Mundstücke & Schutz > Smoktech' => 9,
        'ZUBEHÖR > Mundstücke & Schutz > Steam Crave' => 10,
        'ZUBEHÖR > Mundstücke & Schutz > Uwell' => 11,
        'ZUBEHÖR > Mundstücke & Schutz > VapeOnly' => 12,
        'ZUBEHÖR > Mundstücke & Schutz > Wismec' => 13,
        'ZUBEHÖR > Dichtungen' => 8,
        'ZUBEHÖR > Dichtungen > Aspire' => 1,
        'ZUBEHÖR > Dichtungen > eLeaf' => 2,
        'ZUBEHÖR > Dichtungen > Joyetech' => 3,
        'ZUBEHÖR > Dichtungen > Smoktech' => 4,
        'ZUBEHÖR > Dichtungen > Uwell' => 5,
        'ZUBEHÖR > Dichtungen > Vapanion' => 6,
        'ZUBEHÖR > Dichtungen > Vaporesso' => 7,
        'ZUBEHÖR > Selbstwickler' => 9,
        'ZUBEHÖR > Selbstwickler > Coils' => 1,
        'ZUBEHÖR > Selbstwickler > Decks' => 2,
        'ZUBEHÖR > Selbstwickler > Umbau- & Eweiterungskits' => 3,
        'ZUBEHÖR > Selbstwickler > Watte' => 4,
        'ZUBEHÖR > Selbstwickler > Werkzeug' => 5,
        'ZUBEHÖR > Selbstwickler > Wickeldraht' => 6,
        'ZUBEHÖR > Taschen & Etuis' => 10,
        'ZUBEHÖR > Leerflaschen' => 11,
        'ZUBEHÖR > Squonker-Flaschen' => 12,
        'ZUBEHÖR > Batteriekappen & -hülsen' => 13,
        'ZUBEHÖR > Magnet & Magnetadapter' => 14,
        'ZUBEHÖR > Reinigung' => 15,
        'ZUBEHÖR > Accessoires' => 16,
        'ZUBEHÖR > Vitrinen' => 17,
    ),
);
