<?php

return [
    'categories' => [
        'E_CIGARETTE'        => 'E-Zigaretten',
        'BOX_MOD'            => 'Akkus',
        'BOX_MOD_CELL'       => 'Akkuträger',
        'SQUONKER_BOX'       => 'Squonker Boxen',
        'E_PIPE'             => 'E-Pfeifen',
        'CLEAROMIZER'        => 'Verdampfer',
        'CLEAROMIZER_RTA'    => 'Clearomizer > DIY > RTA',
        'CLEAROMIZER_RDA'    => 'Clearomizer > DIY > RDA',
        'CLEAROMIZER_RDTA'   => 'Clearomizer > DIY > RDTA',
        'CLEAROMIZER_RDSA'   => 'Clearomizer > DIY > RDSA',
        'LIQUID'             => 'Liquids',
        'EASY3_CAP'          => 'Liquids > Easy 3 Caps',
        'AROMA'              => 'Aromen',
        'SHAKE_VAPE'         => 'Shake & Vape',
        'HEAD'               => 'Zubehör > Köpfe',
        'TANK'               => 'Zubehör > Glastanks & Schutz',
        'TANK_PROTECTION'    => 'Zubehör > Glastanks & Schutz',
        'SEAL'               => 'Zubehör > Dichtungen',
        'DRIP_TIP'           => 'Zubehör > Mundstücke & Schutz',
        'DRIP_TIP_CAP'       => 'Zubehör > Mundstücke & Schutz',
        'POD'                => 'Pods & Cartridges',
        'CARTRIDGE'          => 'Pods & Cartridges',
        'CELL'               => 'Zubehör > Akkuzellen',
        'CELL_BOX'           => 'Zubehör > Akkuzellen',
        'BASE'               => 'Basen & Shots',
        'SHOT'               => 'Basen & Shots',
        'CHARGER'            => 'Zubehör > Ladegeräte & -kabel',
        'CABLE'              => 'Zubehör > Ladegeräte & -kabel',
        'SQUONKER_BOTTLE'    => 'Zubehör > Squonker Flaschen',
        'BAG'                => 'Zubehör > Taschen',
        'TOOL'               => 'Zubehör > DIY > Werkzeug',
        'TOOL_HEATING_PLATE' => 'Zubehör > DIY > Werkzeug',
        'WADDING'            => 'Zubehör > DIY > Watte', // Watte
        'WIRE'               => 'Zubehör > DIY > Wickeldraht',
        'DECK'               => 'Zubehör > DIY > Decks',
        'COIL'               => 'Zubehör > DIY > Coils',
        'RDA_BASE'           => 'Zubehör > DIY > Bases',
        'EMPTY_BOTTLE'       => 'Zubehör > Leerflaschen',
        'CLEANING_SUPPLY'    => 'Zubehör > Reinigung',
        'ACCESSORY'          => 'Zubehör > Acessories',
        'E_HOOKAH'           => 'Vaporizer',
        'VAPORIZER'          => 'Vaporizer',
        'BATTERY_CAP'        => 'Zubehör > Batteriekappen',
        'BATTERY_SLEEVE'     => 'Zubehör > Batteriehülsen',
        'MAGNET'             => 'Zubehör > Magnete',
        'MAGNET_ADAPTOR'     => 'Zubehör > Magnetadapter',
        'EXTENSION_KIT'      => 'Zubehör > Umbau- & Erweiterung',
        'CONVERSION_KIT'     => 'Zubehör > Umbau- & Erweiterung',
        'HEATING_PLATE'      => 'Zubehör > Heizplatten',
        'STORAGE'            => 'Zubehör > Vitrinen',
    ],
];

