<?php

return [
    'descriptionAromaDefault' =>
        '<p><strong>Aroma von ##supplier##</strong> zur Herstellung von E-Liquid. <strong>Geschmack: ##flavor##</strong>.</p>'
        . '<p>Geben Sie das Aroma entsprechend der Dosierempfehlung '
        . 'des Herstellers einer nikotinfreien oder nikotinhaltigen Basis zu und mischen Sie das Ergebnis gut durch. Das fertige '
        . 'Liquid sollte nun vor der Verwendung noch einige Tage reifen, damit sich die Aromastoffe entfalten können. In der Regel werden 1 - 5 Tage Reifezeit empfohlen.</p>'
        . '<p><strong>Aromen sind hochkonzentriert und dürfen keinesfalls pur gedampft werden.</strong></p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>##content## ml Aroma zur Herstellung von E-Liquids </td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Dosierung</td>'
        . '<td>##dosage## %</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe</td>'
        . '<td>Propylenglykol, Aromastoffe</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>',

    'descriptionAromaLongfill' =>
        '<p><strong>Longfill-Aroma von ##supplier##</strong> zur Herstellung von E-Liquid. <strong>Geschmack: ##flavor##</strong>.</p>'
        .'<p>##content## ml Aroma sind in eine ##capacity## ml Flasche abgefüllt.'
        . ' Füllen Sie die Flasche einfach mit einer nikotinfreien oder nikotinhaltigen Base bis oben auf. Verschließen Sie dann die Flasche und schütteln Sie '
        . ' durch, damit sich die Flüssigkeiten gut vermischen. Das fertige E-Liquid sollte nun vor der Verwendung noch einige Tage reifen, damit sich '
        . 'die Aromastoffe entfalten können. In der Regel werden 1 - 5 Tage Reifezeit empfohlen.</p>'
        . '<p><strong>Aromen sind hochkonzentriert und dürfen keinesfalls pur gedampft werden.</strong></p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>##content## ml Aroma in einer ##capacity## ml Flasche </td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Dosierung</td>'
        . '<td>Flasche bis oben mit Basis auffüllen</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe</td>'
        . '<td>Propylenglykol, Aromastoffe</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>',

    'descriptionAroma' => [
        'Elli\'s Aromen' =>
            '<p><strong>Lebensmittelaroma von ##supplier##. Geschmack: ##flavor##.</strong></p>'
            . '<p>Zur Herstellung von E-Liquid fügen Sie das Aroma entsprechend der Dosierempfehlung '
            . 'des Herstellers einer nikotinfreien oder nikotinhaltigen Basis zu und mischen Sie das Ergebnis gut durch. Das fertige '
            . 'Liquid sollte nun vor der Verwendung noch einige Tage reifen, damit sich die Aromastoffe entfalten können.</p>'
            . '<p>Detaillierte Angaben zu Dosierung und Reifezeit von Elli\'s Aromen finden Sie unter diesem Link: <a title="Ellifiziert!" href="http://www.ellifiziert.de/?page=labor" target="_blank">Ellifiziert!</a></p>'
            . '<p><strong>Aromen sind hochkonzentriert und dürfen keinesfalls pur gedampft werden.</strong></p>'
            . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
            . '<tbody>'
            . '<tr>'
            . '<td>Produkt</td>'
            . '<td>##content## ml Lebensmittelaroma</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Geschmack </td>'
            . '<td>##flavor##</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Dosierung</td>'
            . '<td>##dosage## %</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Inhaltsstoffe</td>'
            . '<td>Propylenglykol, Aromastoffe</td>'
            . '</tr>'
            .'</tbody>'
            . '</table>',
        ],

    'descriptionShakeVapeDefault' =>
        '<p><strong>Shake & Vape E-Liquid von ##supplier##. Geschmack: ##flavor##.</strong></p>'
        . '<p>Die ##capacity## ml Flasche enthält ##content## ml überaromatisiertes, nikotinfreies E-Liquid. '
        . 'Füllen Sie die Flasche einfach mit ##fillup## ml Nikotin-Shot oder ##fillup## ml Basis auf. Anschließend gut schütteln, und Ihr E-Liquid ist fertig zum Gebrauch.</p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>##content## ml überaromatisiertes E-Liquid in ##capacity## ml Flasche </td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe<sup>1</sup></td>'
        . '<td>PG, VG, Aromastoffe</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>'
        . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin. </p>',

    'descriptionShakeVapeTwoSizes' =>
        '<p><strong>Shake & Vape E-Liquid von ##supplier##. Geschmack: ##flavor##.</strong></p>'
        . '<p>Wählen Sie zwischen einer ##capacity1## ml Flasche mit ##content1## ml und einer '
        . '##capacity2## ml Flasche mit ##content2## ml überaromatisiertem, nikotinfreien E-Liquid aus. '
        . 'Füllen Sie die Flasche einfach mit ##fillup1## ml bzw. ##fillup2## ml Nikotin-Shot oder Basis auf. Anschließend gut schütteln, und Ihr E-Liquid ist fertig zum Gebrauch.</p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>Überaromatisiertes E-Liquid in Flasche zum Auffüllen</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe<sup>1</sup></td>'
        . '<td>PG, VG, Aromastoffe</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>'
        . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin. </p>',

    'descriptionShakeVape' => [
        'Chicken Shop' =>
            '<p><strong>Shake & Vape E-Liquid von Chicken Shop. Geschmack: ##flavor##.</strong></p>'
            . '<p>Wählen Sie zwischen 25 ml und 200 ml überaromatisiertem, nikotinfreien E-Liquid aus.</p>'
            . '<p>Die Variante mit 25 ml E-Liquid erhalten in einer 30 ml Flasche. '
            . 'Füllen Sie diese Flasche einfach mit 5 ml Nikotin-Shot oder Basis auf. Anschließend gut schütteln, und Ihr E-Liquid ist fertig zum Gebrauch.</p>'
            . '<p>In der 200 ml Variante erhalten Sie neben der vollständig mit überaromatisiertem E-Liquid gefüllten 200 ml Flasche zwei 60 ml Leerflaschen zum '
            . 'Mischen Ihres E-Liquids. Füllen Sie dazu eine 60 ml Flasche mit 50 ml E-Liquid und 10 ml Nikotin-Shot oder Basis. '
            . 'Gut schütteln und Ihr E-Liquid ist fertig.</p>'
            . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
            . '<tbody>'
            . '<tr>'
            . '<td>Produkt</td>'
            . '<td>Überaromatisiertes E-Liquid</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Geschmack </td>'
            . '<td>##flavor##</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Inhaltsstoffe<sup>1</sup></td>'
            . '<td>PG, VG, Aromastoffe</td>'
            . '</tr>'
            .'</tbody>'
            . '</table>'
            . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin</p>',

        'Pink Spot' =>
            '<p><strong>Shake & Vape E-Liquid von Pink Spot. Geschmack: ##flavor##.</strong></p>'
            . '<p>Die 60 ml Flasche enthält 50 ml überaromatisiertes, nikotinfreies E-Liquid. '
            . 'Füllen Sie die Flasche einfach mit einem 10 ml Nikotin-Shot oder 10 ml Basis auf. Anschließend gut schütteln, und Ihr E-Liquid ist fertig zum Gebrauch.</p>'
            . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
            . '<tbody>'
            . '<tr>'
            . '<td>Produkt</td>'
            . '<td>50 ml überaromatisiertes E-Liquid in 60 ml Flasche </td>'
            . '</tr>'
            . '<tr>'
            . '<td>Geschmack </td>'
            . '<td>##flavor##</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Basis (PG/VG)<sup>1</sup></td>'
            . '<td>40:60</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Inhaltsstoffe<sup>1</sup></td>'
            . '<td>PG, VG, Aromastoffe</td>'
            . '</tr>'
            .'</tbody>'
            . '</table>'
            . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin</p>',
        'Koncept XIX' =>
            '<p><strong>Shake & Vape E-Liquid von Vampire Vape. Geschmack: ##flavor##.</strong></p>'
            . '<p>Die 60 ml Flasche enthält 50 ml überaromatisiertes, nikotinfreies E-Liquid. '
            . 'Füllen Sie die Flasche einfach mit einem 10 ml Nikotin-Shot oder 10 ml Basis auf. Anschließend gut schütteln, und Ihr E-Liquid ist fertig zum Gebrauch.</p>'
            . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
            . '<tbody>'
            . '<tr>'
            . '<td>Produkt</td>'
            . '<td>50 ml überaromatisiertes E-Liquid in 60 ml Flasche </td>'
            . '</tr>'
            . '<tr>'
            . '<td>Geschmack </td>'
            . '<td>##flavor##</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Basis (PG/VG)<sup>1</sup></td>'
            . '<td>20:80</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Inhaltsstoffe<sup>1</sup></td>'
            . '<td>PG, VG, Aromastoffe</td>'
            . '</tr>'
            .'</tbody>'
            . '</table>'
            . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin</p>'
        ],

    'descriptionLiquidDefault' =>
        '<p><strong>Gebrauchsfertiges E-Liquid von ##supplier## für die E-Zigarette. Geschmack: ##flavor##.</strong></p><p>Einfach in den Verdampfer der E-Zigarette einfüllen und losdampfen!</p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>Gebrauchsfertiges E-Liquid, 10 ml Flasche </td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe<sup>1</sup></td>'
        . '<td>PG, VG, Aromastoffe, Nikotin nach Wahl</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>'
        . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin</p>',

    'descriptionLiquidFixedNicotine' =>
        '<p><strong>Gebrauchsfertiges E-Liquid von ##supplier## für die E-Zigarette. Geschmack: ##flavor##.</strong></p><p>Einfach in den Verdampfer der E-Zigarette einfüllen und losdampfen!</p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>Gebrauchsfertiges E-Liquid, 10 ml Flasche </td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe<sup>1</sup></td>'
        . '<td>PG, VG, Aromastoffe, Nikotin: ##nicotine## mg/ml</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>'
        . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin</p>',

    'descriptionsByProductNumber' => [
        'PY100A10-3B' =>
            '<p><strong>Dieses Bundle enthält die drei Longfill-Aromen Fuze, Destruction und Blast von Pyromania</strong> zur Herstellung von E-Liquid.</p>'
            . '<p>Jeweils 15 ml Aroma sind in eine 60 ml Chubby Gorilla Flasche abgefüllt.'
            . ' Füllen Sie eine Flasche einfach mit einer nikotinfreien oder nikotinhaltigen Base bis oben auf. Verschließen Sie dann die Flasche und schütteln Sie '
            . ' durch, damit sich die Flüssigkeiten gut vermischen. Das fertige E-Liquid sollte nun vor der Verwendung noch einige Tage reifen, damit sich '
            . 'die Aromastoffe entfalten können. In der Regel werden 1 - 5 Tage Reifezeit empfohlen.</p>'
            . '<p><strong>Aromen sind hochkonzentriert und dürfen keinesfalls pur gedampft werden.</strong></p>'
            . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
            . '<tbody>'
            . '<tr>'
            . '<td>Produkt</td>'
            . '<td> 3 x 15 ml Aroma in 60 ml Flasche</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Geschmack</td>'
            . '<td>Blast</td>'
            . '<td>Drachenfrucht, Papaya</td>'
            . '</tr>'
            . '<tr>'
            . '</tr>'
            . '<tr>'
            . '<td></td>'
            . '<td>Destruction</td>'
            . '<td>Joghurt, Limette, Kokos</td>'
            . '</tr>'
            . '<tr>'
            . '<td></td>'
            . '<td>Fuze</td>'
            . '<td>schwarze Johannisbeere, Grapefruit</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Dosierung</td>'
            . '<td>Flasche bis oben mit Base auffüllen</td>'
            . '</tr>'
            . '<tr>'
            . '<td>Inhaltsstoffe</td>'
            . '<td>Propylenglykol, Aromastoffe</td>'
            . '</tr>'
            .'</tbody>'
            . '</table>'
        ],

    'descriptionEasy3' =>
        '<p><strong>Gebrauchsfertiges, mit dem bekannten InnoCigs Liquid gefülltes Pod von ##supplier## exklusiv für die ##supplier## Easy 3 E-Zigarette. Geschmack: ##flavor##.</strong></p>'
        . '<p>Schieben Sie das Pod einfach in die Easy 3 und dampfen Sie los! Das Pod kann nicht nachbefüllt werden. Wenn es leer ist, werfen Sie es weg und setzen ein neues ein. Die Packung enthält zwei Pods.</p>'
        . '<table border="5" frame="hsides" rules="rows" cellspacing="0" cellpadding="2">'
        . '<tbody>'
        . '<tr>'
        . '<td>Produkt</td>'
        . '<td>Pod für die ##supplier## Easy 3, 2 ml </td>'
        . '</tr>'
        . '<tr>'
        . '<td>Geschmack </td>'
        . '<td>##flavor##</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Widerstand</td>'
        . '<td>1,1 Ohm</td>'
        . '</tr>'
        . '<tr>'
        . '<td>Inhaltsstoffe<sup>1</sup></td>'
        . '<td>PG (55%), VG (35%), Wasser (10%), Aromastoffe, Nikotin nach Wahl</td>'
        . '</tr>'
        .'</tbody>'
        . '</table>'
        . '<p><sup>1</sup> PG: Propylenglykol, VG: pflanzliches Glycerin</p>'
        . '<p><strong>Lieferumfang</strong>'
        . '<ul><li>2x SC Easy 3 Pod 1,1 Ohm</li><li>1x Gebrauchsinformation</li></ul>'
        .'</p>'
        . '<p><strong>Kostenhinweis: </strong> Mit der SC Easy 3 dampfen Sie sehr bequem. Sehr viel kostengünstiger kommen Sie aber weg, wenn Sie statt der Easy 3 ein wiederbefüllbares '
        . 'Pod-System verwenden und sich das Innocigs Liquid dazu in der 10 ml Flasche kaufen. Lesen Sie dazu bitte auch unsere '
        . '<strong><a title="Kosten der E-Zigarette" href="https://www.vapee.de/e-zigarette-ratgeber-kosten-im-vergleich/">Hinweise zu den Kosten von E-Zigaretten</a></strong></p>',


];