<?php
return array(
    'Beeren' => array(
        0 => 'Beeren',
        1 => 'Blaubeere',
        2 => 'Boysenbeere',
        3 => 'Brombeere',
        4 => 'Cranberry',
        5 => 'Erdbeere',
        6 => 'Himbeere',
        7 => 'Johannisbeere',
        8 => 'Waldbeeren',
        9 => 'Walderdbeere',
        10 => 'blaue Himbeere',
        11 => 'rote Beeren',
        12 => 'schwarze Johannisbeere',
        13 => 'Stachelbeere',
    ),
    'Bonbons & Kaugummi' => array(
        0 => 'Bonbon',
        1 => 'Butterscotch Toffee',
        2 => 'Dragee',
        3 => 'Eisbonbon',
        4 => 'Fruchtbonbon',
        5 => 'Fudge',
        6 => 'Gummibärchen',
        7 => 'Kaubonbon',
        8 => 'Kaugummi',
        9 => 'Toffee',
        10 => 'süßes Kaugummi',
    ),
    'Cerealien' => array(
        0 => 'Cerealien',
        1 => 'Haferflocken',
        2 => 'Müsli',
        3 => 'Müsliriegel',
    ),
    'Cremiges' => array(
        0 => 'Cream',
        1 => 'Eiscreme',
    ),
    'Frisches' => array(
        0 => 'Eukalyptus',
        1 => 'Koolada',
        2 => 'Menthol',
        3 => 'Minze',
        4 => 'Pfefferminze',
        5 => 'Eis',
    ),
    'Früchte' => array(
        0 => 'Amarenakirsche',
        1 => 'Ananas',
        2 => 'Apfel',
        3 => 'Banane',
        4 => 'Birne',
        5 => 'Früchte',
        6 => 'Kirsche',
        7 => 'Nashi Birne',
        8 => 'Nektarine',
        9 => 'Pfirsich',
        10 => 'Sauerkirsche',
        11 => 'Waldfrüchte',
        12 => 'dunkle Waldfrüchte',
        13 => 'grüner Apfel',
        14 => 'rote Früchte',
        15 => 'roter Apfel',
        16 => 'saure Früchte',
        17 => 'süße Früchte',
        18 => 'Mirabelle',
        19 => 'Aprikose',
        20 => 'Sommerfrüchte',
        21 => 'Bratapfel',
    ),
    'Gebäck' => array(
        0 => 'Apfelstrudel',
        1 => 'Baklava',
        2 => 'Bienenstich',
        3 => 'Biskuit',
        4 => 'Blätterteig',
        5 => 'Churro',
        6 => 'Crumble',
        7 => 'Donut',
        8 => 'Keks',
        9 => 'Kuchen',
        10 => 'Käsekuchen',
        11 => 'Macaron',
        12 => 'Muffin',
        13 => 'Muffin',
        14 => 'Müsliriegel',
        15 => 'Pfannkuchen',
        16 => 'Salzbretzel',
        17 => 'Streuselkuchen',
        18 => 'Toast',
        19 => 'Torte',
        20 => 'Waffel',
    ),
    'Getränke' => array(
        0 => 'Barley Water',
        1 => 'Bier',
        2 => 'Brause',
        3 => 'Cassis',
        4 => 'Cola',
        5 => 'Energy Drink',
        6 => 'Gin',
        7 => 'Highland Soda',
        8 => 'Limonade',
        9 => 'Martini',
        10 => 'Mojito',
        11 => 'Sambuca',
        12 => 'Smoothie',
        13 => 'Soda',
        14 => 'Tonic',
        15 => 'Curaçao',
    ),
    'Gewürze' => array(
        0 => 'Anis',
        1 => 'Gewürznelke',
        2 => 'Lakritz',
        3 => 'Puderzucker',
        4 => 'Salz',
        5 => 'Süßholz',
        6 => 'Traubenzucker',
        7 => 'Vanille',
        8 => 'Zimt',
        9 => 'Zucker',
        10 => 'brauner Zucker',
        11 => 'schwarzer Trüffel',
    ),
    'Melonen & Gurken' => array(
        0 => 'Honigmelone',
        1 => 'Melone',
        2 => 'Melonenmix',
        3 => 'Wassermelone',
        4 => 'Gurke',
    ),
    'Milch & Co.' => array(
        0 => 'Butter',
        1 => 'Buttermilch',
        2 => 'Joghurt',
        3 => 'Milch',
        4 => 'Milch-Shake',
        5 => 'Sahne',
        6 => 'griechischer Joghurt',
        7 => 'Schmand',
    ),
    'Nussiges' => array(
        0 => 'Erdnuss',
        1 => 'Erdnussbutter',
        2 => 'Haselnuss',
        3 => 'Mandel',
        4 => 'Nougat',
        5 => 'Nuss',
        6 => 'Pekanuss',
        7 => 'Pistazie',
        8 => 'geröstete Nüsse',
    ),
    'Pflanzen' => array(
        0 => 'Aloe Vera',
        1 => 'Guave',
        2 => 'Ingwer',
        3 => 'Marula',
        4 => 'Rhabarber',
        5 => 'Waldmeister',
    ),
    'Pudding' => array(
        0 => 'Pannacotta',
        1 => 'Pudding',
        2 => 'Wackelpudding',
    ),
    'Süßigkeiten' => array(
        0 => 'Buttercreme',
        1 => 'Honig',
        2 => 'Karamell',
        3 => 'Marmelade',
        4 => 'Marshmellow',
        5 => 'Popcorn',
        6 => 'Rosinen',
        7 => 'Schokolade',
        8 => 'Zuckerwatte',
        9 => 'weiße Schokolade',
    ),
    'Tabak' => array(
        0 => 'Tabak',
    ),
    'Tee & Kaffee' => array(
        0 => 'Cappucino',
        1 => 'Eistee',
        2 => 'Kaffee',
        3 => 'Mocca',
        4 => 'Tee',
        5 => 'grüner Tee',
        6 => 'schwarzer Tee',
    ),
    'Trauben' => array(
        0 => 'Traube',
        1 => 'dunkle Traube',
        2 => 'helle Traube',
        3 => 'rote Traube',
        4 => 'schwarze Traube',
    ),
    'Zitrusfrüchte' => array(
        0 => 'Blutorange',
        1 => 'Grapefruit',
        2 => 'Limette',
        3 => 'Limone',
        4 => 'Mandarine',
        5 => 'Orange',
        6 => 'Zitrone',
        7 => 'Zitrusfrüchte',
    ),
    'exotische Früchte' => array(
        0 => 'Drachenfrucht',
        1 => 'Granatapfel',
        2 => 'Kaktusfeige',
        3 => 'Kiwi',
        4 => 'Kokos',
        5 => 'Litschi',
        6 => 'Mango',
        7 => 'Maracuja',
        8 => 'Papaya',
        9 => 'Passionsfrucht',
        10 => 'Sternfrucht',
        11 => 'exotische Früchte',
        12 => 'karibische Früchte',
        13 => 'tropische Früchte',
    ),
);
