<?php

return array (
  'Beeren' => 
  array (
    0 => 'Acai',
    1 => 'Aronia',
    2 => 'Beeren',
    3 => 'Beerenmix',
    4 => 'Blaubeere',
    5 => 'Boysenbeere',
    6 => 'Brombeere',
    7 => 'Cranberry',
    8 => 'Erdbeere',
    9 => 'Heidelbeere',
    10 => 'Himbeere',
    11 => 'Johannisbeere',
    12 => 'Preiselbeere',
    13 => 'Stachelbeere',
    14 => 'Stachelbeergelee',
    15 => 'Waldbeeren',
    16 => 'Walderdbeere',
    17 => 'blaue Himbeere',
    18 => 'rote Beeren',
    19 => 'rote Himbeere',
    20 => 'schwarze Himbeere',
    21 => 'schwarze Johannisbeere',
    22 => 'süße Beeren',
  ),
  'Bonbons & Kaugummi' => 
  array (
    0 => 'Bonbon',
    1 => 'Butterscotch Candy',
    2 => 'Butterscotch Toffee',
    3 => 'Dragee',
    4 => 'Eisbonbon',
    5 => 'Fruchtbonbon',
    6 => 'Fudge',
    7 => 'Gummibärchen',
    8 => 'Kaubonbon',
    9 => 'Kaugummi',
    10 => 'Minzpastille',
    11 => 'Orangenbonbon',
    12 => 'Pfefferminzbonbon',
    13 => 'Toffee',
    14 => 'rote Fruchtgummis',
    15 => 'süßes Kaugummi',
  ),
  'Cerealien' => 
  array (
    0 => 'Cerealien',
    1 => 'Cornflakes',
    2 => 'Haferflocken',
    3 => 'Müsli',
    4 => 'Müsliriegel',
    5 => 'Rice Crispies',
  ),
  'Cremiges' => 
  array (
    0 => 'Cream',
    1 => 'Creme',
    2 => 'Crème Brûlée',
    3 => 'Eiscreme',
    4 => 'Konfitüre',
    5 => 'Pannacotta',
    6 => 'Pudding',
    7 => 'Vanillepudding',
    8 => 'Wackelpudding',
  ),
  'Frisches & Eiscreme' => 
  array (
    0 => 'Bananensplit',
    1 => 'Eis',
    2 => 'Eisbonbon',
    3 => 'Eiscreme',
    4 => 'Eistee',
    5 => 'Eukalyptus',
    6 => 'Frische',
    7 => 'Koolada',
    8 => 'Menthol',
    9 => 'Minze',
    10 => 'Minzmix',
    11 => 'Pfefferminze',
    12 => 'Sandwich-Eis',
    13 => 'Slush Eis',
    14 => 'Spearmint',
    15 => 'Vanilleeis',
    16 => 'Zitronensorbet',
    17 => 'marokkanische Minze',
  ),
  'Früchte' => 
  array (
    0 => 'Amarenakirsche',
    1 => 'Ananas',
    2 => 'Apfel',
    3 => 'Apfelmix',
    4 => 'Aprikose',
    5 => 'Banane',
    6 => 'Birne',
    7 => 'Bratapfel',
    8 => 'Fruchtsäure',
    9 => 'Früchte',
    10 => 'Früchtemix',
    11 => 'Kirsche',
    12 => 'Mirabelle',
    13 => 'Nashi Birne',
    14 => 'Nektarine',
    15 => 'Pfirsich',
    16 => 'Pflaume',
    17 => 'Sauerkirsche',
    18 => 'Schattenmorelle',
    19 => 'Sommerfrüchte',
    20 => 'Waldfrüchte',
    21 => 'Wildfrüchte',
    22 => 'dunkle Waldfrüchte',
    23 => 'gelber Apfel',
    24 => 'grüner Apfel',
    25 => 'rote Früchte',
    26 => 'roter Apfel',
    27 => 'saure Früchte',
    28 => 'süße Früchte',
    29 => 'süße Kirsche',
  ),
  'Gebäck' => 
  array (
    0 => 'Apfelkuchen',
    1 => 'Apfelstrudel',
    2 => 'Backwaren',
    3 => 'Baiser',
    4 => 'Baklava',
    5 => 'Belgische Waffel',
    6 => 'Berliner',
    7 => 'Bienenstich',
    8 => 'Biskuit',
    9 => 'Blaubeerkuchen',
    10 => 'Blätterteig',
    11 => 'Brandteig',
    12 => 'Butttercreme-Torte',
    13 => 'Churro',
    14 => 'Cookie',
    15 => 'Crumble',
    16 => 'Donut',
    17 => 'Keks',
    18 => 'Kirschkuchen',
    19 => 'Kuchen',
    20 => 'Käsekuchen',
    21 => 'Macaron',
    22 => 'Meringe',
    23 => 'Muffin',
    24 => 'Müsliriegel',
    25 => 'Pfannkuchen',
    26 => 'Salzbretzel',
    27 => 'Schwarzwälder Kirschtorte',
    28 => 'Streusel',
    29 => 'Streuselkuchen',
    30 => 'Toast',
    31 => 'Torte',
    32 => 'Waffel',
    33 => 'Zimtrolle',
    34 => 'Zimtschnecke',
    35 => 'Zitronenkuchen',
    36 => 'Zitronentorte',
  ),
  'Getränke' => 
  array (
    0 => 'Apfelsaft',
    1 => 'Barley Water',
    2 => 'Bier',
    3 => 'Brause',
    4 => 'Cassis',
    5 => 'Cassisbrause',
    6 => 'Cherry Cola',
    7 => 'Cola',
    8 => 'Curaçao',
    9 => 'Eierlikör',
    10 => 'Energy Drink',
    11 => 'Gin',
    12 => 'Gin Basil Smash',
    13 => 'Highland Soda',
    14 => 'Ingwerbier',
    15 => 'Jamaica Rum',
    16 => 'Limonade',
    17 => 'Limonade in pink',
    18 => 'Martini',
    19 => 'Mojito',
    20 => 'Pfirsichtee',
    21 => 'Pina Colada',
    22 => 'Rum',
    23 => 'Sambuca',
    24 => 'Smoothie',
    25 => 'Soda',
    26 => 'Tequila Sunrise',
    27 => 'Tonic',
    28 => 'Virgin Colada',
    29 => 'Whisky',
    30 => 'Wodka',
    31 => 'Zitronentee',
    32 => 'bittere Limonade',
    33 => 'karibischer Rum',
  ),
  'Gewürze' => 
  array (
    0 => 'Anis',
    1 => 'Basilikum',
    2 => 'Bourbon Vanille',
    3 => 'Bourbon-Vanille',
    4 => 'Chili',
    5 => 'Gewürze',
    6 => 'Gewürznelke',
    7 => 'Kardamom',
    8 => 'Kräuter',
    9 => 'Lakritz',
    10 => 'Limettenschale',
    11 => 'Masala-Gewürze',
    12 => 'Puderzucker',
    13 => 'Rauch',
    14 => 'Salz',
    15 => 'Süßholz',
    16 => 'Traubenzucker',
    17 => 'Vanille',
    18 => 'Zimt',
    19 => 'Zucker',
    20 => 'brauner Zucker',
    21 => 'schwarzer Trüffel',
  ),
  'Melonen' => 
  array (
    0 => 'Cantaloupe-Melone',
    1 => 'Honigmelone',
    2 => 'Melone',
    3 => 'Melonenmix',
    4 => 'Wassermelone',
    5 => 'Yubari Melone',
    6 => 'Zuckermelone',
    7 => 'verschiedene Melonensorten',
  ),
  'Milch & Co.' => 
  array (
    0 => 'Butter',
    1 => 'Buttermilch',
    2 => 'Joghurt',
    3 => 'Milch',
    4 => 'Milchshake',
    5 => 'Sahne',
    6 => 'Schmand',
    7 => 'Schokomilch',
    8 => 'Sojamilch',
    9 => 'griechischer Joghurt',
    10 => 'süße Schlagsahne',
  ),
  'Nüsse' => 
  array (
    0 => 'Erdnuss',
    1 => 'Erdnussbutter',
    2 => 'Haselnuss',
    3 => 'Makadamia-Nuss',
    4 => 'Mandel',
    5 => 'Nougat',
    6 => 'Nuss',
    7 => 'Pekanuss',
    8 => 'Pistazie',
    9 => 'Walnuss',
    10 => 'geröstete Nüsse',
  ),
  'Pflanzen' => 
  array (
    0 => 'Agave',
    1 => 'Aloe Vera',
    2 => 'Guave',
    3 => 'Gurke',
    4 => 'Heu',
    5 => 'Hibiskus',
    6 => 'Holunder',
    7 => 'Holunderblüte',
    8 => 'Ingwer',
    9 => 'Marula',
    10 => 'OG Kush',
    11 => 'Orchidee',
    12 => 'Rhabarber',
    13 => 'Waldmeister',
  ),
  'Sonstige' => 
  array (
    0 => 'Beere',
    1 => 'Holznote',
    2 => 'Lakritze',
    3 => 'Pfirisch',
    4 => 'Süßigkeiten',
    5 => 'Weintraube',
  ),
  'Süßigkeiten' => 
  array (
    0 => 'Ahornsirup',
    1 => 'Buttercreme',
    2 => 'Butterscotch',
    3 => 'Candy',
    4 => 'Erdbeerlolli',
    5 => 'Erdbeerschnüre',
    6 => 'Frucht-Loops',
    7 => 'Grenadine',
    8 => 'Himbeerlolli',
    9 => 'Honig',
    10 => 'Kakao',
    11 => 'Kakaobohne',
    12 => 'Karamell',
    13 => 'Kirschlolli',
    14 => 'Lolli',
    15 => 'Marmelade',
    16 => 'Marshmallow',
    17 => 'Marshmellow',
    18 => 'Marzipan',
    19 => 'Popcorn',
    20 => 'Praline',
    21 => 'Rohrzucker',
    22 => 'Rosine',
    23 => 'Rosinen',
    24 => 'Schokolade',
    25 => 'Süßwaren',
    26 => 'Waldhonig',
    27 => 'Weingummi',
    28 => 'Zuckersirup',
    29 => 'Zuckerwatte',
    30 => 'gebackene Mandeln',
    31 => 'gebrannte Mandeln',
    32 => 'kandierter Apfel',
    33 => 'karamellisierte Früchte',
    34 => 'saures Weingummi',
    35 => 'weiße Schokolade',
  ),
  'Tabak' => 
  array (
    0 => 'Burley Tabak',
    1 => 'Doppelapfel',
    2 => 'Pfeifentabak',
    3 => 'Rohtabakblätter',
    4 => 'Shisha-Tabak',
    5 => 'Tabak',
    6 => 'Virginia Tabak',
    7 => 'Zigarrentabak',
  ),
  'Tee & Kaffee' => 
  array (
    0 => 'Café Latte',
    1 => 'Cappuccino',
    2 => 'Ceylon Tee',
    3 => 'Chai Latte',
    4 => 'Earl Grey',
    5 => 'Eistee',
    6 => 'Espresso',
    7 => 'Frappé',
    8 => 'Jasmintee',
    9 => 'Kaffee',
    10 => 'Kaffee-Likör',
    11 => 'Matcha',
    12 => 'Mocca',
    13 => 'Tee',
    14 => 'grüner Tee',
    15 => 'grüner Zitronentee',
    16 => 'schwarzer Tee',
  ),
  'Trauben' => 
  array (
    0 => 'Traube',
    1 => 'Trauben-Mix',
    2 => 'dunkle Traube',
    3 => 'helle Traube',
    4 => 'rote Traube',
    5 => 'schwarze Traube',
  ),
  'Zitrusfrüchte' => 
  array (
    0 => 'Bergamotte',
    1 => 'Blutorange',
    2 => 'Grapefruit',
    3 => 'Limette',
    4 => 'Limone',
    5 => 'Mandarine',
    6 => 'Orange',
    7 => 'Zitrone',
    8 => 'Zitronengras',
    9 => 'Zitrusfrüchte',
  ),
  'exotische Früchte' => 
  array (
    0 => 'Drachenfrucht',
    1 => 'Feige',
    2 => 'Granatapfel',
    3 => 'Kaktusfeige',
    4 => 'Kiwi',
    5 => 'Kokos',
    6 => 'Kokosmilch',
    7 => 'Litschi',
    8 => 'Mango',
    9 => 'Maracuja',
    10 => 'Papaya',
    11 => 'Passionsfrucht',
    12 => 'Sternfrucht',
    13 => 'Tropical Mix',
    14 => 'exotische Früchte',
    15 => 'karibische Früchte',
    16 => 'tropische Früchte',
  ),
);