<?php

return array (
  'Beeren' => 
  array (
    0 => 'Acai',
    1 => 'Aronia',
    2 => 'Aroniabeere',
    3 => 'Beere',
    4 => 'Beeren',
    5 => 'Beerenmix',
    6 => 'Blaubeere',
    7 => 'Boysenbeere',
    8 => 'Brombeere',
    9 => 'Cranberry',
    10 => 'Erdbeere',
    11 => 'Gojibeere',
    12 => 'Heidelbeere',
    13 => 'Himbeere',
    14 => 'Johannisbeere',
    15 => 'Maulbeere',
    16 => 'Preiselbeere',
    17 => 'Stachelbeere',
    18 => 'Stachelbeergelee',
    19 => 'Waldbeeren',
    20 => 'Walderdbeere',
    21 => 'blaue Himbeere',
    22 => 'dunkle Beeren',
    23 => 'rote Beeren',
    24 => 'rote Himbeere',
    25 => 'schwarze Himbeere',
    26 => 'schwarze Johannisbeere',
    27 => 'süße Beeren',
  ),
  'Bonbons & Kaugummi' => 
  array (
    0 => 'Bonbon',
    1 => 'Dragee',
    2 => 'Eisbonbon',
    3 => 'Fruchtbonbon',
    4 => 'Fruchtgummi',
    5 => 'Fudge',
    6 => 'Gummibärchen',
    7 => 'Kaubonbon',
    8 => 'Kaugummi',
    9 => 'Minzpastille',
    10 => 'Orangenbonbon',
    11 => 'Pfefferminzbonbon',
    12 => 'Toffee',
    13 => 'rote Fruchtgummis',
    14 => 'süßes Kaugummi',
  ),
  'Cerealien' => 
  array (
    0 => 'Cerealien',
    1 => 'Cornflakes',
    2 => 'Haferflocken',
    3 => 'Müsli',
    4 => 'Müsliriegel',
    5 => 'Rice Crispies',
  ),
  'Cremiges' => 
  array (
    0 => 'Cream',
    1 => 'Creme',
    2 => 'Crème Brûlée',
    3 => 'Eiscreme',
    4 => 'Konfitüre',
    5 => 'Pannacotta',
    6 => 'Pudding',
    7 => 'Vanillepudding',
    8 => 'Wackelpudding',
  ),
  'Frisches & Eiscreme' => 
  array (
    0 => 'Bananensplit',
    1 => 'Eis',
    2 => 'Eisbonbon',
    3 => 'Eiscreme',
    4 => 'Eistee',
    5 => 'Eukalyptus',
    6 => 'Frische',
    7 => 'Koolada',
    8 => 'Menthol',
    9 => 'Minze',
    10 => 'Minzmix',
    11 => 'Pfefferminze',
    12 => 'Sandwich-Eis',
    13 => 'Slush Eis',
    14 => 'Spearmint',
    15 => 'Vanilleeis',
    16 => 'Zitronensorbet',
    17 => 'marokkanische Minze',
  ),
  'Früchte' => 
  array (
    0 => 'Amarenakirsche',
    1 => 'Ananas',
    2 => 'Apfel',
    3 => 'Apfelmix',
    4 => 'Aprikose',
    5 => 'Banane',
    6 => 'Birne',
    7 => 'Bratapfel',
    8 => 'Fruchtsäure',
    9 => 'Früchte',
    10 => 'Früchtemix',
    11 => 'Kirsche',
    12 => 'Mirabelle',
    13 => 'Nashi Birne',
    14 => 'Nektarine',
    15 => 'Pfirsich',
    16 => 'Pflaume',
    17 => 'Sauerkirsche',
    18 => 'Schattenmorelle',
    19 => 'Sommerfrüchte',
    20 => 'Waldfrüchte',
    21 => 'Wildfrüchte',
    22 => 'dunkle Waldfrüchte',
    23 => 'gelber Apfel',
    24 => 'grüner Apfel',
    25 => 'rote Früchte',
    26 => 'roter Apfel',
    27 => 'saure Früchte',
    28 => 'süße Früchte',
    29 => 'süße Kirsche',
  ),
  'Gebäck' => 
  array (
    0 => 'Apfelkuchen',
    1 => 'Apfelstrudel',
    2 => 'Backwaren',
    3 => 'Baiser',
    4 => 'Baklava',
    5 => 'Belgische Waffel',
    6 => 'Berliner',
    7 => 'Bienenstich',
    8 => 'Biskuit',
    9 => 'Blaubeerkuchen',
    10 => 'Blätterteig',
    11 => 'Brandteig',
    12 => 'Butterkeks',
    13 => 'Butttercreme-Torte',
    14 => 'Churro',
    15 => 'Cookie',
    16 => 'Crumble',
    17 => 'Donut',
    18 => 'Keks',
    19 => 'Kirschkuchen',
    20 => 'Kuchen',
    21 => 'Käsekuchen',
    22 => 'Lebkuchen',
    23 => 'Macaron',
    24 => 'Meringe',
    25 => 'Muffin',
    26 => 'Müsliriegel',
    27 => 'Nussecke',
    28 => 'Pfannkuchen',
    29 => 'Salzbretzel',
    30 => 'Schokotörtchen',
    31 => 'Schwarzwälder Kirschtorte',
    32 => 'Streusel',
    33 => 'Streuselkuchen',
    34 => 'Toast',
    35 => 'Torte',
    36 => 'Vanillekipferl',
    37 => 'Waffel',
    38 => 'Zimtgebäck',
    39 => 'Zimtrolle',
    40 => 'Zimtschnecke',
    41 => 'Zitronenkuchen',
    42 => 'Zitronentorte',
  ),
  'Getränke' => 
  array (
    0 => 'Apfelsaft',
    1 => 'Barley Water',
    2 => 'Bier',
    3 => 'Brause',
    4 => 'Cassis',
    5 => 'Cassisbrause',
    6 => 'Cherry Cola',
    7 => 'Cola',
    8 => 'Curaçao',
    9 => 'Eierlikör',
    10 => 'Eierpunsch',
    11 => 'Energy Drink',
    12 => 'Gin',
    13 => 'Gin Basil Smash',
    14 => 'Glühwein',
    15 => 'Glühwein mit Schuss',
    16 => 'Highland Soda',
    17 => 'Ingwerbier',
    18 => 'Jamaica Rum',
    19 => 'Likör',
    20 => 'Limonade',
    21 => 'Limonade in pink',
    22 => 'Martini',
    23 => 'Mojito',
    24 => 'Pfirsichtee',
    25 => 'Pina Colada',
    26 => 'Prosecco',
    27 => 'Punsch',
    28 => 'Rum',
    29 => 'Sambuca',
    30 => 'Smoothie',
    31 => 'Soda',
    32 => 'Tequila Sunrise',
    33 => 'Tonic',
    34 => 'Virgin Colada',
    35 => 'Whisky',
    36 => 'Wodka',
    37 => 'Zitronentee',
    38 => 'bittere Limonade',
    39 => 'karibischer Rum',
  ),
  'Gewürze' => 
  array (
    0 => 'Anis',
    1 => 'Basilikum',
    2 => 'Bourbon Vanille',
    3 => 'Bourbon-Vanille',
    4 => 'Chili',
    5 => 'Gewürze',
    6 => 'Gewürznelke',
    7 => 'Holznote',
    8 => 'Kardamom',
    9 => 'Kräuter',
    10 => 'Lakritz',
    11 => 'Limettenschale',
    12 => 'Masala-Gewürze',
    13 => 'Puderzucker',
    14 => 'Rauch',
    15 => 'Salz',
    16 => 'Süßholz',
    17 => 'Traubenzucker',
    18 => 'Vanille',
    19 => 'Zimt',
    20 => 'Zucker',
    21 => 'brauner Zucker',
    22 => 'schwarzer Trüffel',
  ),
  'Melonen' => 
  array (
    0 => 'Cantaloupe-Melone',
    1 => 'Honigmelone',
    2 => 'Melone',
    3 => 'Melonenmix',
    4 => 'Wassermelone',
    5 => 'Yubari Melone',
    6 => 'Zuckermelone',
    7 => 'verschiedene Melonensorten',
  ),
  'Milch & Co.' => 
  array (
    0 => 'Butter',
    1 => 'Buttermilch',
    2 => 'Joghurt',
    3 => 'Milch',
    4 => 'Milchshake',
    5 => 'Sahne',
    6 => 'Schmand',
    7 => 'Schokomilch',
    8 => 'Sojamilch',
    9 => 'griechischer Joghurt',
    10 => 'süße Schlagsahne',
  ),
  'Nüsse' => 
  array (
    0 => 'Cashew-Nuss',
    1 => 'Erdnuss',
    2 => 'Erdnussbutter',
    3 => 'Haselnuss',
    4 => 'Makadamia-Nuss',
    5 => 'Mandel',
    6 => 'Nougat',
    7 => 'Nuss',
    8 => 'Nuss-Mix',
    9 => 'Pekanuss',
    10 => 'Pistazie',
    11 => 'Walnuss',
    12 => 'geröstete Nüsse',
  ),
  'Pflanzen' => 
  array (
    0 => 'Agave',
    1 => 'Aloe Vera',
    2 => 'Avocado',
    3 => 'Guave',
    4 => 'Gurke',
    5 => 'Heu',
    6 => 'Hibiskus',
    7 => 'Holunder',
    8 => 'Holunderblüte',
    9 => 'Ingwer',
    10 => 'Marula',
    11 => 'OG Kush',
    12 => 'Orchidee',
    13 => 'Rhabarber',
    14 => 'Waldmeister',
  ),
  'Sonstige' => 
  array (
    0 => 'Butterscotch',
    1 => 'Clementine',
    2 => 'Clementine',
    3 => 'Energydrink',
    4 => 'Erdbeer',
    5 => 'Ernussbutter',
    6 => 'Lychee',
    7 => 'Virginia-Tabak',
    8 => 'Virginia-Tabak',
    9 => 'Vsanille',
  ),
  'Süßigkeiten' => 
  array (
    0 => 'Ahornsirup',
    1 => 'Buttercreme',
    2 => 'Butterscotch Candy',
    3 => 'Candy',
    4 => 'Erdbeerlolli',
    5 => 'Erdbeerschnüre',
    6 => 'Erdnussbutter',
    7 => 'Frucht-Loops',
    8 => 'Grenadine',
    9 => 'Himbeerlolli',
    10 => 'Honig',
    11 => 'Kakao',
    12 => 'Kakaobohne',
    13 => 'Karamell',
    14 => 'Kirschlolli',
    15 => 'Lolli',
    16 => 'Marmelade',
    17 => 'Marshmallow',
    18 => 'Marshmellow',
    19 => 'Marzipan',
    20 => 'Popcorn',
    21 => 'Praline',
    22 => 'Rohrzucker',
    23 => 'Rosine',
    24 => 'Rosinen',
    25 => 'Schokolade',
    26 => 'Süßigkeiten',
    27 => 'Süßwaren',
    28 => 'Tiramisu',
    29 => 'Waldhonig',
    30 => 'Weingummi',
    31 => 'Zuckerguss',
    32 => 'Zuckersirup',
    33 => 'Zuckerwatte',
    34 => 'gebackene Mandeln',
    35 => 'gebrannte Mandeln',
    36 => 'kandierter Apfel',
    37 => 'karamellisierte Früchte',
    38 => 'saures Weingummi',
    39 => 'weiße Schokolade',
  ),
  'Tabak' => 
  array (
    0 => 'American Blend',
    1 => 'Burley-Tabak',
    2 => 'Doppelapfel',
    3 => 'Pfeifentabak',
    4 => 'Rohtabakblätter',
    5 => 'Shisha-Tabak',
    6 => 'Tabak',
    7 => 'Virginia Tabak',
    8 => 'Zigarrentabak',
    9 => 'dunkler Tabak',
    10 => 'süßer Tabak',
  ),
  'Tee & Kaffee' => 
  array (
    0 => 'Café Latte',
    1 => 'Cappuccino',
    2 => 'Ceylon Tee',
    3 => 'Chai Latte',
    4 => 'Earl Grey',
    5 => 'Eistee',
    6 => 'Espresso',
    7 => 'Frappé',
    8 => 'Früchtetee',
    9 => 'Jasmintee',
    10 => 'Kaffee',
    11 => 'Kaffee-Likör',
    12 => 'Matcha',
    13 => 'Milchkaffee',
    14 => 'Minztee',
    15 => 'Mocca',
    16 => 'Orientalischer Minztee',
    17 => 'Tee',
    18 => 'Yuzu-Tee',
    19 => 'grüner Tee',
    20 => 'grüner Zitronentee',
    21 => 'schwarzer Tee',
  ),
  'Trauben' => 
  array (
    0 => 'Traube',
    1 => 'Trauben-Mix',
    2 => 'Weintraube',
    3 => 'dunkle Traube',
    4 => 'helle Traube',
    5 => 'rote Traube',
    6 => 'schwarze Traube',
  ),
  'Zitrusfrüchte' => 
  array (
    0 => 'Bergamotte',
    1 => 'Blutorange',
    2 => 'Grapefruit',
    3 => 'Limette',
    4 => 'Limone',
    5 => 'Mandarine',
    6 => 'Orange',
    7 => 'Orangenblüte',
    8 => 'Zitrone',
    9 => 'Zitronengras',
    10 => 'Zitrusfrüchte',
  ),
  'exotische Früchte' => 
  array (
    0 => 'Dattel',
    1 => 'Drachenfrucht',
    2 => 'Feige',
    3 => 'Granatapfel',
    4 => 'Kaktus',
    5 => 'Kaktusfeige',
    6 => 'Kiwi',
    7 => 'Kokos',
    8 => 'Kokosmilch',
    9 => 'Litschi',
    10 => 'Mango',
    11 => 'Maracuja',
    12 => 'Papaya',
    13 => 'Passionsfrucht',
    14 => 'Sternfrucht',
    15 => 'Tropical Mix',
    16 => 'exotische Früchte',
    17 => 'karibische Früchte',
    18 => 'tropische Früchte',
  ),
);