<?php

return [
    'name_prepare' => [
        'preg_replace' => [
            '~(The Bros -)~'                        => 'The Bro\'s -',
            '~(Superfruit -) (Mulberry)~'           => '$1 Aroma $2',
            '~\s+~'                                 => ' ',
            '~(- )+~'                               => '$1',
            '~ ,~'                                  => ',',
            '~, -~'                                 => '-',
            '~ - ?$~'                               => '',
            '~Voopoo~'                              => 'VooPoo',
            '~10ml\/ml~'                            => '10ml',
            '~0ml\/ml~'                             => '0mg/ml',
            '~(\d+)m~'                              => '$1 m',
            '~(0 mg)$~'                             => '$1/ml',
            '~(\d) mAH~'                            => '$1 mAh',
            '~(\d mg)[^\/]~'                        => '$1/ml',
            '~Sherbert~'                            => 'Sherbet',
            '~Americas~'                            => 'America\'s',
            '~America´s~'                           => 'America\'s',
            '~AsMODus~'                             => 'asMODus',
            '~Asmodus~'                             => 'asMODus',
            '~(Original Q) PRO~'                    => '$1 Pro',
            '~(Zeus X) (2)~'                        => '$1$2',
            '~(Amnis 2) mit GS Drive~'              => '$1',
            '~Hellvape~'                            => 'HellVape',
            '~(Rabbit) V2 (RDA)~'                   => '$1 $2 v2',
            '~CoilART~'                             => 'CoilArt',
            '~(Heads )+~'                           => '$1',
            '~(Head )+~'                            => '$1',
            '~(Ni80)\(~'                            => '$1 (',
            '~(10er Packung)en~'                    => '$1',
            '~[^\(](3 Stück pro Packung\))~'        => ' ($1',
            '~(Aromamizer Plus) Bubble (Glastank)~' => '$1 $2',
            '~(Merlin Nano MTL) (Glastank)~'        => '$1 RTA $2',
            '~(V1.5)~'                              => 'v1.5',
            '~(JVIC)\d~'                            => '$1',
            '~((HW1)|(HW2)) (Heads)~'               => 'HW1/HW2 $4',
            '~artikblau~'                           => 'arktikblau',
            '~(K2 & K3.*) \(\d+ (St. pro Pack\))~'  => '$1 (5 $2',
            '~Freemax~'                             => 'FreeMax',
            '~(Skynet) (Pro )?Sub-Ohm ~'            => '$1 $2',
            '~(Aegis X) (\d+ Watt) (mit Cerberus)~' => '$1 $3',
            '~(Lunar)~'                             => '$1 45 Watt',
            '~(Horizon)T(ech)~'                     => '$1t$2',
            '~(Tauren X) (Mesh)~'                   => '$1 Pod $2',
            // separator different from '-'
            '~(SX-RSA Esea) DIY~'                   => '$1',
            '~Bros Frost~'                          => 'Bro\'s Frost',
            '~EXCEED~'                              => 'Exceed',
            '~–~'                                   => '-',
        ],
    ],

    'name_cleanup'              => [
        'preg_replace' => [
            '~\s+~'                                        => ' ',
            '~(- )+~'                                      => '$1',
            '~ ,~'                                         => ',',
            '~-,~'                                         => '-',
            '~, -~'                                        => '-',
            '~ - ?$~'                                      => '',
            '~ $~'                                         => '',
            '~^ ~'                                         => '',
            '~(RDTA)+~'                                    => '$1',
            '~-V12~'                                       => '- V12',
            '~(Virginas) (Best)~'                          => 'Virginia\'s $2',
            '~-(Ersatz)~'                                  => '- $1',
            '~( mit Maat -)~'                              => '',
            '~( mit Melo 5 -)~'                            => '',
            '~-(E-Zigarette)~'                             => '- $1',
            '~-(Netzstecker)~'                             => '- $1',
            '~-(Mundstücke)~'                              => '- $1',
            '~- (mit Ello)~'                               => '$1',
            '~-(V8-)~'                                     => '- $1',
            '~(10er Packung)en~'                           => '$1',
            '~-(Anniversary)~'                             => '- $1',
            '~(GS) -(Basal)~'                              => '$1 $2',
            '~-(Glastank)~'                                => '- $1',
            '~-(Clearomizer)~'                             => '- $1',
            '~(Head) - Head~'                              => '$1',
            '~- (Head)~'                                   => '$1',
            '~^(\p{L}*) (Head)~'                           => '$1 - $2',
            '~(JustFog) ([^\-])~'                          => '$1 - $2',
            '~ XXer Packung~'                              => '',
            '~(Revvo) - (Boost)~'                          => '$1 $2',
            '~(EX) --M (Mesh)~'                            => '$1-M $2',
            '~(Tasche) X -L~'                              => '$1 XL',
            '~(VooPoo.*)Pnp~'                              => '$1PnP',
            '~(E-Zigarette \(Set\)) e$~'                   => '$1',
            '~(iStick Pico) - (Resin mit Melo 4) - (D22)~' => '$1 $2 $3 -',
            '~(mit TFV8 Baby) - (V2)~'                     => '$1 $2 -',
            '~(Leerflasche), (\d+ ml)~'                    => '$1 - $2',
            '~(Air) - (Plus)~'                             => '$1 $2 -',
            '~(Melo 3) - (Mini)~'                          => '$1 $2 -',
            '~(TFV12) - P-~'                               => '$1-P -',
            '~(Glaz RTA) - (V2)~'                          => '$1 $2 -',
            '~(Legend) - (mit Alpha)~'                     => '$1 $2',
            '~((V200)|(V80)) - (mit Amor NSE)~'            => '$1 $4',
            '~(Lite) - (mit GS Air 3)~'                    => '$1 $2',
            '~(Probierbox - Liquid) - 10 ml~'              => '$1',
            '~(Nikotinsalz-Liquid) (\d+ mg/ml)~'           => '$1 - $2',
            '~(VG/PG: 80/20), (\d+ ml), (\d+ mg/ml)~'      => '$1 - $2 - $3',
            '~(Squonker Flasche), (\d+ ml)~'               => '$1 - $2',
            '~(Star Spangled), 9 mg/ml~'                   => '$1',
            '~(Ultem Tank), (5 ml)~'                       => '$1 - $2',
            '~(Akkuträger) - Akkuträger~'                  => '$1',
            '~Smok TFV8 -~'                                => 'SMOK - TFV8',
            '~(Aegis X) - (mit Cerberus)~'                 => '$1 $2',
            '~(Aegis X) - (mit Zeus)~'                     => '$1 $2',
            '~(Solo) - (mit Tengu)~'                       => '$1 $2 -',
            '~(Solo) - (mit Cerberus)~'                    => '$1 $2',
            '~(Morph) - (Akkuträger)~'                     => '$1 219 - $2',
            '~Tank (BF Mesh Head)~'                        => '$1',
            '~- (Mac Advanced)~'                           => '$1 -',
            '~(TF) -(Tank Stick)~'                         => '$1 $2',
            '~80W (E-Zigarette)~'                          => '$1',
            '~(Cygnet) - (Revvo)~'                         => '$1 $2',
            '~(1,4 Ohm) (Pod)~'                            => '$2, $1',
            '~(-)+~'                                       => '$1',
            '~- pro (Pod)~'                                => 'Pro - $1',
            '~(Liquidflasche) (5 Stück pro Packung).*~'    => '$1 ($2)',
            '~(SX Auto) - Liquidt(ank)~'                   => '$1 - T$2',
            '~(Pink Soda) Liquid~'                         => '$1',
            '~(Blue Slush) Liquid~'                        => '$1',
            '~(Marsupod) - mit~'                           => '$1 - Pod -',
            '~Subohm (Verdampfer)~'                        => '$1',
            '~Subohm (E-Zigarette)~'                       => '$1',
            '~(iSub -)(PLEX)~'                             => '$1 $2',
            '~(eGrip) - (Mini)~'                           => '$1 $2', // does not work with rules below, reason unknown
            '~(Nord) -( 2 -)~'                             => '$1 $2', // does not work with rules below, reason unknown
            '~(Nord) -( X -)~'                             => '$1 $2', // does not work with rules below, reason unknown
            '~(Nord) -( 4 -)~'                             => '$1 $2', // does not work with rules below, reason unknown
            '~- -(Verdampfer)~'                            => '- $1',
            '~(SC - .*) - by SC$~'                         => '$1',
            '~(.*)(3in1 Aroma.*)15( ml)~'                  => '$1$2 45$3',
            '~(Salt Stick) (E-Zigarette)~'                 => '$1 - $2',
            '~(Ares Pod) - \(~'                            => '$1 (',
            '~(NRG) - (PE) (Glastank)~'                    => '$1-$2 - $3',
            '~(NRG) - (PE) (Verdampfer)~'                  => '$1-$2 - $3',
            '~(E-Zigarette)n (Bundle) Set~'                => '$1 ($2)',
            '~(Zenith -) -(Head)~'                         => '$1 $2',
            '~(Crown Pod) - (\()~'                         => '$1 $2',
            //            '~( Pod) - (E-Zigarette)~'                     => ' -$1 $2',
            '~(E-Zigarette \(Bundle\)).*~'                 => '$1',
            '~(Nord) - (Pod)~'                             => '$1 $2',
            '~(Kfeng) - (Verdampfer)~'                     => '$1 Mark - $2',
            '~(vPipe Mini) - E-Zigarette~'                 => '$1 - E-Pfeife',
            '~(Care Edition) (E-Zigarette)~'               => '$1 - $2',
            '~InnoCigs (Caliburn)~'                        => 'Uwell - $1',
            '~(KA1) (- 0,6 Ohm) (Coil)~'                   => '$1 $3 $2',
            '~(Ares 2 D22)(.*)(Limited Edition)~'          => '$1 $3 $2',
            '~(1 Pod) - (P Series Head)~'                  => '$1 mit $2',
            '~(Pro - 2 Pod)~'                              => '$1s',
            '~(P) (Series)~'                               => '$1-$2',
            '~(E-Zigarette) LE$~'                          => '$1 - Limited Edition',
            '~(Aegis Boost) - LE Bonus (E-Zigarette)~'     => '$1 - Limited Bonus Edition - $2',
            '~(B) (Series Head) - (\d,\d Ohm oder) -~'     => '$1-$2 - $3',
            '~(SMOK -) (V9 - 0,15)~'                       => '$1 TF$2',
            '~(Lunar) - Akkuträger - 45 Watt (Lemon.*)~'   => '$1 $2',
            '~(NRG) (-S) (Verdampfer)~'                    => '$1$2 - $3',
            '~(Argus) - (X) - (E-Zigarette)~'              => '$1 $2 - $3',
            '~(Vaporesso) - (Gen) -(S)~'                   => '$1 - $2 $3',
            '~(.*Easy 4.*) - 9 mg/ml~'                     => '$1',
            '~(Verdampfer) (Anniversary Edition)~'         => '$1 - $2',
            '~(Metal Edition) (Verdampfer)~'               => '$2 - $1',
            '~(Argus) - (GT)~'                             => '$1 $2',
            '~Headhot -~'                                  => 'Headshot -',
            '~(Stick) - (G15)~'                            => '$1 $2 -',
            '~(Cartridge) mit,~'                           => '$1,',
            '~VStick pro~'                                 => 'VStick Pro',
            '~(GeekVape -) N S (Head)~'                    => '$1 NS $2',
        ],
    ],


    // NOTE: Since we use the new API property PARENT_NAME now, we do not have
    // to replace options in product names any longer, so this setting is not
    // used any more.
    'product_name_option_fixes' => [
        // option text                                  // option found in name
        'prisma-blau'                                => 'blau-prisma',
        'prisma-chrom'                               => 'chrom-prisma',
        'prisma-gold'                                => 'gold-prisma',
        'prisma-regenbogen'                          => 'regenbogen-prisma',
        'prisma-rot'                                 => 'rot-prisma',
        'prisma-gunmetal'                            => 'gunmetal-prisma',
        'schwarz-rot'                                =>
            [
                'rot-schwarz',
                'schwarz rot',
            ],
        'Jeans'                                      => 'jeans',
        'Jade'                                       => 'jade',
        'NI80'                                       => 'Ni80',
        '0,4 Ohm'                                    => '0,4',
        '2,0 ml'                                     => ['2 ml', '2ml'],
        '2 ml'                                       => '2,0 ml',
        '3,5 ml'                                     => [
            '3.5 ml',
            '3,5ml',
        ],
        '4,5 ml'                                     => '4,5ml',
        '4 ml'                                       => '4ml',
        '15ml'                                       => '15 ml',
        '10ml'                                       => '10 ml',
        '20ml'                                       => '20 ml',
        '18ml'                                       => '18 ml',
        '5ml'                                        => '5 ml',
        '28ml'                                       => '28 ml',
        'Typ A'                                      => 'Typ-A',
        'Typ B'                                      => 'Typ-B',
        '3,0ml'                                      => '3 ml',
        '4,2ml'                                      => '4,2 ml',
        'V2-M'                                       => 'M',
        'V2-XL'                                      => 'XL',
        'Coral'                                      => 'coral',
        'matt-schwarz'                               => 'matt schwarz',
        'schwarz-weiß'                               => 'schwarz-weiss',
        'schwarz-weiss-resin'                        => 'schwarz-weiß-resin',
        'camouflage-grau'                            => 'camouflage grau',
        'Flasche schwarz transparent + schwarze Cap' => 'schwarz-transparent mit schwarzer Cap',
        'Flasche schwarz + schwarze Cap'             => 'schwarz mit schwarzer Cap',
        'Flasche transparent + schwarze Cap'         => 'mit schwarzer Cap',
        'Flasche weiss + weisse Cap'                 => 'weiss mit weisser Cap',
        'Flasche transparent + transparente Cap'     => '', // does not occur in name
        '1er Packung'                                => '', // does not occur in name
        'weiß'                                       => 'weiss',
        '50PG / 50VG'                                => [
            '50PG/50VG',
            '50VG/50PG',
            '50VG / 50PG',
        ],
        '28 GA'                                      => '28GA',
        '26 GA'                                      => '26GA',
        '24 GA'                                      => '24GA',
        '22 GA'                                      => '22GA',
        '24 GA*2+32 GA'                              => '24GA*2+32GA',
        '28 GA*2+32 GA'                              => '28GA*2+32GA',
        '26 GA+32 GA'                                => '26GA+32GA',
        'ProC1 0,4 Ohm'                              => '0,4 Ohm',
        'ProC1-S 0,25 Ohm'                           => '0,25 Ohm',
        'ProC2 0,15 Ohm'                             => '0,15 Ohm',
        'ProC3 0,2 Ohm'                              => '0,2 Ohm',
        'ProC4 0,15 Ohm'                             => '0,15 Ohm',
        'Edelstahl (5er Pack)'                       => 'Edelstahl (5 St. pro Pack)',
        'Kunststoff (10er Pack)'                     => 'KunstStoff (10 St. pro Pack),',
    ],

    // By default occurances of an option name in the article name are removed.
    // If an option replacement is defined here for the particular option, the
    // occurance of the option name gets replaced with the string defined here.

    // NOTE: Since we use the new API property PARENT_NAME now, we do not have
    // to replace options in product names any longer, so this setting is not
    // used any more.
    'option_replacements'       => [
        'Postless Deck'    => 'Deck',
        'Series Deck'      => 'Deck',
        'Single Coil Deck' => 'Deck',
        'Velocity Deck'    => 'Deck',
    ],

    'products_without_brand' => [
        'Keramik Multifunktionspinzette Tweezer V8',
        'Tasche mit Schulterriemen',
        'Tasche mit Griff',
        'Multifunktionstasche',
        'Keramik Multifunktionspinzette Tweezer V8 schwarz',
        'Celluloid Mundstücke  (5 Stück pro Packung)',
        'Edelstahl Mundstücke S1Z (5 Stück pro Packung)',
        'Kunststoff Mundstücke  (5 Stück pro Packung)',
    ],

    'product_names_direct' => [
    ],

    'product_name_replacements' => [
        'preg_replace' => [
            '~(PnP) (0,6 Ohm) (Coil)~'                                                   => '$1 $3 - $2',
            '~(SKRR) (S)~'                                                               => '$1-$2',
            '~Buch - Die E-Zigarette~'                                                   => 'Die E-Zigarette - Fakten und Mythen - Prof. Dr. Bernd Mayer',
            '~(Wolf) Tank (Mini)~'                                                       => '$1 $2',
            '~(Aegis Squonk)er~'                                                         => '$1',
            '~(1,5 Ohm) (Cartridge)~'                                                    => '$2, $1',
            '~(Elli)´s~'                                                                 => 'Elli\'s',
            '~(Roofy)`s~'                                                                => 'Roofy\'s',
            '~Die4Brüder Bubble~'                                                        => 'Die 4 Brüder',
            '~(Manta) (Glastank)~'                                                       => '$1 RTA $2',
            '~(Manta) Bubble (Glastank)~'                                                => '$1 RTA $2',
            '~(Coilology.*(4|7) in 1) (Set)~'                                            => '$1 Coil-$3',
            '~Aster$~'                                                                   => 'Aster 75 Watt',
            '~(Dark Mesh Bubble) Ersatzglas~'                                            => '$1 Glastank',
            '~(VM 25) Ersatzglas~'                                                       => '$1 Glastank',
            '~(Nautilus X Mundstück)e~'                                                  => '$1',
            '~80er (Mesh Wire) (1,5 m)~'                                                 => '$1 - $2',
            '~100er (Mesh Wire) (1,5 m)~'                                                => '$1 - $2',
            '~150er (Mesh Wire) (1,5 m)~'                                                => '$1 - $2',
            '~(D19.*O-Ringe)~'                                                           => 'Exceed $1',
            '~(D22.*O-Ringe)~'                                                           => 'Exceed $1',
            '~(Exceed) Box~'                                                             => 'Exceed D22',
            '~((1 Liter)|(\d+ ml)) (Basis)~'                                             => '$4 - $1',
            '~1 Liter~'                                                                  => '1.000 ml',
            '~E-Zigaretten (Liquid)~'                                                    => '- $1',
            '~(Nikotinsalz) (Liquid)~'                                                   => '- $1-$2',
            '~-( - Liquid)~'                                                             => '$1',
            '~(Liquid) für E-Zigaretten~'                                                => '$1',
            '~(Shortz.*) - (0 mg/ml)~'                                                   => '$1 - 50 ml, $2',
            '~(Koncept XIX.*) (0 mg/ml)~'                                                => '$1 - 50 ml, $2',
            '~EZ.WATT~'                                                                  => 'EZ.Watt',
            '~-(\d+) ml~'                                                                => '- $1 ml',
            '~ (\d+) mAh~'                                                               => ' - $1 mAh',
            '~(\d{2})VG */ *(\d{2})PG~'                                                  => '- VG/PG: $1/$2,',
            '~(\d{2})PG */ *(\d{2})VG~'                                                  => '- VG/PG: $2/$1,',
            '~(\d)(\d{3}) mAh~'                                                          => '$1.$2 mAh',
            '~([^,\-]) (\d) m$~'                                                         => '$1 - $2 m',
            '~([^,\-]) (\d,\d+) Ohm~'                                                    => '$1 - $2 Ohm',
            '~, (\d,\d+ Ohm) Heads?~'                                                    => ' Heads, $1',
            '~ (\d+) Watt~'                                                              => ' - $1 Watt',
            '~ml - (\d)~'                                                                => 'ml, $1',
            '~(Engine 2) Ersatzglas~'                                                    => '$1 RTA Glastank',
            '~(KFB 2 AIO) Ersatzglas~'                                                   => '$1 Glastank',
            '~([^,\-]) (\d(,\d+)?) ?ml~'                                                 => '$1, $2 ml',
            '~(\d+)ML(.*Leerflasche)~'                                                   => '$2, $1 ml',
            '~([^,\-]) ((\d+)(,\d+)? ml)$~'                                              => '$1 - $2',
            '~([^,\-]) (\d+) mg\/ml$~'                                                   => '$1 - $2 mg/ml',
            '~(0 mg/ml) - (\d+ ml)~'                                                     => '$2, $1',
            '~(\d+ ml) - (\d+ mg/ml)~'                                                   => '$1, $2',
            '~(\d+ mg/ml),? (\d+ ml)~'                                                   => '$2, $1',
            '~([^,\-]) (\d+ ml, \d+ mg/ml)~'                                             => '$1 - $2',
            '~(Treib.*100 ml$)~'                                                         => '$1, 0 mg/ml',
            '~(Brunhilde MTL) (Edel)~'                                                   => '$1 RTA $2',
            '~(Brunhilde MTL RTA), (\d ml) (.*)~'                                        => '$1 $3 - $2',
            '~(Brunhilde) (RTA) (Edel)~'                                                 => '$1 Top Coiler $2 $3',
            '~(Brunhilde) (RTA), (\d ml) (.*)~'                                          => '$1 Top Coiler $2 $4 - $3',
            '~(Bad Candy Liquids) (- .*)(- 20 ml)~'                                      => '$1 $2 - Aroma $3',
            '~(Crazy Lab XL) - (Garden)(.*)~'                                            => '$1 - Aroma $2 $3',
            // 'Aroma' missing in InnoCigs name
            '~(Dreamlike -.*) pure (.*)~'                                                => '$1 Pure $2',
            // pure -> Pure
            '~(Vapanion)(.*)(- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $2 $3 $5',
            // non standard
            '~(Ezigaro Pro - Quick Eazy) (Aroma)(.*)(- \d+(,\d+)? ml)~'                  => '$1 - $3 - $2 $4',
            // non standard
            '~(Gods of Olymp) - (.*) (- \d+(,\d+)? ml)~'                                 => '$1 - $2 - Aroma $3',
            // non standard
            '~(Strapped Sodas) - (.*) (Aroma) (- \d+(,\d+)? ml)~'                        => '$1 - $2 - $3 $4',
            // non standard
            '~(Vapeozon - Läuft!) (Aroma)(.*)(- \d+(,\d+)? ml)~'                         => '$1 - $3 - $2 $4',

            '~(Bamberger Dampferlädla - Bassd Schoo) (- Aroma)(.*)(- \d+(,\d+)? ml)~'    => '$1 - $3 $2 $4',
            '~(Bamberger Dampferlädla - Götter) (- Aroma)(.*)(- \d+(,\d+)? ml)~'         => '$1 - $3 $2 $4',
            '~(Bamberger Dampferlädla - Lädlas Chabeso) (- Aroma)(.*)(- \d+(,\d+)? ml)~' => '$1 - $3 $2 $4',
            '~(Classic Sauce by Classic Dampf) (- Aroma)(.*)(- \d+(,\d+)? ml)~'          => '$1 - $3 $2 $4',
            '~(Classic Dampf) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                           => '$1 - $3 $2 $4',
            '~(Dampforia) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Noon) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                    => '$1 - $3 $2 $4',
            '~(Fana Vape - M2Like) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                      => '$1 - $3 $2 $4',
            '~(Shadow Burner) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                           => '$1 - $3 $2 $4',
            '~(Philgood´s Liquidhimmel) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                 => '$1 - $3 $2 $4',
            '~(Happy Club Mix) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                          => '$1 - $3 $2 $4',
            '~(Flavour Manufaktur) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                      => '$1 - $3 $2 $4',
            '~(mammoth) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                 => '$1 - $3 $2 $4',
            '~(The Vaping Flavour) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                      => '$1 - $3 $2 $4',
            '~(Day n Night) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(Omerta Liquids - Bisha) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                  => '$1 - $3 $2 $4',
            '~(Omerta Liquids - La Famiglia) (- Aroma)(.*)(- \d+(,\d+)? ml)~'            => '$1 - $3 $2 $4',
            '~(Omerta Liquids - Carat) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                  => '$1 - $3 $2 $4',
            '~(Omerta Liquids - The Dons) (- Aroma)(.*)(- \d+(,\d+)? ml)~'               => '$1 - $3 $2 $4',
            '~(Omerta Liquids - Gusto) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                  => '$1 - $3 $2 $4',
            '~(Fiasco Brew) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(Bad Candy) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Arcanum - Respawn) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                       => '$1 - $3 $2 $4',
            '~(Headshot) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                => '$1 - $3 $2 $4',
            '~(Noble Psycho) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(VapingGamerz) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(YO-YO) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                   => '$1 - $3 $2 $4',
            '~(Dreamlike) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(#Sukka Watte) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(Gangsterz) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Crazy Lab XL) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(Aroma Syndikat) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                          => '$1 - $3 $2 $4',
            '~(Dr. M) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                   => '$1 - $3 $2 $4',
            '~(Primeval) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                => '$1 - $3 $2 $4',
            '~(VapeTrip) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                => '$1 - $3 $2 $4',
            '~(After Meal) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(Frühstücksclub) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                          => '$1 - $3 $2 $4',
            '~(Mythos by Bushido) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                       => '$1 - $3 $2 $4',
            '~(Frosty Affairs) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                          => '$1 - $3 $2 $4',
            '~(Rocket Girl) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(Patronus) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                => '$1 - $3 $2 $4',
            '~(Die 4 Brüder) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(SteamersClub) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(#Schmeckt) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(#Kaktus) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                 => '$1 - $3 $2 $4',
            '~(MAXIMA) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                  => '$1 - $3 $2 $4',
            '~(Firestorm) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Azadian) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                 => '$1 - $3 $2 $4',
            '~(The Bro\'s) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(Drei Könige) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(The Bro\'s - Konfitüre) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                  => '$1 - $3 $2 $4',
            '~(KTS) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                     => '$1 - $3 $2 $4',
            '~(KTS - Superfruit) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                        => '$1 - $3 $2 $4',
            '~(Bamberger Dampferlädla) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                  => '$1 - $3 $2 $4',
            '~(Bamberger Dampferlädla - Hüttenzauber) (- Aroma)(.*)(- \d+(,\d+)? ml)~'   => '$1 - $3 $2 $4',
            '~(Dr. Fog - Shisha) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                        => '$1 - $3 $2 $4',
            '~(Mr. Blitz) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Bro\'s Frost) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(Dog House) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Detonation Drip) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                         => '$1 - $3 $2 $4',
            '~(Enfer) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                   => '$1 - $3 $2 $4',
            '~(Elf-Liquid) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(Vaping Gorilla) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                          => '$1 - $3 $2 $4',
            '~(Vaping Gorilla - Monkeys) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                => '$1 - $3 $2 $4',
            '~(Dash Liquids) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(Dr. Fog - Donuts) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                        => '$1 - $3 $2 $4',
            '~(Dr. Fog - All Stars) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                     => '$1 - $3 $2 $4',
            '~(Alphavirus) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(Bonbon Onkel) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(MakeYourLiquid) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                          => '$1 - $3 $2 $4',
            '~(Galaxy) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                  => '$1 - $3 $2 $4',
            '~(Kack Fresh) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(Samurai Maza) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(Samurai) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                 => '$1 - $3 $2 $4',
            '~(MaZa) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                    => '$1 - $3 $2 $4',
            '~(Gedankenlos) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(Tom Klarks) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(WeFog - Blizzard) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                        => '$1 - $3 $2 $4',
            '~(Evergreen) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Refresh Gazoz) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                           => '$1 - $3 $2 $4',
            '~(Psycho Bunny) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(Vape Sphere) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(Kaffeeklatsch) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                           => '$1 - $3 $2 $4',
            '~(510CloudPark) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                            => '$1 - $3 $2 $4',
            '~(510CloudPark - BenchmarX) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                => '$1 - $3 $2 $4',
            '~(hookahLove - hookahSqueeze) (- Aroma)(.*)(- \d+(,\d+)? ml)~'              => '$1 - $3 $2 $4',
            '~(Kirschlolli) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                             => '$1 - $3 $2 $4',
            '~(Oceans) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                  => '$1 - $3 $2 $4',
            '~(Pyromania) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                               => '$1 - $3 $2 $4',
            '~(Pyromania.*)3in1 Bundle(.*)(Aroma)(.*)~'                                  => '$1Fuze, Destruction, Blast$2 3in1 $3 Bundle$4',
            '~(Ultrabio) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                => '$1 - $3 $2 $4',
            '~(Ultrabio) (Singular) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                     => '$1 - $2 - $4 $3 $5',
            '~(Cream Team) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                              => '$1 - $3 $2 $4',
            '~(Joker Flavour) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                           => '$1 - $3 $2 $4',
            '~(Erste Sahne - Football Serie) (- Aroma)(.*)(- \d+(,\d+)? ml)~'            => '$1 - $3 $2 $4',
            '~(Erste Sahne - Gin Serie) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                 => '$1 - $3 $2 $4',
            '~(The Custard Shoppe) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                      => '$1 - $3 $2 $4',
            '~(hilda.) (- Aroma)(.*)(- \d+(,\d+)? ml)~'                                  => '$1 - $3 $2 $4',
            '~(Elli\'s Aromen) (- Aroma)(.*)(- \d+ ml)~'                                 => '$1 - $3 $2 $4',
            '~(Yankee Juice.*) (- Aroma)(.*)(- \d+ ml)~'                                 => '$1 - $3 $2 $4',
            '~(WSY) (- Aroma)(.*)(- \d+ ml)~'                                            => '$1 - $3 $2 $4',
            '~(Dr. Kero) (- Aroma)(.*)(- \d+ ml)~'                                       => '$1 - $3 $2 $4',
            '~(Dr. Vapes - Pink Series) (- Aroma)(.*)(- \d+ ml)~'                        => '$1 - $3 $2 $4',
            '~(Dr. Vapes) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(Dampfdidas) (- Aroma)(.*)(- \d+ ml)~'                                     => '$1 - $3 $2 $4',
            '~(Ant) (- Aroma)(.*)(- \d+ ml)~'                                            => '$1 - $3 $2 $4',
            '~(GangGang) (- Aroma)(.*)(- \d+ ml)~'                                       => '$1 - $3 $2 $4',
            '~(Archangel) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(5Elements) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(Frankonia) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(Demons) (- Aroma)(.*)(- \d+ ml)~'                                         => '$1 - $3 $2 $4',
            '~(Kaori) (- Aroma)(.*)(- \d+ ml)~'                                          => '$1 - $3 $2 $4',
            '~(Captain Dolly) (- Aroma)(.*)(- \d+ ml)~'                                  => '$1 - $3 $2 $4',
            '~(Roofy\'s) (- Aroma)(.*)(- \d+ ml)~'                                       => '$1 - $3 $2 $4',
            '~(Vape Rebelz) (- Aroma)(.*)(- \d+ ml)~'                                    => '$1 - $3 $2 $4',
            '~(Mùa) (- Aroma)(.*)(- \d+ ml)~'                                            => '$1 - $3 $2 $4',
            '~(Arschkalt) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(Yankee Juice - Sweets) (- Aroma)(.*)(- \d+ ml)~'                          => '$1 - $3 $2 $4',
            '~(Dutty Juice) (- Aroma)(.*)(- \d+ ml)~'                                    => '$1 - $3 $2 $4',
            '~(Flavour Trade) (- Aroma)(.*)(- \d+ ml)~'                                  => '$1 - $3 $2 $4',
            '~(Foozy Juice) (- Aroma)(.*)(- \d+ ml)~'                                    => '$1 - $3 $2 $4',
            '~(TNYVPS) (- Aroma)(.*)(- \d+ ml)~'                                         => '$1 - $3 $2 $4',
            '~(Mr\. Niks) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(7 Todsünden) (- Aroma)(.*)(- \d+ ml)~'                                    => '$1 - $3 $2 $4',
            '~(Twenty Eight Monkeys) (- Aroma)(.*)(- \d+ ml)~'                           => '$1 - $3 $2 $4',
            '~(Mule Fuel) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(Shark Attack) (- Aroma)(.*)(- \d+ ml)~'                                   => '$1 - $3 $2 $4',
            '~(Military) (- Aroma)(.*)(- \d+ ml)~'                                       => '$1 - $3 $2 $4',
            '~(Tobacco Time) (- Aroma)(.*)(- \d+ ml)~'                                   => '$1 - $3 $2 $4',
            '~(Bozz Liquids) (- Aroma)(.*)(- \d+ ml)~'                                   => '$1 - $3 $2 $4',
            '~(Vapors Line) (- Aroma)(.*)(- \d+ ml)~'                                    => '$1 - $3 $2 $4',
            '~(VapeHansa) (- Aroma)(.*) (- \d+ ml)~'                                     => '$1 - $3 $2 $4',
            '~(Flavorist) (- Aroma)(.*)(- \d+ ml)~'                                      => '$1 - $3 $2 $4',
            '~(VapeTastic -) (Aroma) - (.*)(- \d+ ml)~'                                  => '$1 $3 - $2 $4',
            '~(Aroma Blood Sukka$)~'                                                     => '$1 - 30 ml',
            '~(Vampire Vape) - (Aroma)(.*)(- \d+ ml)~'                                   => '$1 - $3 - $2 $4',
            '~(Twisted) - (Peng Juice) (Aroma)(.*)(- \d+ ml)~'                           => '$1 - $2 $4 - $3 $5',
            '~Okolom~'                                                                   => 'Lomoko',
            '~Vape( -)?( Aroma)(.*)(- \d+ ml)~'                                          => 'Vape - $3 -$2 $4',
            '~(Vampire Vape) ([^\-])~'                                                   => '$1 - $2',
            '~(VLADS VG) Liquid (-.*)~'                                                  => '$1 $2 - Liquid',
            '~(Bull) (- Aroma)(.*)(- \d+ ml)~'                                           => '$1 - $3 $2 $4',
            '~(Remedy) - Remedy~'                                                        => '$1',
            '~(5 Stars Peine.*) (- Aroma)(.*)(-|,)?( \d+ ml)~'                           => '$1 - $3 $2 -$5',
            '~(5 Stars Peine) (- .* Edition)~'                                           => '$1 - $2 -',
            '~,( - Aroma - 9 ml)~'                                                       => '$1',
            '~(SC -) (Aroma) (.*)~'                                                      => '$1 $3 - $2',
            '~- Twisted (Aroma) - (.*)(- \d+ ml)~'                                       => '- $2 - $1 $3',
            '~(VC4) 4~'                                                                  => '$1',
            '~(MC1) - 1 Schacht~'                                                        => '$1',
            '~(I VG - )(Aroma) (.*)(- \d+ ml)~'                                          => '$1 $3 - $2 $4',
            '~(PlusSolt).*(\d\d ml) (Nikotinsalz).*(Shot) (- 18 mg/ml)~'                 => '$1 - $3-$4 - $2 $5',
            '~(Aromamizer Plus)~'                                                        => '$1 RDTA',
            '~(Twisted -) (Cryostasis|Road Trip) (Aroma)(.*)(- \d+ ml)~'                 => '$1 $2 $4 - $3 $5',
            '~((SC)|(InnoCigs))(.*)((- )?(Liquid)|(Aroma))$~'                            => '$1$4$6$5 - 10 ml',
            '~(InnoCigs)(.*) Aroma (- Liquid)~'                                          => '$1$2 $3',
            '~(SC) (- Vape Base)(.*-)(.*)~'                                              => '$1 $3 - $4',
            '~^(Erste Sahne) ([^\-])~'                                                   => '$1 - $2',
            '~(Cleaner) (Reinigung)~'                                                    => '$1 - $2',
            '~(John Smith.*) (- \d+ ml)~'                                                => '$1 - Aroma $2',
            '~Heads~'                                                                    => 'Head',
            '~(BVC) Clearomizer (Head)~'                                                 => '$1 $2',
            '~((Vape)|(SC)) - (\d+ ml) (Shot) - (.*), (.*)~'                             => '$1 - Nikotin-$5 - $6, $4, $7',
            '~(Solt) (\d+ ml) (.*) - (.*), (.*)~'                                        => '$1 - $3 - $4, $2, $5',
            '~(Happy Liquid)(.*)~'                                                       => '$1$2 - Liquid - 10 ml',
            '~(PlusSolt) (10 ml) (Nikotinsalz) (Shot)  - (\d+ mg/ml)~'                   => '$1 $3-$4 - $2, $5',
            '~(Crown 3 Parallel) ((SUS316)|(Kanthal)) (Head)~'                           => '$1 $5',
            '~(.*) (Mignon)(.*) (- .*)~'                                                 => '$1 $2 $3 - Akkuzelle $4',
            '~([^\-]) (\d.\d+) (mAh)~'                                                   => '$1 - $2 $3',
            '~(Liquid) -$~'                                                              => '$1',
            '~(Liquid)$~'                                                                => '$1 - 10 ml',
            '~(Illusions - Beyond Series.*50 ml)~'                                       => '$1, 0 mg/ml',
            '~(\d+(\.\d+)? ml, 0 mg/ml)$~'                                               => '- Shake & Vape - $1',
            '~(Insane.*) (- 100 ml)~'                                                    => '$1 - Shake & Vape $2',
            '~(Chicken Shop.*) (- 0 mg/ml)~'                                             => '$1 - Shake & Vape $2',
            '~(Skull Plus.*) - 0 mg/ml~'                                                 => '$1 - Shake & Vape - 100 ml, 0 mg/ml',
            '~(Koncept XIX.*) - (50 ml)~'                                                => '$1 - Shake & Vape - 50 ml, 0 mg/ml',
            '~(Disco Juice.*) (- 0 mg/ml)~'                                              => '$1 - Shake & Vape $2',
            '~(Dr\. Frost.*) (- 0 mg/ml)~'                                               => '$1 - Shake & Vape $2',
            '~(Basis -) - Shake \& Vape -~'                                              => '$1',
            '~([^,\-]) (\d m)~'                                                          => '$1, $2',
            '~Clearomizer (Head)~'                                                       => '$1',
            '~Clearomizer Ständer~'                                                      => 'Verdampferständer',
            '~(Aspire) (INR) (\d{5})er - (\d\.\d{3} mAh)~'                               => '$1 - Akkuzelle - $3, $4',
            '~(iJoy) (21700) Akku - (.*)~'                                               => '$1 - Akkuzelle - $2, $3',
            '~(Samsung) (40T) (21700) (.*)~'                                             => '$1 - Akkuzelle - $2 $3 - $4',
            '~EVO~'                                                                      => 'Evo',
            '~SINUOUS~'                                                                  => 'Sinuous',
            '~POD~'                                                                      => 'Pod',
            '~GNOME~'                                                                    => 'Gnome',
            '~ Core Dual ~'                                                              => ' ',
            '~ Core ~'                                                                   => ' ',
            '~Basis~'                                                                    => 'Base',
            '~(Twelve Monkeys.*Circle of Life) (.*)~'                                    => '$1 - $2',
            '~(Tango Yango) Mango-Sahne~'                                                => '$1',
            '~(Chinese Green) Grüner Tee-Lychee~'                                        => '$1',
            '~(Fresh Yellow) Zitrone~'                                                   => '$1',
            '~(Hakuna Matata) Traube~'                                                   => '$1',
            '~(Cucumis) s(ativus) Gurke~'                                                => '$1 S$2',
            '~(Afternoon) Vanille-Käsekuchen~'                                           => '$1',
            '~(Always) Cola~'                                                            => '$1',
            '~(Angels in Heaven) Tabak~'                                                 => '$1',
            '~(Blue Spot) Blaubeeren~'                                                   => '$1',
            '~(Brown Nutty) Nougat~'                                                     => '$1',
            '~(Caribbean) Kokos-Schokoladen~'                                            => '$1',
            '~(Celestial Dragon) Tabak~'                                                 => '$1',
            '~(Cold Vacci) Heidelbeere-Fresh~'                                           => '$1',
            '~(Commander Joe) Tabak~'                                                    => '$1',
            '~(Devils Darling) Tabak~'                                                   => '$1',
            '~(First Man) Apfel~'                                                        => '$1',
            '~(First Money) Orangenlimonade~'                                            => '$1',
            '~(Green Angry) Limetten~'                                                   => '$1',
            '~(Hairy Fluffy) Pfirsich~'                                                  => '$1',
            '~(Inside Red) Wassermelonen~'                                               => '$1',
            '~(La Renaissance) Tabak-Schokoladen~'                                       => '$1',
            '~(Little Soft) Himbeer~'                                                    => '$1',
            '~(Master Wood) Waldmeister~'                                                => '$1',
            '~(Milli) Vanille~'                                                          => '$1',
            '~(Monkey Around) Bananen-Amarenakirsche~'                                   => '$1',
            '~(Pretty Sweetheart) Sahne-Erdbeer~'                                        => '$1',
            '~(Red Cyclone) Rote Früchte~'                                               => '$1',
            '~(Red Violet) Amarenakirsche~'                                              => '$1',
            '~(Rounded Yellow) Honigmelonen~'                                            => '$1',
            '~(Spiky) Maracuja~'                                                         => '$1',
            '~(Star Spangled) Tabak~'                                                    => '$1',
            '~(Sweetheart) Erdbeer~'                                                     => '$1',
            '~(The Empire) Tabak Nuss~'                                                  => '$1',
            '~(It).*(Apple Pie)~'                                                        => '$1\'s $2',
            '~(King)s (Fool)~'                                                           => '$1\'s $2',
            '~(Nebelfee)(.*)?(s Milk)~'                                                  => '$1\'$3',
            '~(Father)s (Milk)~'                                                         => '$1\'s $2',
            '~(Smooth) Weston~'                                                          => '$1 Western',
            '~(Ice) (Frappe)~'                                                           => '$1d $2',
            '~(Pipes Best) Tabak~'                                                       => '$1',
            '~(Desert Safari) Tabak~'                                                    => '$1',
            '~(Delicate Mild) Tabak~'                                                    => '$1',
            '~(Taste of America) Tabak~'                                                 => '$1',
            '~(The Rebels) Tabak Vanille~'                                               => '$1',
            '~(White Glacier) Fresh~'                                                    => '$1',
            '~(Wild West) Tabakaroma~'                                                   => '$1',
            '~(Virginias Best) Tabak~'                                                   => '$1',
            '~(Virginas Best) Tabak~'                                                    => '$1',
            '~(Strong Taste) Tabak~'                                                     => '$1',
            '~(RY4) Tabak~'                                                              => '$1',
            '~(Pure) Tabakaroma~'                                                        => '$1',
            '~(America\'s Finest) Tabak~'                                                => '$1',
            '~(Gentleman)’(s Cloud) Tabak~'                                              => '$1\'$2',
            '~(MyWay) Pfeifentabak~'                                                     => '$1',
            '~(Shaken, not stirred) Orangen~'                                            => '$1',
            '~(Stirred, not )S(haken) Mango~'                                            => '$1s$2',
            '~(Black Tie) Tabak~'                                                        => '$1',
            '~(Courtesy of the Kings) Minze-Schokoladen~'                                => '$1',
            '~(Lady-Like) Früchtemix~'                                                   => '$1',
            '~(Kings Dessert) Crème Brûlée~'                                             => '$1',
            '~(Atlantis Luxury) Tequila Sunrise~'                                        => '$1',
            '~(My Island) Virgin Colada~'                                                => '$1',
            '~(Mystery Fruits) Kaktusfeige~'                                             => '$1',
            '~(Babette)’s~'                                                              => '$1\'s',

            '~(ProC)\d(-S)?~'                                     => '$1',
            '~E-Zigaretten (- Nikotinsalz-Liquid)~'               => '$1',
            '~E-Zigaretten Starter Set~'                          => 'E-Zigarette',
            '~(Anniversary)-(Edition) (E-Zigarette)~'             => '$1 $2 - $3',
            '~E-Zigaretten Set~'                                  => 'E-Zigarette',
            '~E Zigaretten Set~'                                  => 'E-Zigarette',
            '~E-Zigaretten-Set~'                                  => 'E-Zigarette',
            '~(Pasito) Pod (E-Zigarette)~'                        => '$1 $2',
            '~(J-Easy)((3)|(9))~'                                 => '$1 $2',
            '~Nautilus Mini BVC Clearomizer~'                     => 'Nautilus Mini Clearomizer',
            '~Clearomizer( Set)?~'                                => 'Verdampfer',
            '~Glastank und Mundstück Set~'                        => 'Glastank + Mundstück (Set)',
            '~Tank (Verdampfer)~'                                 => '$1',
            '~Ersatz-Dichtung~'                                   => 'Ersatzdichtung',
            '~Dichtungs-Set~'                                     => 'Ersatzdichtungen',
            '~Heads Heads~'                                       => 'Heads',
            '~Mr\. Niks~'                                         => 'Mr. Nik\'s',
            '~reds Apple EJuice~'                                 => 'Red\'s Apple Juice',
            '~mit -~'                                             => 'mit',
            '~mit D22 ~'                                          => '',
            '~Pro P~'                                             => 'pro P',
            '~(pro Pack)[^u]~'                                    => '$1ung)',
            '~St. pro~'                                           => 'Stück pro',
            '~5er Pack~'                                          => '5 Stück pro Packung',
            '~10er Packung~'                                      => '(10 Stück pro Packung)',
            '~(Dual Coil), (1,5 Ohm)~'                            => '- $1, $2',
            '~Vape Base~'                                         => 'Shake & Vape',
            '~mAh 40A~'                                           => 'mAh, 40 A',
            '~P80 Watt~'                                          => 'P80 - 80 Watt',
            '~\+ Adapter~'                                        => ', mit Adapter',
            '~Limited Edition - 30 ml~'                           => 'Limited Edition - Aroma - 30 ml',
            '~(Pod) mit (Head)~'                                  => '$1 inkl. $2',
            '~6 in 1 Head Set~'                                   => 'Coil Set (20 Stück, 6 Varianten)',
            '~Base - Shake \& Vape -~'                            => 'Base -',
            '~(Glastank),? (\d+ ml)~'                             => '$1 - $2',
            '~(Head) - (ARC)~'                                    => '$2 $1 -',
            '~(Hookah) (Set)~'                                    => '$1 ($2)',
            '~(Zelos) - 5~'                                       => '$1 - Akku $2',
            '~(Z50) (- \d\.\d+ mAh)~'                             => '$1 - Akku $2',
            '~(Zelos 3) (- \d\.\d+ mAh)~'                         => '$1 - Akku $2',
            '~(Galaxies) (- \d+ mAh)~'                            => '$1 - Akku $2',
            '~(Zeep Mini) (- \d+ mAh)~'                           => '$1 - Akku $2',
            '~(NX40) (- \d\.\d+ mAh)~'                            => '$1 - Akku $2',
            '~(Meteor 510) (- \d\.\d+ mAh)~'                      => '$1 - Akku $2',
            '~(iStick Nowos) (- \d\.\d+ mAh)~'                    => '$1 - Akku $2',
            '~(Gen Nano) (- \d\.\d+ mAh)~'                        => '$1 - Akku $2',
            '~(CoolFire Z50) (- \d\.\d+ mAh)~'                    => '$1 - Akku $2',
            '~(iStick S80) (- \d\.\d+ mAh)~'                      => '$1 - Akku $2',
            '~(iStick Rim) (- \d\.\d+ mAh)~'                      => '$1 - Akku $2',
            '~(Adept) (- \d\.\d+ mAh)~'                           => '$1 - Akku $2',
            '~(Typhon) (- \d+ Watt)~'                             => '$1 - Akku $2',
            '~(Amnis) (- \d+ mAh)~'                               => '$1 - Akku $2',
            '~(X-Priv Baby) (- \d\.\d+ mAh)~'                     => '$1 - Akku $2',
            '~(Aegis Mini) (- \d\.\d+ mAh)~'                      => '$1 - Akku $2',
            '~(Drag Mini) (- \d\.\d+ mAh)~'                       => '$1 - Akku $2',
            '~(Target Mini 2) (- \d\.\d+ mAh)~'                   => '$1 - Akku $2',
            '~(Exceed X) (- \d\.\d+ mAh)~'                        => '$1 - Akku $2',
            '~(iStick T80) (- \d\.\d+ mAh)~'                      => '$1 - Akku $2',
            '~(Kroma A) (- \d\.\d+ mAh)~'                         => '$1 - Akku $2',
            '~(MVP5) (- \d\.\d+ mAh)~'                            => '$1 - Akku $2',
            '~(Proton Mini) (- \d\.\d+ mAh)~'                     => '$1 - Akku $2',
            '~(Mag Baby) (- \d+ Watt)~'                           => '$1 - Akku $2',
            //            '~(Compact 14) (Akku)~'                                  => '$1 - $2',
            '~(Pumper.*) (- \d+ Watt)~'                           => '$1 - Squonker Box $2',
            '~(Blocks.*) (\d+ Watt)~'                             => '$1 - Squonker Box - $2',
            '~(Feedlink) (- \d+ Watt)~'                           => '$1 - Squonker Box $2',
            '~(Pumper)-~'                                         => '$1 ',
            '~(Basal) (Akku)~'                                    => '$1 - $2',
            '~(J-Easy \d) (Akku)~'                                => '$1 - $2',
            '~(RX Gen3)~'                                         => 'Reuleaux RX Gen3',
            '~(RX GEN3)~'                                         => 'RX Gen3',
            '~(Lux) 200~'                                         => '$1',
            '~(Aegis Squonk) (- \d+ Watt)~'                       => '$1 - Squonker Box $2',
            '~(MDura Pro) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(RHEA) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Alieno) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Swag PX80) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(ARCFOX) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Z1 SBS) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(213 Fog) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(FORZ TX80) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Thelema DNA 250C) (- \d+ Watt)~'                   => '$1 - Akkuträger $2',
            '~(Finixx) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Velocity) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Paradox) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Rigel Mini) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(Rigel) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Scar Mini) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Vrod) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Morph 2) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Scar 18) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Grus) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Gen X) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Siegfried) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Essent) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Argus GT) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Techmod) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(MIXX) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Deco) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Gen-S) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Kriemhild) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(V200 Vtec 1.8) (- \d+ Watt)~'                      => '$1 - Akkuträger $2',
            '~(Aegis Max)( Zeus) (- \d+ Watt)~'                   => '$1 - Akkuträger $3',
            //special
            '~(Kroma-R) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Centaurus DNA 250C) (- \d+ Watt)~'                 => '$1 - Akkuträger $2',
            '~(Swag 2) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(G-Priv 3) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Glint) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(DJV D7) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Hadron) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Trip) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Proton) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Humvee) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(R150S) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(RSQ Mate) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(G100) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Tac21) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Fush) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(GEN) (- \d+ Watt)~'                                => '$1 - Akkuträger $2',
            '~(Double Barrel V3) (- \d+ Watt)~'                   => '$1 - Akkuträger $2',
            '~(Detonator) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Revo) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Mag P3) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Tribeaut) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Lunar) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Magma) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Rudder) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Taggerz) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Cube X) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(VX200) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Morph) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Aegis Solo) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(Druga Foxy) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(X217) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Topside Dual) (- \d+ Watt)~'                       => '$1 - Akkuträger $2',
            '~(Lux) (- \d+ Watt)~'                                => '$1 - Akkuträger $2',
            '~(ECO) (- \d+ Watt)~'                                => '$1 - Akkuträger $2',
            '~(ECO Pro) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Helix) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Reuleaux RX Gen3) (- \d+ Watt)~'                   => '$1 - Akkuträger $2',
            '~(Speeder) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Cut Premium) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Rage) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(eMASK) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Valyrian 2) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(Soulkeeper) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(Titan PWM) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Crown 4) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(x Ultroner EOS II) (- \d+ Watt)~'                  => '$1 - Akkuträger $2',
            '~(SkyStar) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Mag Grip) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Puxos) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Dynamo) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Colossal) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Minikin.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Lustro) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Amighty) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Puma) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(V-IT) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Invoke) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Evdilo) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Nunchaku 2) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(iKonn) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Lexicon) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Lucid) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(iStick .*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Aegis X) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Aegis Legend.*) (- \d+ Watt)~'                     => '$1 - Akkuträger $2',
            '~(Edge.*) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Nova) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Espion.*) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(eVic Primo SE) (- \d+ Watt)~'                      => '$1 - Akkuträger $2',
            '~([GXTH]-Priv( 2)?) (- \d+ Watt)~'                   => '$1 - Akkuträger $3',
            '~(G-Priv Baby) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Ironfist) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Hypercar) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Nunchaku) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Ultex T80) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Luxe 2) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Luxe) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Polar) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Species) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Sinuous.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Revenger.*) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(SX Mini.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(VK530.*) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Subverter 1.*) (- \d+ Watt)~'                      => '$1 - Akkuträger $2',
            '~(Drag 2.*) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Drag 3) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Drag X Plus) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Delta) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(iJust 21700) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Reuleaux.*) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(CB-80) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Luxotic.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Medea) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Aster)~'                                           => '$1 - Akkuträger - 75 Watt',
            '~OSUB (King) (- \d+ Watt)~'                          => 'Osub $1 - Akkuträger $2',
            '~(Dichtung) (Set)~'                                  => 'Ersatzdichtungen',
            '~(Head) \((Dual Coil)\)~'                            => '$2 $1',
            '~(\d,\d+ Ohm) (Head)~'                               => '$2 - $1',
            '~(iKonn) 220~'                                       => '$1',
            '~(Melo \d) D(\d\d) ((Verdampfer)|(Glastank))~'       => '$1 - $3 - $2 mm',
            '~(IM4) - (Head)~'                                    => 'IM4 Head',
            '~HG2 18650~'                                         => 'INR18650HG2 - Akkuzelle',
            '~(VTC((6)|(5A)))~'                                   => '$1 - Akkuzelle',
            '~(INR18650-((25R)|(30Q)))~'                          => '$1 - Akkuzelle',
            '~\(Panasonic\) (NCR20700B)~'                         => '$1 - Akkuzelle',
            '~(\d{5})er (Quad Akkubox)~'                          => '$2 - $1',
            '~(\d{5})er( Akku)?~'                                 => '$1 - Akkuzelle',
            '~Akkuzellebox~'                                      => 'Akkubox',
            '~(Easy 3) (Caps) (.*) \(~'                           => '$1 $3 - $2 (',
            '~(Easy 4) (Caps) (.*) \(~'                           => '$1 $3 - $2 (',
            '~(Sweetheart)e~'                                     => '$1',
            '~(Devil)s (Darling)~'                                => '$1\'s $2',
            '~(Prince)-((X6)|(M4)|(T10)|(Q4))~'                   => '$1 $2',
            '~(SMOK) (V8)~'                                       => '$1 TF$2',
            '~((vPipe III)|(Zen Pipe)) Set~'                      => '$1 - E-Pfeife',
            '~(vPipe III) (- E-Pfeife) (Ebony)~'                  => '$1 $3 $2',
            '~(Pod) mit Head -~'                                  => '$1 -',
            '~(Pod) mit~'                                         => '$1 -',
            '~(Watt)s$~'                                          => '$1',
            '~(Batterie)-H(ülse)~'                                => '$1h$2',
            '~(Batterie)-K(appe)~'                                => '$1k$2',
            '~mit (Revvo Boost)~'                                 => '$1',
            '~Ta (Baby)~'                                         => 'Tarot $1',
            '~(ClouDrippin’ Psychedelic Edition) (.*) (- Aroma)~' => '$2 - $1 $3',
            '~(20700/21700) (Batteriekappe)~'                     => '$2 - $1',
            '~(GTM?\d)( Coil)? (Head)~'                           => '$1 - $3',
            '~[Cc][Cc][eE][lL][lL]~'                              => 'cCell',
            '~(cCell) Coil (Head)~'                               => '$1 - $2',
            '~Geekvape~'                                          => 'GeekVape',
            '~(GeekVape) ([^\-])~'                                => '$1 - $2',
            '~2 in 1 Set~'                                        => '(2 Stück pro Packung)',
            '~2 in 1 (Clapton Head) Set~'                         => '$1 (2 Stück pro Packung)',
            '~(18650)(VTC)~'                                      => '$1 $2',
            '~((18650)|(21700)|(26650)) - (Akku((zelle)|(box)))~' => '$5 - $1',
            '~((18650)|(21700)|(26650)) - (\d\.\d\d\d)~'          => '$1, $5',
            '~(John Smith)s~'                                     => '$1\'s',
            '~(N\d\d ((Framed)|(Fused)) Clapton) Head~'           => '$1 Coil',
            '~(Metal Edition) (E-Zigarette)~'                     => '$1 - $2',
            '~(0,2 Ohm) (Mesh Head)~'                             => '$2 - $1',
            '~(Land) Pod (E-Zigarette)~'                          => '$1 $2',
            '~(A1 MTL Clapton)~'                                  => '$1 Coils',
            '~Shortfill 5 in 1 (.*)~'                             => '5-in-1 $1',
            '~(510) (Adapter)~'                                   => '$1er $2',
        ],
    ],
    'product_names'             => [
        'Advken'                => [
            '~(Twirl RDA)~',
            '~(Manta RTA)~',
            '~(Dark Mesh)~',
            '~(CP TF RTA)~',
            '~(Owl)~',
            '~(Artha V2 RDA)~',
        ],
        'Arctic Dolphin'        => [
            '~(Crea RDA)~',
        ],
        'Artery'                => [
            '~(Pal Stick)~',
            '~(Pal 2 (Pro)?)~',
            '~(Baton)~',
        ],
        'Aspire'                => [
            // Aspire
            '~(Neeko RTA)~',
            '~(Tekno)~',
            '~(Favostix)~',
            '~(Finixx)~',
            '~(Onixx)~',
            '~(SteelTech)~',
            '~(Minican)~',
            '~(Deco)~',
            '~(BP60)~',
            '~(BP80)~',
            '~(Rover 2)~',
            '~(Reax Mini)~',
            '~(Nepho)~',
            '~(Athos)~',
            '~(Dynamo)~',
            '~(Cloudflask)~',
            '~(Atlantis Evo)~',
            '~(PockeX)~',
            '~((Cobble)( AIO)?)~',
            '~((Spryte)( AIO)?)~',
            '~(Proteus)~',
            '~(Typhon)~',
            '~(Cygnet)~',
            '~(Speeder)~',
            '~(Puxos)~',
            '~(Tigon( AIO)?)~',
            '~((Triton)(( 2)|( Mini))?)~',
            '~((Breeze)(( 2)|( NXT))?)~',
            '~((Zelos)(( 2.0)|( 3))?)~',
            '~(Revvo(( Mini)|( Boost))?)~',
            '~(Nautilus(( 3)|( 2S?)|( XS)|( X)|( Mini)|( Prime X)|( Prime)|( AIO)|( GT( Mini)?))?)~',
            '~(Cleito((( Shot)|( 120)?( Pro)?))?)~',
            '~(SkyStar)~',
            '~(Feedlink)~',
            '~((Revvo)( Mini)?)~',
            '~((K1 Plus)|(K1 Stealth)|((K\d)( \& K3)?))~',
            '~((K1 Plus)|(K1 Stealth)|((K\d)( \& K3)?))~',
            '~(AVP(( QBE)|( Pro))?)~',
            '~(K-Lite)~',
            '~(Odan(( Evo)|( Mini))?)~',
            '~(Mulus)~',
            '~(OBY)~',
            '~(9th)~',
            '~(Vrod 200)~',
            '~(Guroo)~',
            '~(PENEX)~'
        ],
        'asMODus'               => [
            '~((Minikin V3S mit Viento)|(Minikin(( V2 Kodama)|( V2)|( V3S)|( V3)|( Reborn))?))~',
            '~(C4 RDA)~',
            '~(Colossal)~',
            '~(Pumper 18/21)~',
            '~(Lustro)~',
            '~(Bunker RDA)~',
            '~(Nefarius RDTA)~',
            '~(Voluna V2 RTA)~',
            '~(X VapePorn Vice RDA)~',
            '~((Amighty mit Viento)|(Amighty)|(Viento))~',
            '~(X VapersMD Dawg RTA)~',
            '~(\.Blank RDA)~',
            '~(Anani V2 RTA)~',
        ],
        'Augvape'               => [
            '~(Intake RTA)~',
            '~(Templar RDA)~',
            '~(Occula RDA)~',
            '~(Skynet( Pro)?)~',
            '~(Merlin Nano MTL RTA)~',
            '~(Druga Narada( Pod)?)~',
            '~(iNtake Dual RTA)~',
        ],
        'CoilArt'               => [
            '~(Mage RTA V2)~',
            '~(Lux( Mesh)?)~',
            '~(Mino)~',
            '~(Blazar MTL)~',
        ],
        'Cthulhu'               => [
            '~(Iris Mesh RDA)~',
            '~(1928 MTL RDA)~',
            '~(Hastur(( MTL RTA Mini)|( MTL RDA)|( MTL RTA))?)~',
            '~(Zathog RDA)~',
            '~(Mjölnir RDA)~',
            //            '~(Hastur)~',
            '~(Furai 510)~',
            '~(Mulan MTL RDTA)~',
        ],
        'Dejavu'                => [
            '~(DJV D7)~',
        ],
        'Desire Design'         => [
            '~(Cut Premium)~',
            '~(Rage)~',
            '~(Bulldog)~',
            '~(Lunar)~',
        ],
        'Digiflavor'            => [
            '~(Siren 2 RTA)~',
            '~(Drop RDA( v1.5)?)~',
            '~(Drop Solo RDA)~',
            '~(Edge)~',
            '~(Helix)~',
            '~(Z1 SBS)~',
        ],
        'Ehpro'                 => [
            '~(Panther RDA)~',
        ],
        'Famovape'              => [
            '~(Magma)~',
        ],
        'FreeMax'               => [
            '~(Twister mit Fireluke 2)~',
            '~(Fireluke 22?)~',
            '~(Fireluke 3)~',
            '~(Fireluke Mesh)~',
            '~(Maxus(( 50W)|( 100W)|( 200W)))~',
            '~(M Pro( 2)?)~',
            '~(Gemm)~',
        ],
        'GeekVape'              => [
            '~(Talo X RDA)~',
            '~(Wenax(( Stylus)|( K1)|( C1))?)~',
            '~(Alpha)~',
            '~(Bident)~',
            '~(Ammit 25 RTA)~',
            '~(Baron RDA)~',
            '~(Blitzen RTA)~',
            '~(Ammit MTL RTA)~',
            '~(Tengu RDA)~',
            '~(Creed RTA)~',
            '~(Zeus(( X2)|( X RTA)|( Dual RTA)|( RTA))?)~',
            '~(Ammit Dual Coil RTA)~',
            '~(Aegis(( Hero)|( Max)|( Pod)|( Boost Plus)|( Boost Pro)|( Boost Luxury Edition)|( Boost)|( Legend( 2)?)|( Mini)|( X)|( Solo)|( Squonk))?)~',
            '~(Aero Mesh)~',
            '~(Cerberus)~',
            '~(Creed RTA)~',
            '~(Nova)~',
            '~(Loop( v1.5)? RDA)~',
            '~(Lucid)~',
            '~(Flint)~',
            '~(Frenzy)~',
            '~(Mero( AIO)?)~',
            '~(Z Nano)~',
            '~(Z50)~',
            '~(Obelisk)~',
        ],
        'Gorilla Killa'         => [
            '~(eVolut1on)~',
        ],
        'HellVape'              => [
            '~(Grimm)~',
            '~(MD RTA)~',
            '~(Anglo RDA)~',
            '~(Dead Rabbit( V2)? RTA)~',
            '~(Dead Rabbit RDA( v2)?)~',
            '~(Fat Rabbit)~',
            '~(Dead Rabbit SQ RDA)~',
            '~(Drop Dead RDA)~',
            '~(Hellbeast)~',
            '~(Rebirth RDA)~',
            '~(Passage RDA)~',
            '~(Rebirth RTA)~',
            '~(Hellcoil H7-0\d)~',
            '~(Ravana RTA)~',
        ],
        'Horizontech'           => [
            '~(Falcon( King)?)~',
            '~(Magico)~',
        ],
        'iPV'                   => [
            '~(V-IT)~',
            '~(Revo)~',
            '~(Finder BF RDA)~',
            '~(V3 mini( ADA)?)~',
        ],
        'Joyetech'              => [
            '~(eRoll)~',
            '~(eGrip Mini)~',
            '~(CuAIO D22)~',
            '~(Batpack)~',
            '~(Atopack Magic)~',
            '~(Espion Silk)~',
            '~(Teros ONE)~',
            '~(Tralus)~',
            '~(Espion mit ProCore X)~',
            '~(Espion Tour)~',
            '~(ProCore Conquer)~',
            '~(ProCore Air( Plus)?)~',
            '~(Exceed Air)~',
            '~(Exceed Grip)~',
            '~(Exceed X)~',
            '~(Notch(C|c)ore)~',
            '~(Teros)~',
            '~(Riftcore(( Duo)|( Solo)))~',
            '~(ObliQ)~',
            '~(EVIO C)~',
        ],
        'Kangerm'               => [
            '~(M2)~',
            '~(Innovator)~',
        ],
        'Nikola'                => [
            '~(Medea)~',
            '~(Lapetus)~',
        ],
        'Oumier'                => [
            '~(Rudder)~',
            '~(Bombus RTA)~',
            '~(VLS RDA)~',
            '~(Wasp Nano(( RDTA)|( RTA)|( RDA)))~',
            '~(Bulk RTA)~',
            '~(Armadillo RDA)~',

        ],
        'Eleaf'                 => [
            '~(iStick Power 2C mit GTL Pod)~',
            '~(iStick Pico 2)~',
            '~(iStick Pico Baby)~',
            '~(Pico Compaq)~',
            '~(Tance Max)~',
            '~(Ello)~',
            '~(iJust Mini)~',
            '~(Coral 2)~',
            '~(GZeno( S)?)~',
            '~(iStick S80 mit GZeno)~',
            '~(Elven)~',
            '~(iTap)~',
            '~(iStick P100)~',
            '~(iStick T80 mit GTL Pod)~',
            '~(iSolo(( Air)|( R)))~',
        ],
        'SC'                    => [
            '~(iJust(( 21700)|( ECM)|( 3 Pro)|( 3)|( Mini)|( AIO))?)~',
            '~(Ello( ((Vate)|(Duro)|(Pop))?))~',
            '~(iCare Flask)~',
            '~(iKuu Lite)~',
            '~(iTap)~',
            '~(Elven)~',
            '~(GTiO)~',
            '~(Basal)~',
            '~(GS ((Air 2)|(Air 3)|(Air)|(Baby)|(Drive)|(Turbo))?)~',
            '~(iKonn)~',
            '~(Invoke)~',
            '~(iStick ((T80)|(Melo)|(Amnis( 2)?)|(Pico X)|(Pico 21700)|(Pico Baby)|(Pico S)|(Pico)|(Trim)|(Nowos)|(Mix)|(Rim C)|(Rim))?)~',
            '~(iWu)~',
            '~(Lexicon)~',
            '~(Melo \d)~',
            '~(Easy 3)~',
            '~(Easy 4)~',
            '~(Tance( Max)?)~',
            '~(Pesso)~',
            '~(Rotor)~',
        ],
        'Innokin'               => [
            '~(Endura ((T18 2 Mini)|(T18 2)|(T18)|(T20S)|(T20)|(T22)|(M18))?)~',
            '~(Prism ((S)|(T18/T22)|(T18 2)|(T18E)|(T18)|(T20(S)?)|(T22))?)~',
            '~(CoolFire Z50)~',
            '~(Proton( Mini)?)~',
            '~(Glim)~',
            '~(EZ.Watt)~',
            '~(Zenith(( D22)|( Pro))?)~',
            '~(Scion 2 Plexus)~',
            '~(Ares 2(( D24)|( D22)))~',
            '~(Ares RTA)~',
            '~(Cool Fire Mini)~',
            '~(iSub (B)?)~',
            '~(Kroma A)~',
            '~(Gala)~',
            '~(Z Biip)~',
            '~(JEM)~',
            '~(Jem Pen)~',
            '~(Zlide( Tube)?)~',
            '~(Plex((ar)|( 3D))?)~',
            '~(Ajax)~',
            '~(I.O)~',
            '~(Podin)~',
            '~(Sceptre)~',
        ],
        'InnoCigs'              => [
            '~(eGrip Mini)~',
            '~(Batpack)~',
            '~(Atopack( Magic)?)~',
            '~(Cubis 2)~',
            '~(Cubis Max)~',
            '~(RunAbout)~',
            '~(eGo Pod)~',
            '~((eGo AIO)(( Mansion)|( Simple))?)~',
            '~(Espion (Infinite AI)|(Infinite)|(Silk)|(Solo)|(Tour))~',
            '~(eVic Primo Fit)~',
            '~(Ultex T80)~',
            '~(NCFilm Heizplatte)~',
            '~(Exceed( Air)|( D19)|( D22)|( Edge)|( Grip Pro)|( Grip Plus)|( Grip))~',
            '~(Notchcore)~',
            '~(Presence)~',
            '~(ProCore (Air Plus)|(Air)|(Conquer)|(Remix)|(X))~',
            '~(Riftcore(( Duo)|( Solo)))~',
            '~(Teros( ONE)?)~',
            '~(Unimax 22)~',
            '~(Tralus)~',
        ],
        'JustFog'               => [
            '~(C601)~',
            '~(Fog1)~',
            '~(J-Easy3)~',
            '~(Minifit( Max)?)~',
            '~(Compact 14)~',
            '~(Compact 16)~',
            '~(P16A)~',
            '~(Q14)~',
            '~(Q16(( C)|( Pro)))~',
            '~(QPod)~',
        ],
        'Quawins' => [
            '~(VStick pro)~',
        ],
        'Lost Vape'             => [
            '~(Grus)~',
            '~(Original Q( Pro)?)~',
            '~(Original Plus( DNA)?)~',
            '~(Lyra)~',
            '~(Gemini Hybrid)~',
            '~(Back to Basic)~',
            '~(UBX)~',
            '~(UB( Lite)?)~',
            '~(Prana S)~',
            '~(Ursa( Quest Multi)?)~',
            '~(Quest Q-Ultra)~',
            '~(Q-Ultra)~',
            '~(Thelema(( Pod Mod)|( DNA 250C))?)~',
        ],
        'Kizoku'                => [
            '~(Techmod)~',
            '~(Unlimit RTA)~',
            '~(Limit RTA)~',
        ],
        'OBS'                   => [
            '~(Crius 2 RTA)~',
            '~(Engine 2( RTA)?)~',
            '~(KFB 2 AIO)~',
            '~(Engine MTL)~',
            '~(Cheetah 3 RDA)~',
            '~(Cube(( Mini)|( MTL)|( X)|( Pod))?)~',
            '~(Land)~',
            '~(Alter)~',
            '~(Prow)~',
        ],
        'OFRF'                  => [
            '~(Gear RTA)~',
            '~(nexMESH)~',
        ],
        'OXVA'                  => [
            '~(Idian( X)?)~',
            '~(Arbiter RTA)~',
            '~(Arbiter Solo RTA)~',
            '~(Unipro RBA)~',
            '~(Velocity)~',
        ],
        'Smok'                  => [
            '~(Acro)~',
            '~(Gram(( 25)|( 16))?)~',
            '~(#4)~',
            '~(Thallo S)~',
            '~(IPX80)~',
            '~(Rigel( Mini)?)~',
            '~(Scar Mini)~',
            '~(NFIX Mate)~',
            '~(Nfix)~',
            '~(Scar P5)~',
            '~(Scar 18)~',
            '~(RPM160)~',
            '~(NexM)~',
            '~(Alike)~',
            '~(Nord(( 2)|( X)|( 4))?)~',
            '~(Mag(( P3)|( Pod))?)~',
            '~(G-Priv ((2)|(Baby)))~',
            '~(Globe)~',
            '~(Vape Pen V2)~',
            '~(Vape Pen 22)~',
            '~((Vape Pen Nord(( 19)|( 22))?)|(Nord(( AIO 19)|( AIO 22))?))~',
            '~(H-Priv 2)~',
            '~(Morph 219)~',
            '~(Morph 2)~',
            '~(Mag Baby)~',
            '~(Micro One)~',
            '~(Osub King)~',
            '~(TFV16)~',
            '~(TFV18)~',
            '~(Priv M17)~',
            '~(TF )~',
            '~(QBox)~',
            '~(R-Kiss)~',
            '~(R40)~',
            '~(Stick( V9( Max)?)?)~',
            '~(T-Priv)~',
            '~(X-Priv( Baby)?)~',
            '~(TFV12((-P)|( Baby Prince)|( Prince))?)~',
            '~(TFV8 ((Baby)|(X-Baby))?)~',
            '~(TFV9( Mini)?)~',
            '~(Baby V2)~',
            '~(Species)~',
            '~(RPM Lite)~',
            '~(Mico)~',
            '~(Priv N19)~',
            '~(RPM40)~',
            '~(RPM80 Pro)~',
            '~(Novo 2)~',
            '~(Novo X)~',
            '~(Fetch(( Mini)|( Pro)))~',
            '~(Pozz X)~',
            '~(Guardian)~',
            '~(RPM 2)~',
            '~(ARCFOX)~',
            '~(Stick G15)~',
        ],
        'ThunderHead Creations' => [
            '~(Tauren(( MTL RTA)|( RDTA)|( RDA)|( RTA)|( Solo RDA)|( Pro)|( One RTA)|( X Pod)))~',
        ],
        'Renova'                => [
            '~(Zero( Mesh)?)~',
        ],
        'Revenant Vape'         => [
            '~(Delta)~',
        ],
        'Sigelei'               => [
            '~(Chronus mit Shikra)~',
            '~(Sibra E2)~',
            '~(Sibra F)~',
            '~(Sobra)~',
            '~(Moonshot 120)~',
            '~(Wolf Mini)~',
            '~(Etiny Plus)~',
            '~(Odo 2)~',
        ],
        'Smoant'                => [
            '~(Battlestar Squonker( RDA)?)~',
            '~(Taggerz)~',
            '~(Pasito)~',
        ],
        'Snowwolf'              => [
            '~(Mfeng(( Baby)|( UX))?)~',
            '~(Mfeng(( Baby)|( UX))?)~',
            '~(Kfeng(-X)?)~',
            '~(Afeng)~',
            '~(Wolf Tank Mini)~',
            '~(Mini)~',
            '~(Exilis X)~',
            '~(Wocket)~',
            '~(P200)~',
        ],
        'Squid Industries'      => [
            '~(Squad( RTA)?)~',
        ],
        'Steamax'               => [
            // Smok
            '~(G-Priv ((2)|(Baby)))~',
            '~(Globe)~',
            '~(R-Kiss)~',
            '~(H-Priv 2)~',
            '~(Mag Baby)~',
            '~(Micro One)~',
            '~(Osub King)~',
            '~(Priv M17)~',
            '~(QBox)~',
            '~(R40)~',
            '~(Stick)~',
            '~(T-Priv)~',
            '~(X-Priv( Baby)?)~',
            '~(TFV12 ((Baby Prince)|(Prince))?)~',
            '~(TFV8 ((Baby)|(X-Baby))?)~',
            '~(Baby V2)~',
            '~(Trough)~',
            '~(Species)~',

            // Wismec
            '~(R80)~',
            '~(Preva(( DNA)|( KTR)|( SS316 Dual)))~',
            '~(Amor NS Pro)~',
            '~(Amor NSE)~',
            '~(Column)~',
            '~(Divider)~',
            '~(Elabo Mini)~',
            '~(Gnome(( King)|( Evo))?)~',
            '~(Guillotine V2)~',
            '~(Luxotic BF Box)~',
            '~(Luxotic MF Box)~',
            '~(Luxotic DF Box)~',
            '~(Luxotic Surface)~',
            '~(Luxotic NC)~',
            '~(Kestrel RDTA)~',
            '~(Motiv 2)~',
            '~(Reuleaux RX Gen3 Dual)~',
            '~(Reuleaux Tinker( 2)?)~',
            '~(Sinuous(( V200)|( P80)|( V80)|( Ravage)|( SW)|( Solo))?)~',
            '~(Reux)~',
            '~(Vape Pen V2)~',

        ],
        'Steam Crave'           => [
            '~(Aromamizer Plus RDTA)~',
            '~(Aromamizer Supreme RDTA V2(\.1)?)~',
            '~(Aromamizer Supreme V3)~',
            '~(Aromamizer Titan RDTA)~',
            '~(Aromamizer Titan V2( RDTA)?)~',
            '~(Aromamizer Lite RTA( v1.5)?)~',
            '~(Titan)~',
            '~(Glaz Mini MTL RTA)~',
            '~(Glaz RDSA)~',
            '~(Mico)~',
            '~(Glaz RTA)~',
        ],
        'UD' => [
            '~(Zeep Mini)~',
        ],
        'Uwell'                 => [
            '~(Tripod PCC)~',
            '~(Evdilo)~',
            '~(Marsupod)~',
            '~(Crown(( 3)|( 4)|( 5)|( Pod)))~',
            '~(Fancier RTA)~',
            '~(Hypercar)~',
            '~(Ironfist)~',
            '~(Nunchaku(( RDA)|( 2))?)~',
            '~(Valyrian(( 2 Pro)|( 2)|( Pod))?)~',
            '~(Blocks)~',
            '~(Whirl(( S)|( 2)|( 20)|( 22))?)~',
            '~(Caliburn(( Koko( Prime)?)|( G))?)~',
            '~(Amulet)~',
            '~(Zumwalt Pod)~',
            '~(Aeglos)~',
            '~(Yearn Neat 2)~',

        ],
        'Vapanion'              => [
            '~(Cascade(( Baby SE)|( Baby)|( One Plus)|( One))?)~',
            '~(NRG((-S)|( SE))?)~',
            '~(Switcher( LE)?)~',

        ],
        'Vapefly'               => [
            '~(Galaxies 30W)~',
            '~(Galaxies Air)~',
            '~(Manners)~',
            '~(Brunhilde MTL RTA)~',
            '~(Brunhilde Top Coiler RTA)~',
            '~(Kriemhild( 2)?)~',
            '~(Siegfried)~',
            '~(TGO( Pod Mod)?)~',
            '~(JesterX( Pod Mod)?)~',
        ],
        'VapeOnly'              => [
            '~(vPipe(( III)|( Mini)) (Ebony)?)~',
            '~(Zen Pipe)~',
        ],
        'VooPoo'                => [
            '~(Drag Max)~',
            '~(Drag 2)~',
            '~(Drag 3)~',
            '~(Drag X(( & Vmate)|( Plus))?)~',
            '~(Drag Mini)~',
            '~(Drag Nano)~',
            '~(Drag Baby Trio)~',
            '~(X217)~',
            '~(Maat)~',
            '~(Find(( Pod)|( S Trio))?)~',
            '~((Zip)|((Alpha Zip)( (Mini))?))~',
            '~(Uforce T2)~',
            '~(Vinci(( 2)|( X 2)|( X)|( Air))?)~',
            '~(Navi)~',
            '~(Argus(( X)|( GT)|( Air)))~',
            '~(PnP Pod)~',
            '~(V Thru Pro)~',
            '~(Argus( Pro)?)~',
            '~(VMATE)~',
        ],
        'Vaporesso'             => [
            '~(Forz)~',
            '~(FORZ TX80( RDA)?)~',
            '~(FORZ RDA)~',
            '~(FORZ 25)~',
            '~(GTX(( Tank 22)|( One)|( 18)))~',
            '~(Cascade(( One Plus SE)|( One Plus)|( One)|( Baby SE))?)~',
            '~(Barr)~',
            '~(Osmall)~',
            '~(Sky Solo( Plus)?)~',
            '~(GEN)~',
            '~(Gen(( X)|( S))?)~',
            '~(Aurora Play)~',
            '~(Luxe(( S)|( Nano)|( 2))?)~',
            '~(LUXE PM40)~',
            '~(NRG)~',
            '~(Orca Solo( Plus)?)~',
            '~(Polar)~',
            '~(Revenger X)~',
            '~(SKRR((-S Mini)|(-S))?)~',
            '~(Tarot Baby)~',
            '~(Veco)~',
            '~(Zero( Mesh)?)~',
            '~(Target(( Mini 2)|( PM80 SE)|( PM80)|( PM30))?)~',
            '~(VM Solo 22)~',
            '~(VM Stick 18)~',
            '~(VM \d\d)~',
            '~(PodStick)~',
            '~(Degree)~',
            '~(Swag 2( Christmas Edition)?)~',
            '~(XTRA)~',
            '~(Gen Nano)~',
            '~(XROS)~',
            '~(Xiron Pod Mod)~',
            '~(Swag PX80)~',
        ],
        'Vapor Storm'           => [
            '~(Puma)~',
            '~(Ares Pod)~',
            '~(Subverter 1)~',
            '~(ECO( Pro)?)~',
            '~(Lion RDA)~',
            '~(Trip)~',
        ],
        'VapX'                  => [
            '~(Geyser( S)?)~',
            '~(ART)~',

        ],
        'Vsticking'             => [
            '~(VK530)~',
            '~(VIY)~',
            '~(VKsma)~',
            '~(SMA ADA)~',
            '~(SMI ADA)~',
        ],
        'Vzone'                 => [
            '~(Scado)~',
            '~(eMASK)~',
            '~(Vlit Preco)~',
            '~(Preco( Plus)?)~',
            '~(Vlit Vowl 40)~',
        ],
        'Wismec'                => [
            '~(Preva(( DNA)|( KTR)|( SS316 Dual)|( Pod))?)~',
            '~(Bellerophon RTA)~',
            '~(Tobhino BF RDA)~',
            '~(Amor NS Pro)~',
            '~(Amor NSE)~',
            '~(Column)~',
            '~(Divider)~',
            '~(Elabo Mini)~',
            '~(Gnome(( Evo)|( King))?)~',
            '~(Guillotine V2)~',
            '~(Luxotic BF Box)~',
            '~(Luxotic MF Box)~',
            '~(Luxotic DF Box)~',
            '~(Luxotic NC)~',
            '~(Luxotic Surface)~',
            '~(Motiv 2)~',
            '~(Reuleaux RX Gen3 Dual)~',
            '~(Sinuous(( P80)|( V80)|( Ravage)|( SW))?)~',
            '~(Reux)~',
            '~(Kestrel RDTA)~',
            '~(Reuleaux Tinker( 2)?)~',
            '~(R80)~',
            '~(CB-80)~',
            '~(HiFlask)~',
        ],
        'Wotofo'                => [
            '~(Manik Pod Mod)~',
            '~(Warrior RDA)~',
            '~(Recurve RDA)~',
            '~(STNG MTL RDA)~',
            '~(COG MTL RTA)~',
            '~(Profile(( M RTA)|( Unity RTA)|( 1.5 RDA)|( RDTA)))~',
            '~(nexM Pro)~',
            '~(SMRT)~',
            '~(The Troll X RTA)~',
        ],
        'XTAR'                  => [
            '~(Queen ANT MC6C)~',
            '~(Dragon VP4 Plus)~',
            '~(VC4(S)?)~',
            '~(MC1((S)|( Plus))?)~',
            '~(MC2(( Plus)|(S))?)~',
            '~(PB2(C)?)~',
            '~(VC2(S)?)~',
            '~(SC1)~',
            '~(SC2)~',
            '~(ST2)~',
            '~(MC4)~',
        ],
        'Yihi'                  => [
            '~(SX Mini Mi Class)~',
            '~(SX Mini SL Class)~',
            '~(SX Mini X Class)~',
            '~(SX Mini Divine RDA)~',
            '~(SX Nano)~',
            '~(SXmini SX Auto)~',
            '~(SX Auto)~',
            '~(SX-RSA Esea)~',
        ],
        'ZQ'                    => [
            '~(Vi)~',
            '~(GO)~',
            '~(LEX)~',
            '~(Trio RTA)~',
        ],

    ],

    'innocigs_brands' => ['SC', 'Steamax', 'InnoCigs', 'Innocigs'],
];