<?php

return [
    'name_prepare' => [
        'preg_replace' => [
            '~\s+~'                                 => ' ',
            '~(- )+~'                               => '$1',
            '~ ,~'                                  => ',',
            '~, -~'                                 => '-',
            '~ - ?$~'                               => '',
            '~10ml\/ml~'                            => '10ml',
            '~0ml\/ml~'                             => '0mg/ml',
            '~(\d+)m~'                              => '$1 m',
            '~(0 mg)$~'                             => '$1/ml',
            '~(\d) mAH~'                            => '$1 mAh',
            '~(\d mg)[^\/]~'                        => '$1/ml',
            '~Sherbert~'                            => 'Sherbet',
            '~Americas~'                            => 'America\'s',
            '~America´s~'                           => 'America\'s',
            '~AsMODus~'                             => 'asMODus',
            '~Asmodus~'                             => 'asMODus',
            '~(Heads )+~'                           => '$1',
            '~(Head )+~'                            => '$1',
            '~(10er Packung)en~'                    => '$1',
            '~[^\(](3 Stück pro Packung\))~'        => ' ($1',
            '~(Aromamizer Plus) Bubble (Glastank)~' => '$1 $2',
            '~(JVIC)\d~'                            => '$1',
            '~((HW1)|(HW2)) (Heads)~'               => 'HW1/HW2 $4',
            '~artikblau~'                           => 'arktikblau',
            '~(K2 & K3.*) \(\d+ (St. pro Pack\))~'  => '$1 (5 $2',
            '~Freemax~'                             => 'FreeMax',
            '~(Skynet) (Pro )?Sub-Ohm ~'            => '$1 $2',
            // separator different from '-'
            '~–~'                                   => '-',
        ],
    ],


    'name_cleanup'              => [
        'preg_replace' => [
            '~\s+~'                                        => ' ',
            '~(- )+~'                                      => '$1',
            '~ ,~'                                         => ',',
            '~-,~'                                         => '-',
            '~, -~'                                        => '-',
            '~ - ?$~'                                      => '',
            '~ $~'                                         => '',
            '~^ ~'                                         => '',
            '~(RDTA)+~'                                    => '$1',
            '~-V12~'                                       => '- V12',
            '~-(Ersatz)~'                                  => '- $1',
            '~-(E-Zigarette)~'                             => '- $1',
            '~-(Netzstecker)~'                             => '- $1',
            '~-(Mundstücke)~'                              => '- $1',
            '~- (mit Ello)~'                               => '$1',
            '~-(V8-)~'                                     => '- $1',
            '~(10er Packung)en~'                           => '$1',
            '~-(Anniversary)~'                             => '- $1',
            '~(GS) -(Basal)~'                              => '$1 $2',
            '~-(Glastank)~'                                => '- $1',
            '~-(Clearomizer)~'                             => '- $1',
            '~(Head) - Head~'                              => '$1',
            '~- (Head)~'                                   => '$1',
            '~^(\p{L}*) (Head)~'                           => '$1 - $2',
            '~(JustFog) ([^\-])~'                          => '$1 - $2',
            '~ XXer Packung~'                              => '',
            '~(Revvo) - (Boost)~'                          => '$1 $2',
            '~(EX) --M (Mesh)~'                            => '$1-M $2',
            '~(Tasche) X -L~'                              => '$1 XL',
            '~(E-Zigarette \(Set\)) e$~'                   => '$1',
            '~(iStick Pico) - (Resin mit Melo 4) - (D22)~' => '$1 $2 $3 -',
            '~(mit TFV8 Baby) - (V2)~'                     => '$1 $2 -',
            '~(Leerflasche), (\d+ ml)~'                    => '$1 - $2',
            '~(Air) - (Plus)~'                             => '$1 $2 -',
            '~(Melo 3) - (Mini)~'                          => '$1 $2 -',
            '~(TFV12) - P-~'                               => '$1-P -',
            '~(Glaz RTA) - (V2)~'                          => '$1 $2 -',
            '~(Legend) - (mit Alpha)~'                     => '$1 $2',
            '~((V200)|(V80)) - (mit Amor NSE)~'            => '$1 $4',
            '~(Lite) - (mit GS Air 3)~'                    => '$1 $2',
            '~(Probierbox - Liquid) - 10 ml~'              => '$1',
            '~(Nikotinsalz-Liquid) (\d+ mg/ml)~'           => '$1 - $2',
            '~(VG/PG: 80/20), (\d+ ml), (\d+ mg/ml)~'      => '$1 - $2 - $3',
            '~(Squonker Flasche), (\d+ ml)~'               => '$1 - $2',
            '~(Star Spangled), 9 mg/ml~'                   => '$1',
            '~(Ultem Tank), (5 ml)~'                       => '$1 - $2',
            '~(Akkuträger) - Akkuträger~'                  => '$1',
        ],
    ],


    // NOTE: Since we use the new API property PARENT_NAME now, we do not have
    // to replace options in product names any longer, so this setting is not
    // used any more.
    'product_name_option_fixes' => [
        // option text                                  // option found in name
        'prisma-blau'                                => 'blau-prisma',
        'prisma-chrom'                               => 'chrom-prisma',
        'prisma-gold'                                => 'gold-prisma',
        'prisma-regenbogen'                          => 'regenbogen-prisma',
        'prisma-rot'                                 => 'rot-prisma',
        'prisma-gunmetal'                            => 'gunmetal-prisma',
        'schwarz-rot'                                =>
            [
                'rot-schwarz',
                'schwarz rot',
            ],
        'Jeans'                                      => 'jeans',
        'Jade'                                       => 'jade',
        'NI80'                                       => 'Ni80',
        '0,4 Ohm'                                    => '0,4',
        '2,0 ml'                                     => ['2 ml', '2ml'],
        '2 ml'                                       => '2,0 ml',
        '3,5 ml'                                     => [
            '3.5 ml',
            '3,5ml',
        ],
        '4,5 ml'                                     => '4,5ml',
        '4 ml'                                       => '4ml',
        '15ml'                                       => '15 ml',
        '10ml'                                       => '10 ml',
        '20ml'                                       => '20 ml',
        '18ml'                                       => '18 ml',
        '5ml'                                        => '5 ml',
        '28ml'                                       => '28 ml',
        'Typ A'                                      => 'Typ-A',
        'Typ B'                                      => 'Typ-B',
        '3,0ml'                                      => '3 ml',
        '4,2ml'                                      => '4,2 ml',
        'V2-M'                                       => 'M',
        'V2-XL'                                      => 'XL',
        'Coral'                                      => 'coral',
        'matt-schwarz'                               => 'matt schwarz',
        'schwarz-weiß'                               => 'schwarz-weiss',
        'schwarz-weiss-resin'                        => 'schwarz-weiß-resin',
        'camouflage-grau'                            => 'camouflage grau',
        'Flasche schwarz transparent + schwarze Cap' => 'schwarz-transparent mit schwarzer Cap',
        'Flasche schwarz + schwarze Cap'             => 'schwarz mit schwarzer Cap',
        'Flasche transparent + schwarze Cap'         => 'mit schwarzer Cap',
        'Flasche weiss + weisse Cap'                 => 'weiss mit weisser Cap',
        'Flasche transparent + transparente Cap'     => '', // does not occur in name
        '1er Packung'                                => '', // does not occur in name
        'weiß'                                       => 'weiss',
        '50PG / 50VG'                                => [
            '50PG/50VG',
            '50VG/50PG',
            '50VG / 50PG',
        ],
        '28 GA'                                      => '28GA',
        '26 GA'                                      => '26GA',
        '24 GA'                                      => '24GA',
        '22 GA'                                      => '22GA',
        '24 GA*2+32 GA'                              => '24GA*2+32GA',
        '28 GA*2+32 GA'                              => '28GA*2+32GA',
        '26 GA+32 GA'                                => '26GA+32GA',
        'ProC1 0,4 Ohm'                              => '0,4 Ohm',
        'ProC1-S 0,25 Ohm'                           => '0,25 Ohm',
        'ProC2 0,15 Ohm'                             => '0,15 Ohm',
        'ProC3 0,2 Ohm'                              => '0,2 Ohm',
        'ProC4 0,15 Ohm'                             => '0,15 Ohm',
        'Edelstahl (5er Pack)'                       => 'Edelstahl (5 St. pro Pack)',
        'Kunststoff (10er Pack)'                     => 'KunstStoff (10 St. pro Pack),',
    ],

    // By default occurances of an option name in the article name are removed.
    // If an option replacement is defined here for the particular option, the
    // occurance of the option name gets replaced with the string defined here.

    // NOTE: Since we use the new API property PARENT_NAME now, we do not have
    // to replace options in product names any longer, so this setting is not
    // used any more.
    'option_replacements'       => [
        'Postless Deck'    => 'Deck',
        'Series Deck'      => 'Deck',
        'Single Coil Deck' => 'Deck',
        'Velocity Deck'    => 'Deck',
    ],

    'products_without_brand' => [
        'Keramik Multifunktionspinzette Tweezer V8',
        'Tasche mit Schulterriemen',
        'Tasche mit Griff',
        'Multifunktionstasche',
        'Keramik Multifunktionspinzette Tweezer V8 schwarz',
        'Celluloid Mundstücke  (5 Stück pro Packung)',
        'Edelstahl Mundstücke S1Z (5 Stück pro Packung)',
        'Kunststoff Mundstücke  (5 Stück pro Packung)',
    ],

    'product_names_direct' => [
    ],

    'product_name_replacements' => [
        'preg_replace' => [
            '~(Elli)´s~'                                                 => 'Elli\'s',
            '~(Roofy)`s~'                                                => 'Roofy\'s',
            '~(Manta) (Glastank)~'                                       => '$1 RTA $2',
            '~(Manta) Bubble (Glastank)~'                                => '$1 RTA $2',
            '~(Coilology.*(4|7) in 1) (Set)~'                            => '$1 Coil-$3',
            '~Aster$~'                                                   => 'Aster 75 Watt',
            '~(Nautilus X Mundstück)e~'                                  => '$1',
            '~80er (Mesh Wire) (1,5 m)~'                                 => '$1 - $2',
            '~100er (Mesh Wire) (1,5 m)~'                                => '$1 - $2',
            '~150er (Mesh Wire) (1,5 m)~'                                => '$1 - $2',
            '~(D19.*O-Ringe)~'                                           => 'Exceed $1',
            '~(D22.*O-Ringe)~'                                           => 'Exceed $1',
            '~(Exceed) Box~'                                             => 'Exceed D22',
            '~((1 Liter)|(\d+ ml)) (Basis)~'                             => '$4 - $1',
            '~1 Liter~'                                                  => '1.000 ml',
            '~E-Zigaretten (Liquid)~'                                    => '- $1',
            '~-( - Liquid)~'                                             => '$1',
            '~(Liquid) für E-Zigaretten~'                                => '$1',
            '~(Shortz.*) - (0 mg/ml)~'                                   => '$1 - 50 ml, $2',
            '~(Koncept XIX.*) (0 mg/ml)~'                                => '$1 - 50 ml, $2',
            '~EZ.WATT~'                                                  => 'EZ.Watt',
            '~-(\d+) ml~'                                                => '- $1 ml',
            '~ (\d+) mAh~'                                               => ' - $1 mAh',
            '~(\d{2})VG */ *(\d{2})PG~'                                  => '- VG/PG: $1/$2,',
            '~(\d{2})PG */ *(\d{2})VG~'                                  => '- VG/PG: $2/$1,',
            '~(\d)(\d{3}) mAh~'                                          => '$1.$2 mAh',
            '~([^,\-]) (\d) m$~'                                         => '$1 - $2 m',
            '~([^,\-]) (\d,\d+) Ohm~'                                    => '$1 - $2 Ohm',
            '~, (\d,\d+ Ohm) Heads?~'                                    => ' Heads, $1',
            '~ (\d+) Watt~'                                              => ' - $1 Watt',
            '~ml - (\d)~'                                                => 'ml, $1',
            '~(Engine 2) Ersatzglas~'                                    => '$1 RTA Glastank',
            '~(KFB 2 AIO) Ersatzglas~'                                   => '$1 Glastank',
            '~([^,\-]) (\d(,\d+)?) ?ml~'                                 => '$1, $2 ml',
            '~(\d+)ML(.*Leerflasche)~'                                   => '$2, $1 ml',
            '~([^,\-]) (\d+) ml$~'                                       => '$1 - $2 ml',
            '~([^,\-]) (\d+) mg\/ml$~'                                   => '$1 - $2 mg/ml',
            '~(0 mg/ml) - (\d+ ml)~'                                     => '$2, $1',
            '~(\d+ ml) - (\d+ mg/ml)~'                                   => '$1, $2',
            '~(\d+ mg/ml),? (\d+ ml)~'                                   => '$2, $1',
            '~([^,\-]) (\d+ ml, \d+ mg/ml)~'                             => '$1 - $2',
            '~(Treib.*100 ml$)~'                                         => '$1, 0 mg/ml',
            '~(Elli\'s Aromen) (- Aroma)(.*)(- \d+ ml)~'                 => '$1 - $3 $2 $4',
            '~(WSY) (- Aroma)(.*)(- \d+ ml)~'                            => '$1 - $3 $2 $4',
            '~(Archangel) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(5Elements) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(Frankonia) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(Demons) (- Aroma)(.*)(- \d+ ml)~'                         => '$1 - $3 $2 $4',
            '~(Kaori) (- Aroma)(.*)(- \d+ ml)~'                          => '$1 - $3 $2 $4',
            '~(Captain Dolly) (- Aroma)(.*)(- \d+ ml)~'                  => '$1 - $3 $2 $4',
            '~(Roofy\'s) (- Aroma)(.*)(- \d+ ml)~'                       => '$1 - $3 $2 $4',
            '~(Vape Rebelz) (- Aroma)(.*)(- \d+ ml)~'                    => '$1 - $3 $2 $4',
            '~(Mùa) (- Aroma)(.*)(- \d+ ml)~'                            => '$1 - $3 $2 $4',
            '~(Arschkalt) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(Yankee Juice - Sweets) (- Aroma)(.*)(- \d+ ml)~'          => '$1 - $3 $2 $4',
            '~(Dutty Juice) (- Aroma)(.*)(- \d+ ml)~'                    => '$1 - $3 $2 $4',
            '~(Flavour Trade) (- Aroma)(.*)(- \d+ ml)~'                  => '$1 - $3 $2 $4',
            '~(Foozy Juice) (- Aroma)(.*)(- \d+ ml)~'                    => '$1 - $3 $2 $4',
            '~(TNYVPS) (- Aroma)(.*)(- \d+ ml)~'                         => '$1 - $3 $2 $4',
            '~(Mr\. Niks) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(7 Todsünden) (- Aroma)(.*)(- \d+ ml)~'                    => '$1 - $3 $2 $4',
            '~(Twenty Eight Monkeys) (- Aroma)(.*)(- \d+ ml)~'           => '$1 - $3 $2 $4',
            '~(Mule Fuel) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(Shark Attack) (- Aroma)(.*)(- \d+ ml)~'                   => '$1 - $3 $2 $4',
            '~(Military) (- Aroma)(.*)(- \d+ ml)~'                       => '$1 - $3 $2 $4',
            '~(Tobacco Time) (- Aroma)(.*)(- \d+ ml)~'                   => '$1 - $3 $2 $4',
            '~(Bozz Liquids) (- Aroma)(.*)(- \d+ ml)~'                   => '$1 - $3 $2 $4',
            '~(Vapors Line) (- Aroma)(.*)(- \d+ ml)~'                    => '$1 - $3 $2 $4',
            '~(VapeHansa) (- Aroma)(.*) (- \d+ ml)~'                     => '$1 - $3 $2 $4',
            '~(Flavorist) (- Aroma)(.*)(- \d+ ml)~'                      => '$1 - $3 $2 $4',
            '~(VapeTastic -) (Aroma) - (.*)(- \d+ ml)~'                  => '$1 $3 - $2 $4',
            '~(Aroma Blood Sukka$)~'                                     => '$1 - 30 ml',
            '~(Vampire Vape) - (Aroma)(.*)(- \d+ ml)~'                   => '$1 - $3 - $2 $4',
            '~(Twisted) - (Peng Juice) (Aroma)(.*)(- \d+ ml)~'           => '$1 - $2 $4 - $3 $5',
            '~Okolom~'                                                   => 'Lomoko',
            '~Vape( -)?( Aroma)(.*)(- \d+ ml)~'                          => 'Vape - $3 -$2 $4',
            '~(Vampire Vape) ([^\-])~'                                   => '$1 - $2',
            '~(VLADS VG) Liquid (-.*)~'                                  => '$1 $2 - Liquid',
            '~(Bull) (- Aroma)(.*)(- \d+ ml)~'                           => '$1 - $3 $2 $4',
            '~(Remedy) - Remedy~'                                        => '$1',
            '~(5 Stars Peine.*) (- Aroma)(.*)(-|,)?( \d+ ml)~'           => '$1 - $3 $2 -$5',
            '~(5 Stars Peine) (- .* Edition)~'                           => '$1 - $2 -',
            '~,( - Aroma - 9 ml)~'                                       => '$1',
            '~(SC -) (Aroma) (.*)~'                                      => '$1 $3 - $2',
            '~- Twisted (Aroma) - (.*)(- \d+ ml)~'                       => '- $2 - $1 $3',
            '~(VC4) 4~'                                                  => '$1',
            '~(MC1) - 1 Schacht~'                                        => '$1',
            '~(I VG - )(Aroma) (.*)(- \d+ ml)~'                          => '$1 $3 - $2 $4',
            '~(PlusSolt).*(\d\d ml) (Nikotinsalz).*(Shot) (- 18 mg/ml)~' => '$1 - $3-$4 - $2 $5',
            '~(Aromamizer Plus)~'                                        => '$1 RDTA',
            '~(Twisted -) (Cryostasis|Road Trip) (Aroma)(.*)(- \d+ ml)~' => '$1 $2 $4 - $3 $5',
            '~((SC)|(InnoCigs))(.*)((- )?(Liquid)|(Aroma))$~'            => '$1$4$6$5 - 10 ml',
            '~(InnoCigs)(.*) Aroma (- Liquid)~'                          => '$1$2 $3',
            '~(SC) (- Vape Base)(.*-)(.*)~'                              => '$1 $3 - $4',
            '~^(Erste Sahne) ([^\-])~'                                   => '$1 - $2',
            '~(Cleaner) (Reinigung)~'                                    => '$1 - $2',
            '~(John Smith.*) (- \d+ ml)~'                                => '$1 - Aroma $2',
            '~Heads~'                                                    => 'Head',
            '~(BVC) Clearomizer (Head)~'                                 => '$1 $2',
            '~((Vape)|(SC)) - (\d+ ml) (Shot) - (.*), (.*)~'             => '$1 - Nikotin-$5 - $6, $4, $7',
            '~(Solt) (\d+ ml) (.*) - (.*), (.*)~'                        => '$1 - $3 - $4, $2, $5',
            '~(Happy Liquid)(.*)~'                                       => '$1$2 - Liquid - 10 ml',
            '~(PlusSolt) (10 ml) (Nikotinsalz) (Shot)  - (\d+ mg/ml)~'   => '$1 $3-$4 - $2, $5',
            '~(Crown 3 Parallel) ((SUS316)|(Kanthal)) (Head)~'           => '$1 $5',
            '~(.*) (Mignon)(.*) (- .*)~'                                 => '$1 $2 $3 - Akkuzelle $4',
            '~([^\-]) (\d.\d+) (mAh)~'                                   => '$1 - $2 $3',
            '~(Liquid) -$~'                                              => '$1',
            '~(Liquid)$~'                                                => '$1 - 10 ml',
            '~(Illusions - Beyond Series.*50 ml)~'                       => '$1, 0 mg/ml',
            '~(\d+(\.\d+)? ml, 0 mg/ml)$~'                               => '- Shake & Vape - $1',
            '~(Chicken Shop.*) (- 0 mg/ml)~'                             => '$1 - Shake & Vape $2',
            '~(Skull Plus.*) - 0 mg/ml~'                                 => '$1 - Shake & Vape - 100 ml, 0 mg/ml',
            '~(Koncept XIX.*) - (50 ml)~'                                => '$1 - Shake & Vape - 50 ml, 0 mg/ml',
            '~(Disco Juice.*) (- 0 mg/ml)~'                              => '$1 - Shake & Vape $2',
            '~(Dr\. Frost.*) (- 0 mg/ml)~'                               => '$1 - Shake & Vape $2',
            '~(Basis -) - Shake \& Vape -~'                              => '$1',
            '~([^,\-]) (\d m)~'                                          => '$1, $2',
            '~Clearomizer (Head)~'                                       => '$1',
            '~Clearomizer Ständer~'                                      => 'Verdampferständer',
            '~(Aspire) (INR) (\d{5})er - (\d\.\d{3} mAh)~'               => '$1 - Akkuzelle - $3, $4',
            '~(iJoy) (21700) Akku - (.*)~'                               => '$1 - Akkuzelle - $2, $3',
            '~EVO~'                                                      => 'Evo',
            '~SINUOUS~'                                                  => 'Sinuous',
            '~POD~'                                                      => 'Pod',
            '~GNOME~'                                                    => 'Gnome',
            '~ Core Dual ~'                                              => ' ',
            '~ Core ~'                                                   => ' ',
            '~Basis~'                                                    => 'Base',
            '~(Afternoon) Vanille-Käsekuchen~'                           => '$1',
            '~(Always) Cola~'                                            => '$1',
            '~(Angels in Heaven) Tabak~'                                 => '$1',
            '~(Blue Spot) Blaubeeren~'                                   => '$1',
            '~(Brown Nutty) Nougat~'                                     => '$1',
            '~(Caribbean) Kokos-Schokoladen~'                            => '$1',
            '~(Celestial Dragon) Tabak~'                                 => '$1',
            '~(Cold Vacci) Heidelbeere-Fresh~'                           => '$1',
            '~(Commander Joe) Tabak~'                                    => '$1',
            '~(Devils Darling) Tabak~'                                   => '$1',
            '~(First Man) Apfel~'                                        => '$1',
            '~(First Money) Orangenlimonade~'                            => '$1',
            '~(Green Angry) Limetten~'                                   => '$1',
            '~(Hairy Fluffy) Pfirsich~'                                  => '$1',
            '~(Inside Red) Wassermelonen~'                               => '$1',
            '~(La Renaissance) Tabak-Schokoladen~'                       => '$1',
            '~(Little Soft) Himbeer~'                                    => '$1',
            '~(Master Wood) Waldmeister~'                                => '$1',
            '~(Milli) Vanille~'                                          => '$1',
            '~(Monkey Around) Bananen-Amarenakirsche~'                   => '$1',
            '~(Pretty Sweetheart) Sahne-Erdbeer~'                        => '$1',
            '~(Red Cyclone) Rote Früchte~'                               => '$1',
            '~(Red Violet) Amarenakirsche~'                              => '$1',
            '~(Rounded Yellow) Honigmelonen~'                            => '$1',
            '~(Spiky) Maracuja~'                                         => '$1',
            '~(Star Spangled) Tabak~'                                    => '$1',
            '~(Sweetheart) Erdbeer~'                                     => '$1',
            '~(The Empire) Tabak Nuss~'                                  => '$1',
            '~(It).*(Apple Pie)~'                                        => '$1\'s $2',
            '~(King)s (Fool)~'                                           => '$1\'s $2',
            '~(Nebelfee)(.*)?(s Milk)~'                                  => '$1\'$3',
            '~(Father)s (Milk)~'                                         => '$1\'s $2',
            '~(Smooth) Weston~'                                          => '$1 Western',
            '~(Ice) (Frappe)~'                                           => '$1d $2',
            '~(Pipes Best) Tabak~'                                       => '$1',
            '~(Desert Safari) Tabak~'                                    => '$1',
            '~(Delicate Mild) Tabak~'                                    => '$1',
            '~(Taste of America) Tabak~'                                 => '$1',
            '~(The Rebels) Tabak Vanille~'                               => '$1',
            '~(White Glacier) Fresh~'                                    => '$1',
            '~(Wild West) Tabakaroma~'                                   => '$1',
            '~(Virginias Best) Tabak~'                                   => '$1',
            '~(Virginas Best) Tabak~'                                    => '$1',
            '~(Strong Taste) Tabak~'                                     => '$1',
            '~(RY4) Tabak~'                                              => '$1',
            '~(Pure) Tabakaroma~'                                        => '$1',
            '~(America\'s Finest) Tabak~'                                => '$1',
            '~(Gentleman)’(s Cloud) Tabak~'                              => '$1\'$2',
            '~(MyWay) Pfeifentabak~'                                     => '$1',
            '~(Shaken, not stirred) Orangen~'                            => '$1',
            '~(Stirred, not )S(haken) Mango~'                            => '$1s$2',
            '~(Black Tie) Tabak~'                                        => '$1',
            '~(Courtesy of the Kings) Minze-Schokoladen~'                => '$1',
            '~(Lady-Like) Früchtemix~'                                   => '$1',
            '~(Kings Dessert) Crème Brûlée~'                             => '$1',
            '~(Atlantis Luxury) Tequila Sunrise~'                        => '$1',
            '~(My Island) Virgin Colada~'                                => '$1',
            '~(Mystery Fruits) Kaktusfeige~'                             => '$1',
            '~(Babette)’s~'                                              => '$1\'s',

            '~(ProC)\d(-S)?~'                                     => '$1',
            '~E-Zigaretten Nikotinsalz Liquid~'                   => 'Nikotinsalz-Liquid',
            '~E-Zigaretten Starter Set~'                          => 'E-Zigarette',
            '~(Anniversary)-(Edition) (E-Zigarette)~'             => '$1 $2 - $3',
            '~E-Zigaretten Set~'                                  => 'E-Zigarette',
            '~E-Zigaretten-Set~'                                  => 'E-Zigarette',
            '~(J-Easy)((3)|(9))~'                                 => '$1 $2',
            '~Nautilus Mini BVC Clearomizer~'                     => 'Nautilus Mini Clearomizer',
            '~Clearomizer( Set)?~'                                => 'Verdampfer',
            '~Glastank und Mundstück Set~'                        => 'Glastank + Mundstück (Set)',
            '~Tank (Verdampfer)~'                                 => '$1',
            '~Ersatz-Dichtung~'                                   => 'Ersatzdichtung',
            '~Dichtungs-Set~'                                     => 'Ersatzdichtungen',
            '~Heads Heads~'                                       => 'Heads',
            '~Mr\. Niks~'                                         => 'Mr. Nik\'s',
            '~reds Apple EJuice~'                                 => 'Red\'s Apple Juice',
            '~mit -~'                                             => 'mit',
            '~mit D22 ~'                                          => '',
            '~Pro P~'                                             => 'pro P',
            '~(pro Pack)[^u]~'                                    => '$1ung)',
            '~St. pro~'                                           => 'Stück pro',
            '~5er Pack~'                                          => '5 Stück pro Packung',
            '~10er Packung~'                                      => '(10 Stück pro Packung)',
            '~(Dual Coil), (1,5 Ohm)~'                            => '- $1, $2',
            '~Vape Base~'                                         => 'Shake & Vape',
            '~mAh 40A~'                                           => 'mAh, 40 A',
            '~P80 Watt~'                                          => 'P80 - 80 Watt',
            '~\+ Adapter~'                                        => ', mit Adapter',
            '~Limited Edition - 30 ml~'                           => 'Limited Edition - Aroma - 30 ml',
            '~(Pod) mit (Head)~'                                  => '$1 inkl. $2',
            '~6 in 1 Head Set~'                                   => 'Coil Set (20 Stück, 6 Varianten)',
            '~Base - Shake \& Vape -~'                            => 'Base -',
            '~(Glastank),? (\d+ ml)~'                             => '$1 - $2',
            '~(Head) - (ARC)~'                                    => '$2 $1 -',
            '~(Hookah) (Set)~'                                    => '$1 ($2)',
            '~(Zelos) - 5~'                                       => '$1 - Akku - 5',
            '~(iStick Nowos) (- \d\.\d+ mAh)~'                    => '$1 - Akku $2',
            '~(Typhon) (- \d+ Watt)~'                             => '$1 - Akku $2',
            '~(Amnis) (- \d+ mAh)~'                               => '$1 - Akku $2',
            '~(X-Priv Baby) (- \d\.\d+ mAh)~'                     => '$1 - Akku $2',
            '~(Aegis Mini) (- \d\.\d+ mAh)~'                      => '$1 - Akku $2',
            '~(Drag Mini) (- \d\.\d+ mAh)~'                       => '$1 - Akku $2',
            '~(Mag Baby) (- \d+ Watt)~'                           => '$1 - Akku $2',
            //            '~(Compact 14) (Akku)~'                                  => '$1 - $2',
            '~(Pumper.*) (- \d+ Watt)~'                           => '$1 - Squonker Box $2',
            '~(Blocks.*) (\d+ Watt)~'                             => '$1 - Squonker Box - $2',
            '~(Pumper)-~'                                         => '$1 ',
            '~(Basal) (Akku)~'                                    => '$1 - $2',
            '~(J-Easy \d) (Akku)~'                                => '$1 - $2',
            '~(RX Gen3)~'                                         => 'Reuleaux RX Gen3',
            '~(RX GEN3)~'                                         => 'RX Gen3',
            '~(Lux) 200~'                                         => '$1',
            '~(VX200) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Druga Foxy) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(X217) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Topside Dual) (- \d+ Watt)~'                       => '$1 - Akkuträger $2',
            '~(Lux) (- \d+ Watt)~'                                => '$1 - Akkuträger $2',
            '~(ECO) (- \d+ Watt)~'                                => '$1 - Akkuträger $2',
            '~(ECO Pro) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Helix) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Reuleaux RX Gen3) (- \d+ Watt)~'                   => '$1 - Akkuträger $2',
            '~(Speeder) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Cut Premium) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Rage) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(eMASK) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Valyrian 2) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(Soulkeeper) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(Titan PWM) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Crown 4) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(x Ultroner EOS II) (- \d+ Watt)~'                  => '$1 - Akkuträger $2',
            '~(SkyStar) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Mag Grip) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Puxos) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Feedlink) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Dynamo) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Colossal) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Minikin.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Lustro) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Amighty) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Puma) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(V-IT) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Invoke) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(iKonn) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Lexicon) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Lucid) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(iStick .*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Aegis Legend.*) (- \d+ Watt)~'                     => '$1 - Akkuträger $2',
            '~(Edge.*) (- \d+ Watt)~'                             => '$1 - Akkuträger $2',
            '~(Nova) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Espion.*) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(eVic Primo SE) (- \d+ Watt)~'                      => '$1 - Akkuträger $2',
            '~([GXTH]-Priv( 2)?) (- \d+ Watt)~'                   => '$1 - Akkuträger $3',
            '~(G-Priv Baby) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Ironfist) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Hypercar) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Nunchaku) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Ultex T80) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Luxe) (- \d+ Watt)~'                               => '$1 - Akkuträger $2',
            '~(Polar) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Species) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Sinuous.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Revenger.*) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(SX Mini.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(VK530.*) (- \d+ Watt)~'                            => '$1 - Akkuträger $2',
            '~(Subverter 1.*) (- \d+ Watt)~'                      => '$1 - Akkuträger $2',
            '~(Drag 2.*) (- \d+ Watt)~'                           => '$1 - Akkuträger $2',
            '~(Delta) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(iJust 21700) (- \d+ Watt)~'                        => '$1 - Akkuträger $2',
            '~(Reuleaux.*) (- \d+ Watt)~'                         => '$1 - Akkuträger $2',
            '~(CB-80) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Luxotic.*) (- \d+ Watt)~'                          => '$1 - Akkuträger $2',
            '~(Medea) (- \d+ Watt)~'                              => '$1 - Akkuträger $2',
            '~(Aster)~'                                           => '$1 - Akkuträger - 75 Watt',
            '~OSUB (King) (- \d+ Watt)~'                          => 'Osub $1 - Akkuträger $2',
            '~(Dichtung) (Set)~'                                  => 'Ersatzdichtungen',
            '~(Head) \((Dual Coil)\)~'                            => '$2 $1',
            '~(\d,\d+ Ohm) (Head)~'                               => '$2 - $1',
            '~(iKonn) 220~'                                       => '$1',
            '~(Melo \d) D(\d\d) ((Verdampfer)|(Glastank))~'       => '$1 - $3 - $2 mm',
            '~(IM4) - (Head)~'                                    => 'IM4 Head',
            '~HG2 18650~'                                         => 'INR18650HG2 - Akkuzelle',
            '~(VTC((6)|(5A)))~'                                   => '$1 - Akkuzelle',
            '~(INR18650-((25R)|(30Q)))~'                          => '$1 - Akkuzelle',
            '~\(Panasonic\) (NCR20700B)~'                         => '$1 - Akkuzelle',
            '~(\d{5})er( Akku)?~'                                 => '$1 - Akkuzelle',
            '~Akkuzellebox~'                                      => 'Akkubox',
            '~(Easy 3) (Caps) (.*) \(~'                           => '$1 $3 - $2 (',
            '~(Sweetheart)e~'                                     => '$1',
            '~(Devil)s (Darling)~'                                => '$1\'s $2',
            '~(Prince)-((X6)|(M4)|(T10)|(Q4))~'                   => '$1 $2',
            '~(SMOK) (V8)~'                                       => '$1 TF$2',
            '~((vPipe III)|(Zen Pipe)) (Set)~'                    => '$1 - E-Pfeife (Set)',
            '~(Pod) mit Head -~'                                  => '$1 -',
            '~(Pod) mit~'                                         => '$1 -',
            '~(Watt)s$~'                                          => '$1',
            '~(Batterie)-H(ülse)~'                                => '$1h$2',
            '~(Batterie)-K(appe)~'                                => '$1k$2',
            '~mit (Revvo Boost)~'                                 => '$1',
            '~Ta (Baby)~'                                         => 'Tarot $1',
            '~(ClouDrippin’ Psychedelic Edition) (.*) (- Aroma)~' => '$2 - $1 $3',
            '~(20700/21700) (Batteriekappe)~'                     => '$2 - $1',
            '~(GTM?\d)( Coil)? (Head)~'                           => '$1 - $3',
            '~[Cc][Cc][eE][lL][lL]~'                              => 'cCell',
            '~(cCell) Coil (Head)~'                               => '$1 - $2',
            '~Geekvape~'                                          => 'GeekVape',
            '~(GeekVape) ([^\-])~'                                => '$1 - $2',
            '~2 in 1 Set~'                                        => '(2 Stück pro Packung)',
            '~2 in 1 (Clapton Head) Set~'                         => '$1 (2 Stück pro Packung)',
            '~(18650)(VTC)~'                                      => '$1 $2',
            '~((18650)|(21700)|(26650)) - (Akku((zelle)|(box)))~' => '$5 - $1',
            '~((18650)|(21700)|(26650)) - (\d\.\d\d\d)~'          => '$1, $5',
            '~(John Smith)s~'                                     => '$1\'s',
            '~(N\d\d ((Framed)|(Fused)) Clapton) Head~'           => '$1 Coil',
            '~(Metal Edition) (E-Zigarette)~'                     => '$1 - $2',
            '~(0,2 Ohm) (Mesh Head)~'                             => '$2 - $1',
        ],
    ],
    'product_names'             => [
        'Advken'        => [
            '~(Twirl RDA)~',
            '~(Manta RTA)~',
            '~(Owl)~',
        ],
        'Aspire'        => [
            // Aspire
            '~(Reax Mini)~',
            '~(Nepho)~',
            '~(Athos)~',
            '~(Dynamo)~',
            '~(Atlantis Evo)~',
            '~(PockeX)~',
            '~((Cobble)( AIO)?)~',
            '~((Spryte)( AIO)?)~',
            '~(Proteus)~',
            '~(Typhon)~',
            '~(Cygnet)~',
            '~(Speeder)~',
            '~(Puxos)~',
            '~(Tigon)~',
            '~((Triton)( 2)?)~',
            '~((Breeze)( 2)?)~',
            '~((Zelos)( 2.0)?)~',
            '~(Revvo(( Mini)|( Boost))?)~',
            '~(Nautilus(( 2S?)|( X)|( Mini)|( AIO))?)~',
            '~(Cleito(( 120)?( Pro)?)?)~',
            '~(SkyStar)~',
            '~(Feedlink)~',
            '~((Revvo)( Mini)?)~',
            '~((K1 Plus)|(K1 Stealth)|((K\d)( \& K3)?))~',
            '~(AVP)~',
        ],
        'asMODus'       => [
            '~((Minikin V3S mit Viento)|(Minikin(( V2 Kodama)|( V2)|( V3S)|( V3)|( Reborn))?))~',
            '~(C4 RDA)~',
            '~(Colossal)~',
            '~(Pumper 18/21)~',
            '~(Lustro)~',
            '~(Bunker RDA)~',
            '~(Nefarius RDTA)~',
            '~(Voluna V2 RTA)~',
            '~(X VapePorn Vice RDA)~',
            '~((Amighty mit Viento)|(Amighty)|(Viento))~',
            '~(X VapersMD Dawg RTA)~',
            '~(\.Blank RDA)~',
        ],
        'Augvape'       => [
            '~(Intake RTA)~',
            '~(Templar RDA)~',
            '~(Occula RDA)~',
            '~(Skynet( Pro)?)~',
        ],
        'CoilArt'       => [
            '~(Mage RTA V2)~',
            '~(Lux( Mesh)?)~',
            '~(Mino)~',
        ],
        'Cthulhu'       => [
            '~(Iris Mesh RDA)~',
            '~(1928 MTL RDA)~',
            '~(Hastur(( MTL RTA Mini)|( MTL RDA))?)~',
            '~(Zathog RDA)~',
            '~(Mjölnir RDA)~',
            //            '~(Hastur)~',
            '~(Furai 510)~',
        ],
        'Desire Design' => [
            '~(Cut Premium)~',
            '~(Rage)~',
            '~(Bulldog)~',
        ],
        'Digiflavor'    => [
            '~(Siren 2 RTA)~',
            '~(Drop RDA)~',
            '~(Drop Solo RDA)~',
            '~(Edge)~',
            '~(Helix)~',
        ],
        'Ehpro'         => [
            '~(Panther RDA)~',
        ],
        'FreeMax'       => [
            '~(Twister mit Fireluke 2)~',
            '~(Fireluke 2)~',
            '~(Fireluke Mesh)~',
            '~(M Pro)~',
        ],
        'GeekVape'      => [
            '~(Alpha)~',
            '~(Ammit 25 RTA)~',
            '~(Baron RDA)~',
            '~(Blitzen RTA)~',
            '~(Ammit MTL RTA)~',
            '~(Tengu RDA)~',
            '~(Creed RTA)~',
            '~(Zeus X RTA)~',
            '~(Zeus Dual RTA)~',
            '~(Zeus RTA)~',
            '~(Ammit Dual Coil RTA)~',
            '~(Aegis(( Legend)|( Mini))?)~',
            '~(Aero Mesh)~',
            '~(Cerberus)~',
            '~(Creed RTA)~',
            '~(Nova)~',
            '~(Loop( V1.5)? RDA)~',
            '~(Lucid)~',
            '~(Flint)~',
        ],
        'HellVape'      => [
            '~(Anglo RDA)~',
            '~(Dead Rabbit RTA)~',
            '~(Dead Rabbit RDA)~',
            '~(Dead Rabbit SQ RDA)~',
            '~(Drop Dead RDA)~',
            '~(Hellbeast)~',
            '~(Rebirth RDA)~',
            '~(Passage RDA)~',
            '~(Rebirth RTA)~',
        ],
        'Horizontech' => [
          '~(Falcon)~'
        ],
        'iPV'           => [
            '~(V-IT)~',
        ],
        'Nikola'        => [
            '~(Medea)~',
            '~(Lapetus)~',
        ],
        'SC'            => [
            '~(iJust ((21700)|(ECM)|(3))?)~',
            '~(Ello( ((Vate)|(Duro))?))~',
            '~(iCare Flask)~',
            '~(iKuu Lite)~',
            '~(Elven)~',
            '~(Basal)~',
            '~(GS ((Air 2)|(Air 3)|(Air)|(Baby)|(Drive)|(Turbo))?)~',
            '~(iKonn)~',
            '~(Invoke)~',
            '~(iStick ((Melo)|(Amnis)|(Pico X)|(Pico 21700)|(Pico Baby)|(Pico S)|(Pico)|(Trim)|(Nowos))?)~',
            '~(iWu)~',
            '~(Lexicon)~',
            '~(Melo \d)~',
            '~(Easy 3)~',
        ],
        'Innokin'       => [
            '~(Endura ((T18)|(T20S)|(T22))?)~',
            '~(Prism ((S)|(T18/T22)|(T18)|(T20)|(T22))?)~',
            '~(Proton)~',
            '~(EZ.Watt)~',
        ],
        'InnoCigs'      => [
            '~(Batpack)~',
            '~(Atopack( Magic)?)~',
            '~(Cubis 2)~',
            '~(Cubis Max)~',
            '~(RunAbout)~',
            '~((eGo AIO) (Mansion)?)~',
            '~(Espion (Infinite AI)|(Infinite)|(Silk)|(Solo)|(Tour))~',
            '~(eVic Primo Fit)~',
            '~(Ultex T80)~',
            '~(NCFilm Heizplatte)~',
            '~(Exceed (Air)|(D19)|(D22)|(Edge)|(Grip))~',
            '~(Notchcore)~',
            '~(Presence)~',
            '~(ProCore (Air Plus)|(Air)|(Conquer)|(Remix)|(X))~',
            '~(Riftcore Duo)~',
            '~(Teros)~',
            '~(Unimax 22)~',
        ],
        'JustFog'       => [
            '~(C601)~',
            '~(Fog1)~',
            '~(J-Easy3)~',
            '~(Minifit)~',
            '~(Compact 14)~',
            '~(P16A)~',
            '~(Q14)~',
            '~(Q16 C)~',
        ],
        'Lost Vape'     => [
            '~(Original Q)~',
            '~(Lyra)~',
        ],
        'OBS'           => [
            '~(Crius 2 RTA)~',
            '~(Engine 2( RTA)?)~',
            '~(KFB 2 AIO)~',
            '~(Engine MTL)~',
            '~(Cheetah 3 RDA)~',
            '~(Cube(( Mini)|( MTL))?)~',
        ],
        'Smok'          => [
            '~(G-Priv ((2)|(Baby)))~',
            '~(Globe)~',
            '~((Vape Pen Nord(( 19)|( 22))?)|(Nord(( AIO 19)|( AIO 22))?))~',
            '~(H-Priv 2)~',
            '~(Mag Baby)~',
            '~(Micro One)~',
            '~(Osub King)~',
            '~(Priv M17)~',
            '~(QBox)~',
            '~(R-Kiss)~',
            '~(R40)~',
            '~(Stick)~',
            '~(T-Priv)~',
            '~(X-Priv( Baby)?)~',
            '~(TFV12((-P)|( Baby Prince)|( Prince))?)~',
            '~(TFV8 ((Baby)|(X-Baby))?)~',
            '~(Baby V2)~',
            '~(Species)~',
            '~(Mico)~',

        ],
        'Renova'        => [
            '~(Zero)~',
        ],
        'Revenant Vape' => [
            '~(Delta)~',
        ],
        'Sigelei'       => [
            '~(Chronus mit Shikra)~',
            '~(Sibra E2)~',
            '~(Sibra F)~',
            '~(Sobra)~',
            '~(Moonshot 120)~',
            '~(Wolf Mini)~',
        ],
        'Smoant'        => [
            '~(Battlestar Squonker( RDA)?)~',
        ],
        'Steamax'       => [
            // Smok
            '~(G-Priv ((2)|(Baby)))~',
            '~(Globe)~',
            '~(Nord)~',
            '~(R-Kiss)~',
            '~(H-Priv 2)~',
            '~(Mag Baby)~',
            '~(Micro One)~',
            '~(Osub King)~',
            '~(Priv M17)~',
            '~(QBox)~',
            '~(R40)~',
            '~(Stick)~',
            '~(T-Priv)~',
            '~(X-Priv( Baby)?)~',
            '~(TFV12 ((Baby Prince)|(Prince))?)~',
            '~(TFV8 ((Baby)|(X-Baby))?)~',
            '~(Baby V2)~',
            '~(Species)~',

            // Wismec
            '~(Amor NS Pro)~',
            '~(Amor NSE)~',
            '~(Column)~',
            '~(Divider)~',
            '~(Elabo Mini)~',
            '~(Gnome( King)?)~',
            '~(Guillotine V2)~',
            '~(Luxotic BF Box)~',
            '~(Luxotic MF Box)~',
            '~(Luxotic DF Box)~',
            '~(Luxotic NC)~',
            '~(Motiv 2)~',
            '~(Reuleaux RX Gen3 Dual)~',
            '~(Reuleaux Tinker)~',
            '~(Sinuous(( V200)|( P80)|( V80)|( Ravage)|( SW)|( Solo))?)~',
            '~(Reux)~',

        ],
        'Steam Crave'   => [
            '~(Aromamizer Plus RDTA)~',
            '~(Aromamizer Supreme RDTA V2(\.1)?)~',
            '~(Aromamizer Titan RDTA)~',
            '~(Aromamizer Lite RTA)~',
            '~(Glaz RDSA)~',
            '~(Mico)~',
            '~(Glaz RTA)~',
        ],
        'Uwell'         => [
            '~(Crown (3|4))~',
            '~(Fancier RTA)~',
            '~(Hypercar)~',
            '~(Ironfist)~',
            '~(Nunchaku( RDA)?)~',
            '~(Valyrian( 2)?)~',
            '~(Blocks)~',
            '~(Whirl(( 20)|( 22))?)~',
            '~(Caliburn)~',

        ],
        'Vapanion'      => [
            '~(Cascade(( Baby SE)|( Baby)|( One Plus)|( One))?)~',
            '~(NRG( SE)?)~',
            '~(Switcher( LE)?)~',

        ],
        'VapeOnly'      => [
            '~(vPipe III)~',
            '~(Zen Pipe)~',
        ],
        'VooPoo'        => [
            '~(Drag 2)~',
            '~(Drag Mini)~',
            '~(X217)~',
        ],
        'Vaporesso'     => [
            '~(Cascade(( One Plus SE)|( One Plus)|( One)|( Baby SE))?)~',
            '~(Sky Solo( Plus)?)~',
            '~(Aurora Play)~',
            '~(Luxe( S)?)~',
            '~(NRG)~',
            '~(Orca Solo)~',
            '~(Polar)~',
            '~(Revenger X)~',
            '~(SKRR(-S Mini)?)~',
            '~(Tarot Baby)~',
            '~(Veco)~',
            '~(Zero)~',
        ],
        'Vapor Storm'   => [
            '~(Puma)~',
            '~(Subverter 1)~',
            '~(ECO( Pro)?)~',
            '~(Lion RDA)~',
        ],
        'Vsticking'     => [
            '~(VK530)~',
            '~(VIY)~',
        ],
        'Vzone'         => [
            '~(Scado)~',
            '~(eMASK)~',
            '~(Vlit Preco)~',
            '~(Preco( Plus)?)~',
            '~(Vlit Vowl 40)~',
        ],
        'Wismec'        => [
            '~(Tobhino BF RDA)~',
            '~(Amor NS Pro)~',
            '~(Amor NSE)~',
            '~(Column)~',
            '~(Divider)~',
            '~(Elabo Mini)~',
            '~(Gnome( King)?)~',
            '~(Guillotine V2)~',
            '~(Luxotic BF Box)~',
            '~(Luxotic MF Box)~',
            '~(Luxotic DF Box)~',
            '~(Luxotic NC)~',
            '~(Motiv 2)~',
            '~(Reuleaux RX Gen3 Dual)~',
            '~(Sinuous(( P80)|( V80)|( Ravage)|( SW))?)~',
            '~(Reux)~',
        ],
        'Wotofo'        => [
            '~(Warrior RDA)~',
            '~(Recurve RDA)~',
        ],
        'XTAR'          => [
            '~(Queen ANT MC6C)~',
            '~(VC4)~',
            '~(MC1)~',
            '~(MC2 Plus)~',
            '~(PB2)~',
            '~(VC2S)~',
        ],
        'Yihi'          => [
            '~(SX Mini Mi Class)~',
            '~(SX Mini SL Class)~',
            '~(SX Mini X Class)~',
        ],
        'ZQ'            => [
            '~(Vi)~',
        ],

    ],

    'innocigs_brands' => ['SC', 'Steamax', 'InnoCigs', 'Innocigs'],
];