<?php
return [
    'article_name_option_fixes'     => [
        'prisma-blau'       => 'blau-prisma',
        'prisma-chrom'      => 'chrom-prisma',
        'prisma-gold'       => 'gold-prisma',
        'prisma-regenbogen' => 'regenbogen-prisma',
        'prisma-rot'        => 'rot-prisma',
        'prisma-gunmetal'   => 'gunmetal-prisma',
        '0,4 Ohm'           => '0,4',
        'matt-schwarz'      => 'matt schwarz',
        'schwarz-weiß'      => 'schwarz-weiss',
        'weiß'              => 'weiss',
        '50PG / 50VG'       => [
            '50PG/50VG',
            '50VG/50PG',
            '50VG / 50PG',
        ],
        '28 GA'             => '28GA',
        '26 GA'             => '26GA',
        '24 GA'             => '24GA',
        '22 GA'             => '22GA',
        '24 GA*2+32 GA'     => '24GA*2+32GA',
        '28 GA*2+32 GA'     => '28GA*2+32GA',
        '26 GA+32 GA'       => '26GA+32GA',
    ],

    'articles_without_brand' => [
        'Tasche mit Schulterriemen',
        'Tasche mit Griff',
        'Multifunktionstasche',
        'Keramik Multifunktionspinzette Tweezer V8 schwarz',
        'Celluloid Mundstücke  (5 Stück pro Packung)',
        'Edelstahl Mundstücke S1Z (5 Stück pro Packung)',
        'Kunststoff Mundstücke  (5 Stück pro Packung)',
    ],

    'article_codes'        => [],
    'article_names'        => [
        'Vampire Vape Applelicious - E-Zigaretten Liquid'     => 'Vampire Vape - Applelicious - E-Zigaretten Liquid',
    ],

    'name_prepare' => [
        'preg_replace' => [
            '~\s+~'             => ' ',
            '~(- )+~'           => '$1',
            '~ ,~'              => ',',
            '~, -~'             => '-',
            '~ - ?$~'           => '',
            '~0ml\/ml~'         => '0mg/ml',
            '~(\d+)m~'          => '$1 m',
            '~(\d) mAH~'        => '$1 mAh',
            '~(\d mg)[^\/]~'    => '$1/ml',
            '~Sherbert~'        => 'Sherbet',
            '~Americas~'        => 'America\'s',
            '~(Heads )+~'       => '$1',
            '~(Head )+~'        => '$1',
        ],
    ],

    'name_cleanup' => [
        'preg_replace' => [
            '~\s+~'     => ' ',
            '~(- )+~'   => '$1',
            '~ ,~'      => ',',
            '~, -~'     => '-',
            '~ - ?$~'   => '',
            '~ $~'      => '',
            '~^ ~'      => '',
        ],
    ],

    'article_name_replacements'     => [
        'preg_replace' => [
            '~Aster$~'                                                      => 'Aster 75 Watt',
            '~((1 Liter)|(\d+ ml)) (Basis)~'                                => '$4 - $1',
            '~1 Liter~'                                                     => '1.000 ml',
            '~E-Zigaretten (Liquid)~'                                       => '- $1',
            '~(Liquid) für E-Zigaretten~'                                   => '$1',
            '~Aroma (- Liquid)~'                                            => '$1',
            '~-(\d+) ml~'                                                   => '- $1 ml',
            '~ (\d+) mAh~'                                                  => ' - $1 mAh',
            '~(\d{2})VG */ *(\d{2})PG~'                                     => '- VG/PG: $1:$2,',
            '~(\d{2})PG */ *(\d{2})VG~'                                     => '- VG/PG: $2:$1,',
            '~(\d)(\d{3}) mAh~'                                             => '$1.$2 mAh',
            '~([^,\-]) (\d) m$~'                                            => '$1 - $2 m',
            '~([^,\-]) (\d,\d+) Ohm~'                                       => '$1 - $2 Ohm',
            '~, (\d,\d+ Ohm) Heads?~'                                       => ' Heads, $1',
            '~ (\d+) Watt~'                                                 => ' - $1 Watt',
            '~ml - (\d)~'                                                   => 'ml, $1',
            '~([^,\-]) (\d(,\d+)?) ?ml~'                                    => '$1, $2 ml',
            '~(\d+)ML(.*Leerflasche)~'                                      =>'$2, $1 ml',
            '~([^,\-]) (\d+) ml$~'                                          => '$1 - $2 ml',
            '~([^,\-]) (\d+) mg\/ml$~'                                      => '$1 - $2 mg/ml',
            '~(\d+ mg/ml),? (\d+ ml)~'                                      => '$2, $1',
            '~([^,\-]) (\d+ ml, \d+ mg/ml)~'                                => '$1 - $2',
            '~(Treib.*100 ml$)~'                                            => '$1, 0 mg/ml',
            '~Rebelz (- Aroma)(.*)(- \d+ ml)~'                              => 'Rebelz - $2 $1 $3',
            '~Vape( -)?( Aroma)(.*)(- \d+ ml)~'                             => 'Vape - $3 -$2 $4',
            '~(Vampire Vape) ([^\-])~'                                      => '$1 - $2',
            '~(VLADS VG) Liquid (-.*)~'                                     => '$1 $2 - Liquid',
            '~(Bull) (- Aroma)(.*)(- \d+ ml)~'                              => '$1 - $3 $2 $4',
            '~(SC -) (Aroma) (.*)~'                                         => '$1 $3 - $2',
            '~- Twisted (Aroma) - (.*)(- \d+ ml)~'                          => '- $2 - $1 $3',
            '~(I VG - )(Aroma) (.*)(- \d+ ml)~'                             => '$1 $3 - $2 $4',
            '~(Bozz Liquids -) (Aroma)(.*)(- \d+ ml)~'                      => '$1 $3 - $2 $4',
            '~(Flavorist -) (Aroma)(.*)(- \d+ ml)~'                         => '$1 $3 - $2 $4',
            '~(VapeTastic -) (Aroma) - (.*)(- \d+ ml)~'                     => '$1 $3 - $2 $4',
            '~(Twisted -) (Cryostasis|Road Trip) (Aroma)(.*)(- \d+ ml)~'    => '$1 $2 $4 - $3 $5',
            '~((SC)|(InnoCigs))(.*)((- )?(Liquid)|(Aroma))$~'               => '$1$4$6$5 - 10 ml',
            '~(SC) (- Vape Base)(.*-)(.*)~'                                 => '$1 $3 - $4',
            '~^(Erste Sahne) ([^\-])~'                                      => '$1 - $2',
            '~(John Smith.*) (- \d+ ml)~'                                   => '$1 - Aroma $2',
            '~Heads~'                                                       => 'Head',
            '~(BVC) (Clearomizer) (Head)~'                                  => '$1 $3',
            '~((Vape)|(SC)) - (\d+ ml) (Shot) - (.*), (.*)~'                => '$1 - $5 - $6, $4, $7',
            '~(Solt) (\d+ ml) (.*) - (.*), (.*)~'                           => '$1 - $3 - $4, $2, $5',
            '~(Happy Liquid)(.*)~'                                          => '$1$2 - Liquid - 10 ml',
            '~(PlusSolt) (10 ml) (Nikotinsalz) (Shot)  - (\d+ mg/ml)~'      => '$1 $3-$4 - $2, $5',
            '~(.*) (Mignon)(.*) (- .*)~'                                    => '$1 $2 $3 - Akkuzelle $4',
            '~([^\-]) (\d.\d+) (mAh)~'                                      => '$1 - $2 $3',
            '~(Liquid)$~'                                                   => '$1 - 10 ml',
            '~(- \d+ ml, 0 mg/ml)$~'                                        => '- Shake & Vape - $1',
            '~([^,\-]) (\d m)~'                                             => '$1, $2',
            '~Clearomizer (Head)~'                                          => '$1',
            '~(Aspire) (INR) (\d{5})er - (\d\.\d{3} mAh)~'                  => '$1 - Akkuzelle - $3, $4',
            '~EVO~'                                     => 'Evo',
            '~SINUOUS~'                                 => 'Sinuous',
            '~GNOME~'                                   => 'Gnome',
            '~ Core Dual ~'                             => ' ',
            '~ Core ~'                                  => ' ',
            '~Basis~'                                   => 'Base',
            '~(Afternoon) Vanille-Käsekuchen~'          => '$1',
            '~(Always) Cola~'                           => '$1',
            '~(Angels in Heaven) Tabak~'                => '$1',
            '~(Blue Spot) Blaubeeren~'                  => '$1',
            '~(Brown Nutty) Nougat~'                    => '$1',
            '~(Caribbean) Kokos-Schokoladen~'           => '$1',
            '~(Celestial Dragon) Tabak~'                => '$1',
            '~(Cold Vacci) Heidelbeere-Fresh~'          => '$1',
            '~(Commander Joe) Tabak~'                   => '$1',
            '~(Devils Darling) Tabak~'                  => '$1',
            '~(First Man) Apfel~'                       => '$1',
            '~(First Money) Orangenlimonade~'           => '$1',
            '~(Green Angry) Limetten~'                  => '$1',
            '~(Hairy Fluffy) Pfirsich~'                 => '$1',
            '~(Inside Red) Wassermelonen~'              => '$1',
            '~(La Renaissance) Tabak-Schokoladen~'      => '$1',
            '~(Little Soft) Himbeer~'                   => '$1',
            '~(Master Wood) Waldmeister~'               => '$1',
            '~(Milli) Vanille~'                         => '$1',
            '~(Monkey Around) Bananen-Amarenakirsche~'  => '$1',
            '~(Pretty Sweetheart) Sahne-Erdbeer~'       => '$1',
            '~(Red Cyclone) Rote Früchte~'              => '$1',
            '~(Red Violet) Amarenakirsche~'             => '$1',
            '~(Rounded Yellow) Honigmelonen~'           => '$1',
            '~(Spiky) Maracuja~'                        => '$1',
            '~(Star Spangled) Tabak~'                   => '$1',
            '~(Sweetheart) Erdbeer~'                    => '$1',
            '~(The Empire) Tabak Nuss~'                 => '$1',
            '~(The Rebels) Tabak Vanille~'              => '$1',
            '~(White Glacier) Fresh~'                   => '$1',
            '~(Wild West) Tabakaroma~'                  => '$1',
            '~(Virginias Best) Tabak~'                  => '$1',
            '~(Strong Taste) Tabak~'                    => '$1',
            '~(RY4) Tabak~'                             => '$1',
            '~(Pure) Tabakaroma~'                       => '$1',
            '~(America\'s Finest) Tabak~'               => '$1',
            '~E-Zigaretten Nikotinsalz Liquid~'         => 'Nikotinsalz-Liquid',
            '~E-Zigaretten Starter Set~'                => 'E-Zigarette (Set)',
            '~E-Zigaretten Set~'                        => 'E-Zigarette (Set)',
            '~Clearomizer Set~'                         => 'Clearomizer (Set)',
            '~Glastank und Mundstück Set~'              => 'Glastank + Mundstück (Set)',
            '~Tank (Clearomizer)~'                      => '$1',
            '~Heads Heads~'                             => 'Heads',
            '~AsMODus~'                                 => 'asMODus',
            '~Nautilus Mini BVC Clearomizer~'           => 'Nautilus Mini Clearomizer',
            '~mit -~'                                   => 'mit',
            '~mit D22 ~'                                => '',
            '~Pro P~'                                   => 'pro P',
            '~(pro Pack)[^u]~'                          => '$1ung)',
            '~St. pro~'                                 => 'Stück pro',
            '~5er Pack~'                                => '5 Stück pro Packung',
            '~10er Packung~'                            => '(10 Stück pro Packung)',
            '~(Dual Coil), (1,5 Ohm)~'                  => '- $1, $2',
            '~Vape Base~'                               => 'Shake & Vape',
            '~mAh 40A~'                                 => 'mAh, 40 A',
            '~P80 Watt~'                                => 'P80 - 80 Watt',
            '~\+ Adapter~'                              => ', mit Adapter',
            '~Limited Edition - 30 ml~'                 => 'Limited Edition - Aroma - 30 ml',
            '~Base - Shake \& Vape -~'                  => 'Base -',
            '~(((Single)|(Penta))-Coil) (Head) -~'      => '- $5 - $1,',
            '~(ARC) (Head) -~'                          => '$2 - $1,',
            '~(Kanthal AF) (Tri-Coil) (Head) -~'        => '- $3, $1, $2,',
            '~(BVC) (Head)~'                            => '$2 - $1',
            '~(BVC) (NS) (Head) -~'                     => '$3 - $1 $2,',
            '~(Hookah) (Set)~'                          => '$1 ($2)',
            '~(Zelos) - 5~'                             => '$1 - Akku - 5',
            '~(Typhon) (- \d+ Watt)~'                   => '$1 - Akku $2',
            '~(Speeder) (- \d+ Watt)~'                  => '$1 - Akkuträger $2',
            '~(SkyStar) (- \d+ Watt)~'                  => '$1 - Akkuträger $2',
            '~(Puxos) (- \d+ Watt)~'                    => '$1 - Akkuträger $2',
            '~(Feedlink) (- \d+ Watt)~'                 => '$1 - Akkuträger $2',
            '~(Dynamo) (- \d+ Watt)~'                   => '$1 - Akkuträger $2',
        ],
    ],
    'product_names' => [
        'Aspire' => [
            // Aspire
            '~(Nepho)~',
            '~(Athos)~',
            '~(Atlantis Evo)~',
            '~(PockeX)~',
            '~((Cobble)( AIO)?)~',
            '~((Spryte)( AIO)?)~',
            '~(Proteus)~',
            '~(Typhon)~',
            '~(Speeder)~',
            '~(Puxos)~',
            '~((Triton)( 2)?)~',
            '~((Breeze)( 2)?)~',
            '~((Zelos)( 2.0)?)~',
            '~(Revo( Mini)?)~',
            '~(Nautilus(( 2S?)|( X)|( Mini)|( AIO))?)~',
            '~(Cleito( 120)?( Pro)?)~',
            '~(SkyStar( Revvo)?)~',
            '~(SkyStar( Revvo)?)~',
            '~((Revvo)( Mini)?)~',
            '~((K\d)( \& K3)?)~',
        ]
    ],
    'group_names'     => [
        'STAERKE'           => 'Nikotinstärke',
        'WIDERSTAND'        => 'Widerstand',
        'PACKUNG'           => 'Packungsgröße',
        'FARBE'             => 'Farbe',
        'DURCHMESSER'       => 'Durchmesser',
        'GLAS'              => 'Glas',
    ],
    'option_names' => [
        '100PG' => '100% PG',
        '100VG' => '100% VG',
        '24 GA*2+32 GA' => '24 GA * 2 + 32 GA',
        '26 GA*3+36 GA' => '26 GA * 3 + 36 GA',
        '26 GA*2+30 GA' => '26 GA * 2 + 30 GA',
        '28 GA*2+30 GA' => '28 GA * 2 + 30 GA',
        '28 GA*2+32 GA' => '28 GA * 2 + 32 GA',
        '28 GA*3+36 GA' => '28 GA * 3 + 36 GA',
        '30 GA*3+38 GA' => '30 GA * 3 + 38 GA',
        '50PG / 50VG'   => 'VG/PG: 50/50',
        '70VG / 30PG'   => 'VG/PG: 70/30',
        '80VG / 20PG'   => 'VG/PG: 80/20',
        'Kompass bronze' => 'kompass-bronze',
        'Kompass schwarz' => 'kompass-schwarz',
        'auto pink'     => 'auto-pink',
        'chrome'        => 'chrom',
        'dunkler Marmor' => 'dunkel-marmor',
        'gebürstete bronze' => 'bronze (gebürstet)',
        'gebürsteter Stahl' => 'stahl (gebürstet)',
        'gebürstetes schwarz-silber' => 'schwarz-silber (gebürstet)',
        'gebürstetes silber' => 'silber (gebürstet)',
        'komplett schwarz'  => 'schwarz',
        'metallic grau' => 'grau (metallic)',
        'metallic-resin' => 'resin (metallic)',
        'mosaik grau' => 'grau (mosaik)',
        'mosaik schwarz' => 'schwarz (mosaik)',
        'mosaik schwarz-weiss' => 'schwarz-weiß (mosaik)',
        'mosaik weiss' => 'weiß (mosaik)',
        'mosaik rot' => 'rot (mosaik)',
        'regenbogen-gelb' => 'gelb-regenbogen',
        'regenbogen-schwarz' => 'schwarz-regenbogen',
        'schwarz / grün sprayed' => 'schwarz-grün (sprayed)',
        'schwarz / rot sprayed' => 'schwarz-rot (sprayed)',
        'schwarz / weiss sprayed' => 'schwarz-weiß (sprayed)',
    ],
    'variant_codes'         => [],
    'manufacturers'         => [
        'Smok'     => [
            'supplier'      => 'Smoktech',
            'brand'         => 'Smok'
        ],
        'Renova'     => [
            'supplier'      => 'Vaporesso',
            'brand'         => 'Renova',
        ],
        'Dexter`s Juice Lab'     => [
            'brand'     => 'Dexter\'s Juice Lab',
            'supplier'     => 'Dexter\'s Juice Lab',
        ]
    ],
    'categories'     => [
        'name' => [
            'preg_match' => [
                '~^SC - Base~'          => 'Basen & Shots',
                '~Atlantis EVO Tank~'   => 'Verdampfer',
                '~Feedlink~'            => 'Akkuträger',
                '~TWIST~'               => 'Shake & Vape',
                '~COTN~'                => 'Zubehör',
                '~(Werkzeug-Set)|(pinzette)|(Heizplatte)|(Dichtung)|(Glastank)|(Mundstück)~' => 'Zubehör',
                '~Verdampferkopf~'      => ' Zubehör',
                '~(Shot)~'              => 'Basen & Shots',
                '~- Aroma~'             => 'Aromen',
                '~Liquid~'              => 'Liquid',
                '~0 mg/ml~'             => 'Shake & Vape',
                '~Flavor~'              => 'Aromen',
                '~Vampire Vape.*Limited Edition~' => 'Aromen',
                '~iWu Abdeck~'          => 'Zubehör',
                '~Ladegerät~'           => 'Ladegeräte',
            ]
        ],
        'category' => [
            'preg_match' => [
                '~Liquids \> Easy 3 Caps~'  => 'Liquids > Easy 3 Caps',
                '~E-Zigaretten~'            => 'E-Zigaretten',
                '~^Alt > Joye~'             => 'Zubehör',
                '~Clearomizer~'             => 'Verdampfer',
                '~^Box Mods~'               => 'Akkuträger',
                '~Ladegerät~'               => 'Ladegeräte',
                '~Akku-Zellen \& Zubehör~'  => 'Akkuzellen & Zubehör',
                '~((Aspire)|(InnoCigs)|(Steamax)) Zubehör~'  => 'Zubehör',
                '~Shake & Vape~'            => 'Shake & Vape',
                '~VLADS VG~'                => 'Liquids',
                '~Basen und Shots~'         => 'Basen & Shots',
                '~Vaporizer~'               => 'Vaporizer',
                '~Zubehör~'                 => 'Zubehör',
            ],
        ],
    ],

    'innocigs_brands' => [ 'SC', 'Steamax', 'InnoCigs', 'Innocigs'],
    'innocigs_manufacturers' => ['SC', 'Steamax', 'InnoCigs', 'Innocigs', 'Akkus'],

    'articles'     => 'This key is reserverd for PropertyMapperFactory',
    'log' => [
        'brand',
        'supplier',
        'option',
        'name',
        'replacement',
        'category',
    ]
];